# 00 — Build NIR UCO database

This notebook builds the NIR UCO image-level and object-level databases from the raw `.mat` file.

Main outputs:

- `image_db`: image-level database with cubes, segmentation masks, labels and metadata.
- `object_db`: object-level database with object masks, spectra, geometry and metadata.
- HDF5 database file for reuse in the next notebooks.
- CSV summaries for quick quality control.

In [1]:
from __future__ import annotations

import sys
import json
import time
from pathlib import Path

import numpy as np
import pandas as pd

# Notebook display
pd.set_option("display.max_columns", 120)
pd.set_option("display.max_rows", 200)

# ---------------------------------------------------------------------
# Project root detection
# ---------------------------------------------------------------------
CURRENT_DIR = Path.cwd().resolve()

# If the notebook is launched from notebooks/, project root is parent.
if (CURRENT_DIR / "src").exists():
    PROJECT_ROOT = CURRENT_DIR
elif (CURRENT_DIR.parent / "src").exists():
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    raise RuntimeError(
        "Could not find project root. Launch the notebook from the project "
        "root or from the notebooks/ folder."
    )

SRC_DIR = PROJECT_ROOT / "src"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("SRC_DIR:", SRC_DIR)

PROJECT_ROOT: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts
SRC_DIR: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\src

In [2]:
from src.io.dataload import load_mat_file
from src.data.database import (
    parse_image_key,
    preprocess_nir_uco_cube,
    build_minimal_nir_uco_object_database,
    detect_known_image_keys, 
    resolve_selected_keys,
)
from src.io.database_h5 import (
    save_nir_uco_h5,
    load_nir_uco_h5,
)
from src.utils import make_wavelengths, save_parquet

from src.visualization.plot_images import (
    plot_label_overlay_from_image_db,
)

from src.visualization.plot_objects import (
    plot_object_grid,
    plot_object_view,
)

from src.visualization.tables import (
    build_database_inventory_table,
)

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
# ---------------------------------------------------------------------
# Input path
# ---------------------------------------------------------------------
RAW_MAT_PATH = PROJECT_ROOT / "HSI Data" / "NIR camera UCO (889-1702 nm)" / "NIR_uco_sb.mat"

# ---------------------------------------------------------------------
# Output paths
# ---------------------------------------------------------------------
PROCESSED_DIR = PROJECT_ROOT / "HSI Data" / "processed"
RESULTS_DIR = PROJECT_ROOT / "results" / "00_database"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

DB_H5_PATH = PROCESSED_DIR / "nir_uco_database.h5"

IMAGE_SUMMARY_PATH = RESULTS_DIR / "image_summary.parquet"
OBJECT_SUMMARY_PATH = RESULTS_DIR / "object_summary.parquet"
DATABASE_MANIFEST_PATH = RESULTS_DIR / "database_manifest.parquet"

# ---------------------------------------------------------------------
# Database construction parameters
# ---------------------------------------------------------------------
WAVELENGTH_MODE = "non_noisy_all"
RESULTS_TAG = "non_noisy_all"

N_START = 889
N_END = 1702
N_BANDS_RAW = 69
N_REMOVE_START = 6
N_STOP_END = None
DATA_MODE = "reflectance"

# Object extraction filter after segmentation.
OBJECT_MIN_AREA = 10

FORCED_SPLIT = "projection"

# Whether to skip images whose name does not match the naming convention.
SKIP_UNKNOWN = True

# If None, all valid 3D arrays from the raw .mat file are processed.
SELECTED_KEYS = None

# HDF5 options
INCLUDE_HEAVY_OBJECT_ARRAYS = False
OVERWRITE_OUTPUTS = True

# ---------------------------------------------------------------------
# Segmentation parameters
# ---------------------------------------------------------------------
SEGMENTATION_KWARGS = {
    "reference_method": "max",
    "threshold_method": "fixed",
    "tau_min": 0.02,
    "min_area": 10,
    "opening_radius": 0,
    "closing_radius": 1,
    "fill_holes": True,
    "min_distance": 10,
    "min_area": OBJECT_MIN_AREA,
    "use_watershed": False,
}

# ---------------------------------------------------------------------
# QC plots
# ---------------------------------------------------------------------
RUN_QC_PLOTS = True
N_QC_IMAGES = 3
N_QC_OBJECTS = 20

print("RAW_MAT_PATH:", RAW_MAT_PATH)
print("DB_H5_PATH:", DB_H5_PATH)
print("IMAGE_SUMMARY_PATH:", IMAGE_SUMMARY_PATH)
print("OBJECT_SUMMARY_PATH:", OBJECT_SUMMARY_PATH)
print("DATABASE_MANIFEST_PATH:", DATABASE_MANIFEST_PATH)
print("WAVELENGTH_MODE:", WAVELENGTH_MODE)
print("OBJECT_MIN_AREA:", OBJECT_MIN_AREA)
print("FORCED_SPLIT:", FORCED_SPLIT)
print("SEGMENTATION_KWARGS:", SEGMENTATION_KWARGS)

RAW_MAT_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\HSI Data\NIR camera UCO (889-1702 nm)\NIR_uco_sb.mat
DB_H5_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\HSI Data\processed\nir_uco_database.h5
IMAGE_SUMMARY_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\image_summary.parquet
OBJECT_SUMMARY_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\object_summary.parquet
DATABASE_MANIFEST_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\database_manifest.parquet
WAVELENGTH_MODE: non_noisy_all
OBJECT_MIN_AREA: 10
FORCED_SPLIT: projection
SEGMENTATION_KWARGS: {'reference_method': 'max', 'threshold_method': 'fixed', 'tau_min': 0.02, 'min_area': 10, 'opening_radius': 0, 'closing_radius': 1, 'fill_holes': True, 'min_distance': 10, 'use_watershed': False}

In [5]:
if not RAW_MAT_PATH.exists():
    raise FileNotFoundError(
        f"Raw .mat file not found: {RAW_MAT_PATH}\n"
        "Update RAW_MAT_PATH in the parameters cell."
    )

output_paths = [
    DB_H5_PATH,
    IMAGE_SUMMARY_PATH,
    OBJECT_SUMMARY_PATH,
    DATABASE_MANIFEST_PATH,
]

existing_outputs = [p for p in output_paths if p.exists()]

if existing_outputs and not OVERWRITE_OUTPUTS:
    raise FileExistsError(
        "Some output files already exist:\n"
        + "\n".join(str(p) for p in existing_outputs)
        + "\nSet OVERWRITE_OUTPUTS=True if you want to overwrite them."
    )

print("Raw file found.")

Raw file found.

In [6]:
t0 = time.time()

raw_data = load_mat_file(RAW_MAT_PATH)

elapsed = time.time() - t0

print(f"Loaded raw data in {elapsed:.2f} s")
print(f"Number of entries in raw .mat file: {len(raw_data)}")
print("First keys:")
print(list(raw_data.keys())[:20])

Loaded raw data in 18.04 s
Number of entries in raw .mat file: 48
First keys:
['alm1pea1_sb', 'alm1pea2_sb', 'alm1pea3_sb', 'alm1pea4_sb', 'alm2pea1_sb', 'alm2pea2_sb', 'alm2pea3_sb', 'alm2pea4_sb', 'alm3pea1_sb', 'alm3pea2_sb', 'alm3pea3_sb', 'alm3pea4_sb', 'alm4pea1_sb', 'alm4pea2_sb', 'alm4pea3_sb', 'alm4pea4_sb', 'alm5pea1_sb', 'alm5pea2_sb', 'alm5pea3_sb', 'alm5pea4_sb']

In [7]:
raw_entries = []

for key, value in raw_data.items():
    arr = np.asarray(value)
    raw_entries.append({
        "key": key,
        "type": type(value).__name__,
        "ndim": arr.ndim,
        "shape": arr.shape,
        "dtype": str(arr.dtype),
        "is_candidate_cube": bool(arr.ndim == 3),
    })

raw_entries_df = pd.DataFrame(raw_entries).sort_values(
    ["is_candidate_cube", "key"],
    ascending=[False, True],
).reset_index(drop=True)

raw_entries_df

             key     type  ndim           shape    dtype  is_candidate_cube
0    alm1pea1_sb  ndarray     3  (370, 318, 69)  float64               True
1    alm1pea2_sb  ndarray     3  (370, 318, 69)  float64               True
2    alm1pea3_sb  ndarray     3  (370, 318, 69)  float64               True
3    alm1pea4_sb  ndarray     3  (370, 318, 69)  float64               True
4    alm2pea1_sb  ndarray     3  (370, 318, 69)  float64               True
5    alm2pea2_sb  ndarray     3  (370, 318, 69)  float64               True
6    alm2pea3_sb  ndarray     3  (370, 318, 69)  float64               True
7    alm2pea4_sb  ndarray     3  (370, 318, 69)  float64               True
8    alm3pea1_sb  ndarray     3  (370, 318, 69)  float64               True
9    alm3pea2_sb  ndarray     3  (370, 318, 69)  float64               True
10   alm3pea3_sb  ndarray     3  (370, 318, 69)  float64               True
11   alm3pea4_sb  ndarray     3  (370, 318, 69)  float64               True
12   alm4pea1_sb  ndarray     3  (370, 318, 69)  float64               True
13   alm4pea2_sb  ndarray     3  (370, 318, 69)  float64               True
14   alm4pea3_sb  ndarray     3  (370, 318, 69)  float64               True
15   alm4pea4_sb  ndarray     3  (370, 318, 69)  float64               True
16   alm5pea1_sb  ndarray     3  (370, 318, 69)  float64               True
17   alm5pea2_sb  ndarray     3  (370, 318, 69)  float64               True
18   alm5pea3_sb  ndarray     3  (370, 318, 69)  float64               True
19   alm5pea4_sb  ndarray     3  (370, 318, 69)  float64               True
20    almond1_sb  ndarray     3  (370, 318, 69)  float64               True
21    almond2_sb  ndarray     3  (370, 318, 69)  float64               True
22    almond3_sb  ndarray     3  (370, 318, 69)  float64               True
23    almond4_sb  ndarray     3  (370, 318, 69)  float64               True
24  pea1_pos1_sb  ndarray     3  (370, 318, 69)  float64               True
25  pea1_pos2_sb  ndarray     3  (370, 318, 69)  float64               True
26  pea1_pos3_sb  ndarray     3  (370, 318, 69)  float64               True
27  pea1_pos4_sb  ndarray     3  (370, 318, 69)  float64               True
28  pea1_pos5_sb  ndarray     3  (370, 318, 69)  float64               True
29  pea2_pos1_sb  ndarray     3  (370, 318, 69)  float64               True
30  pea2_pos2_sb  ndarray     3  (370, 318, 69)  float64               True
31  pea2_pos3_sb  ndarray     3  (370, 318, 69)  float64               True
32  pea2_pos4_sb  ndarray     3  (370, 318, 69)  float64               True
33  pea2_pos5_sb  ndarray     3  (370, 318, 69)  float64               True
34  pea3_pos1_sb  ndarray     3  (370, 318, 69)  float64               True
35  pea3_pos2_sb  ndarray     3  (370, 318, 69)  float64               True
36  pea3_pos3_sb  ndarray     3  (370, 318, 69)  float64               True
37  pea3_pos4_sb  ndarray     3  (370, 318, 69)  float64               True
38  pea3_pos5_sb  ndarray     3  (370, 318, 69)  float64               True
39  pea4_pos1_sb  ndarray     3  (370, 318, 69)  float64               True
40  pea4_pos2_sb  ndarray     3  (370, 318, 69)  float64               True
41  pea4_pos3_sb  ndarray     3  (370, 318, 69)  float64               True
42  pea4_pos4_sb  ndarray     3  (370, 318, 69)  float64               True
43  pea4_pos5_sb  ndarray     3  (370, 318, 69)  float64               True
44    peanut1_sb  ndarray     3  (370, 318, 69)  float64               True
45    peanut2_sb  ndarray     3  (370, 318, 69)  float64               True
46    peanut3_sb  ndarray     3  (370, 318, 69)  float64               True
47    peanut4_sb  ndarray     3  (370, 318, 69)  float64               True

In [8]:
candidate_keys = raw_entries_df.loc[
    raw_entries_df["is_candidate_cube"],
    "key",
].tolist()

parsed_rows = []

for key in candidate_keys:
    meta = parse_image_key(key)
    arr = np.asarray(raw_data[key])
    parsed_rows.append({
        "original_key": meta["original_key"],
        "clean_key": meta["clean_key"],
        "sample_kind": meta["sample_kind"],
        "nut_type": meta["nut_type"],
        "batch": meta["batch"],
        "position_set": meta["position_set"],
        "is_pure": meta["is_pure"],
        "is_mixture": meta["is_mixture"],
        "is_position_reference": meta["is_position_reference"],
        "is_unknown": meta["is_unknown"],
        "description": meta["description"],
        "shape": arr.shape,
        "n_rows": arr.shape[0],
        "n_cols": arr.shape[1],
        "n_bands_raw": arr.shape[2],
    })

parsed_df = pd.DataFrame(parsed_rows).sort_values(
    ["sample_kind", "nut_type", "batch", "clean_key"],
    na_position="last",
).reset_index(drop=True)

parsed_df

,original_key,clean_key,sample_kind,nut_type,batch,position_set,is_pure,is_mixture,is_position_reference,is_unknown,description,shape,n_rows,n_cols,n_bands_raw
0,alm1pea1_sb,alm1pea1,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 1 + peanut batch 1,"(370, 318, 69)",370,318,69
1,alm1pea2_sb,alm1pea2,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 1 + peanut batch 2,"(370, 318, 69)",370,318,69
2,alm1pea3_sb,alm1pea3,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 1 + peanut batch 3,"(370, 318, 69)",370,318,69
3,alm1pea4_sb,alm1pea4,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 1 + peanut batch 4,"(370, 318, 69)",370,318,69
4,alm2pea1_sb,alm2pea1,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 2 + peanut batch 1,"(370, 318, 69)",370,318,69
5,alm2pea2_sb,alm2pea2,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 2 + peanut batch 2,"(370, 318, 69)",370,318,69
6,alm2pea3_sb,alm2pea3,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 2 + peanut batch 3,"(370, 318, 69)",370,318,69
7,alm2pea4_sb,alm2pea4,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 2 + peanut batch 4,"(370, 318, 69)",370,318,69
8,alm3pea1_sb,alm3pea1,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 3 + peanut batch 1,"(370, 318, 69)",370,318,69
9,alm3pea2_sb,alm3pea2,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 3 + peanut batch 2,"(370, 318, 69)",370,318,69
10,alm3pea3_sb,alm3pea3,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 3 + peanut batch 3,"(370, 318, 69)",370,318,69
11,alm3pea4_sb,alm3pea4,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 3 + peanut batch 4,"(370, 318, 69)",370,318,69
12,alm4pea1_sb,alm4pea1,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 4 + peanut batch 1,"(370, 318, 69)",370,318,69
13,alm4pea2_sb,alm4pea2,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 4 + peanut batch 2,"(370, 318, 69)",370,318,69
14,alm4pea3_sb,alm4pea3,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 4 + peanut batch 3,"(370, 318, 69)",370,318,69
15,alm4pea4_sb,alm4pea4,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 4 + peanut batch 4,"(370, 318, 69)",370,318,69
16,alm5pea1_sb,alm5pea1,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 5 + peanut batch 1,"(370, 318, 69)",370,318,69
17,alm5pea2_sb,alm5pea2,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 5 + peanut batch 2,"(370, 318, 69)",370,318,69
18,alm5pea3_sb,alm5pea3,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 5 + peanut batch 3,"(370, 318, 69)",370,318,69
19,alm5pea4_sb,alm5pea4,mixture,mixture,NaN,NaN,False,True,False,False,mixture: almond batch 5 + peanut batch 4,"(370, 318, 69)",370,318,69
20,pea1_pos1_sb,pea1_pos1,position_reference,peanut,1.0,1.0,False,False,True,False,peanut batch 1 in position set 1,"(370, 318, 69)",370,318,69
21,pea1_pos2_sb,pea1_pos2,position_reference,peanut,1.0,2.0,False,False,True,False,peanut batch 1 in position set 2,"(370, 318, 69)",370,318,69
22,pea1_pos3_sb,pea1_pos3,position_reference,peanut,1.0,3.0,False,False,True,False,peanut batch 1 in position set 3,"(370, 318, 69)",370,318,69
23,pea1_pos4_sb,pea1_pos4,position_reference,peanut,1.0,4.0,False,False,True,False,peanut batch 1 in position set 4,"(370, 318, 69)",370,318,69
24,pea1_pos5_sb,pea1_pos5,position_reference,peanut,1.0,5.0,False,False,True,False,peanut batch 1 in position set 5,"(370, 318, 69)",370,318,69
25,pea2_pos1_sb,pea2_pos1,position_reference,peanut,2.0,1.0,False,False,True,False,peanut batch 2 in position set 1,"(370, 318, 69)",370,318,69
26,pea2_pos2_sb,pea2_pos2,position_reference,peanut,2.0,2.0,False,False,True,False,peanut batch 2 in position set 2,"(370, 318, 69)",370,318,69
27,pea2_pos3_sb,pea2_pos3,position_reference,peanut,2.0,3.0,False,False,True,False,peanut batch 2 in position set 3,"(370, 318, 69)",370,318,69
28,pea2_pos4_sb,pea2_pos4,position_reference,peanut,2.0,4.0,False,False,True,False,peanut batch 2 in position set 4,"(370, 318, 69)",370,318,69
29,pea2_pos5_sb,pea2_pos5,position_reference,peanut,2.0,5.0,False,False,True,False,peanut batch 2 in position set 5,"(370, 318, 69)",370,318,69
30,pea3_pos1_sb,pea3_pos1,position_reference,peanut,3.0,1.0,False,False,True,False,peanut batch 3 in position set 1,"(370, 318, 69)",370,318,69
31,pea3_pos2_sb,pea3_pos2,position_reference,peanut,3.0,2.0,False,False,True,False,peanut batch 3 in position set 2,"(370, 318, 69)",370,318,69
32,pea3_pos3_sb,pea3_pos3,position_reference,peanut,3.0,3.0,False,False,True,False,peanut batch 3 in position set 3,"(370, 318, 69)",370,318,69
33,pea3_pos4_sb,pea3_pos4,position_reference,peanut,3.0,4.0,False,False,True,False,peanut batch 3 in position set 4,"(370, 318, 69)",370,318,69
34,pea3_pos5_sb,pea3_pos5,position_reference,peanut,3.0,5.0,False,False,True,False,peanut batch 3 in position set 5,"(370, 318, 69)",370,318,69
35,pea4_pos1_sb,pea4_pos1,position_reference,peanut,4.0,1.0,False,False,True,False,peanut batch 4 in position set 1,"(370, 318, 69)",370,318,69
36,pea4_pos2_sb,pea4_pos2,position_reference,peanut,4.0,2.0,False,False,True,False,peanut batch 4 in position set 2,"(370, 318, 69)",370,318,69
37,pea4_pos3_sb,pea4_pos3,position_reference,peanut,4.0,3.0,False,False,True,False,peanut batch 4 in position set 3,"(370, 318, 69)",370,318,69
38,pea4_pos4_sb,pea4_pos4,position_reference,peanut,4.0,4.0,False,False,True,False,peanut batch 4 in position set 4,"(370, 318, 69)",370,318,69
39,pea4_pos5_sb,pea4_pos5,position_reference,peanut,4.0,5.0,False,False,True,False,peanut batch 4 in position set 5,"(370, 318, 69)",370,318,69
40,almond1_sb,almond1,pure,almond,1.0,NaN,True,False,False,False,"pure almond, batch 1","(370, 318, 69)",370,318,69
41,almond2_sb,almond2,pure,almond,2.0,NaN,True,False,False,False,"pure almond, batch 2","(370, 318, 69)",370,318,69
42,almond3_sb,almond3,pure,almond,3.0,NaN,True,False,False,False,"pure almond, batch 3","(370, 318, 69)",370,318,69
43,almond4_sb,almond4,pure,almond,4.0,NaN,True,False,False,False,"pure almond, batch 4","(370, 318, 69)",370,318,69
44,peanut1_sb,peanut1,pure,peanut,1.0,NaN,True,False,False,False,"pure peanut, batch 1","(370, 318, 69)",370,318,69
45,peanut2_sb,peanut2,pure,peanut,2.0,NaN,True,False,False,False,"pure peanut, batch 2","(370, 318, 69)",370,318,69
46,peanut3_sb,peanut3,pure,peanut,3.0,NaN,True,False,False,False,"pure peanut, batch 3","(370, 318, 69)",370,318,69
47,peanut4_sb,peanut4,pure,peanut,4.0,NaN,True,False,False,False,"pure peanut, batch 4","(370, 318, 69)",370,318,69

In [9]:
if SELECTED_KEYS:
    selected_keys = resolve_selected_keys(raw_data, SELECTED_KEYS)
    detected_rows = [(key, parse_image_key(key)) for key in selected_keys]
    print(f"Selected images: {len(selected_keys)} user-selected image(s)")
else:
    detected_rows = detect_known_image_keys(raw_data, skip_non_cubes=True)
    selected_keys = [key for key, _ in detected_rows]
    print("Selected images: all automatically recognized images")

if not selected_keys:
    raise RuntimeError(
        "No recognized NIR UCO image was found. Check image names and parsing patterns."
    )

detected_df = pd.DataFrame([
    {
        "original_key": key,
        "clean_key": meta["clean_key"],
        "sample_kind": meta["sample_kind"],
        "nut_type": meta["nut_type"],
        "batch": meta["batch"],
        "position_set": meta["position_set"],
        "description": meta["description"],
    }
    for key, meta in detected_rows
])

display(detected_df)

print(f"Number of selected images: {len(selected_keys)}")
print(selected_keys)

Selected images: all automatically recognized images

,original_key,clean_key,sample_kind,nut_type,batch,position_set,description
0,alm1pea1_sb,alm1pea1,mixture,mixture,NaN,NaN,mixture: almond batch 1 + peanut batch 1
1,alm1pea2_sb,alm1pea2,mixture,mixture,NaN,NaN,mixture: almond batch 1 + peanut batch 2
2,alm1pea3_sb,alm1pea3,mixture,mixture,NaN,NaN,mixture: almond batch 1 + peanut batch 3
3,alm1pea4_sb,alm1pea4,mixture,mixture,NaN,NaN,mixture: almond batch 1 + peanut batch 4
4,alm2pea1_sb,alm2pea1,mixture,mixture,NaN,NaN,mixture: almond batch 2 + peanut batch 1
5,alm2pea2_sb,alm2pea2,mixture,mixture,NaN,NaN,mixture: almond batch 2 + peanut batch 2
6,alm2pea3_sb,alm2pea3,mixture,mixture,NaN,NaN,mixture: almond batch 2 + peanut batch 3
7,alm2pea4_sb,alm2pea4,mixture,mixture,NaN,NaN,mixture: almond batch 2 + peanut batch 4
8,alm3pea1_sb,alm3pea1,mixture,mixture,NaN,NaN,mixture: almond batch 3 + peanut batch 1
9,alm3pea2_sb,alm3pea2,mixture,mixture,NaN,NaN,mixture: almond batch 3 + peanut batch 2
10,alm3pea3_sb,alm3pea3,mixture,mixture,NaN,NaN,mixture: almond batch 3 + peanut batch 3
11,alm3pea4_sb,alm3pea4,mixture,mixture,NaN,NaN,mixture: almond batch 3 + peanut batch 4
12,alm4pea1_sb,alm4pea1,mixture,mixture,NaN,NaN,mixture: almond batch 4 + peanut batch 1
13,alm4pea2_sb,alm4pea2,mixture,mixture,NaN,NaN,mixture: almond batch 4 + peanut batch 2
14,alm4pea3_sb,alm4pea3,mixture,mixture,NaN,NaN,mixture: almond batch 4 + peanut batch 3
15,alm4pea4_sb,alm4pea4,mixture,mixture,NaN,NaN,mixture: almond batch 4 + peanut batch 4
16,alm5pea1_sb,alm5pea1,mixture,mixture,NaN,NaN,mixture: almond batch 5 + peanut batch 1
17,alm5pea2_sb,alm5pea2,mixture,mixture,NaN,NaN,mixture: almond batch 5 + peanut batch 2
18,alm5pea3_sb,alm5pea3,mixture,mixture,NaN,NaN,mixture: almond batch 5 + peanut batch 3
19,alm5pea4_sb,alm5pea4,mixture,mixture,NaN,NaN,mixture: almond batch 5 + peanut batch 4
20,almond1_sb,almond1,pure,almond,1.0,NaN,"pure almond, batch 1"
21,almond2_sb,almond2,pure,almond,2.0,NaN,"pure almond, batch 2"
22,almond3_sb,almond3,pure,almond,3.0,NaN,"pure almond, batch 3"
23,almond4_sb,almond4,pure,almond,4.0,NaN,"pure almond, batch 4"
24,pea1_pos1_sb,pea1_pos1,position_reference,peanut,1.0,1.0,peanut batch 1 in position set 1
25,pea1_pos2_sb,pea1_pos2,position_reference,peanut,1.0,2.0,peanut batch 1 in position set 2
26,pea1_pos3_sb,pea1_pos3,position_reference,peanut,1.0,3.0,peanut batch 1 in position set 3
27,pea1_pos4_sb,pea1_pos4,position_reference,peanut,1.0,4.0,peanut batch 1 in position set 4
28,pea1_pos5_sb,pea1_pos5,position_reference,peanut,1.0,5.0,peanut batch 1 in position set 5
29,pea2_pos1_sb,pea2_pos1,position_reference,peanut,2.0,1.0,peanut batch 2 in position set 1
30,pea2_pos2_sb,pea2_pos2,position_reference,peanut,2.0,2.0,peanut batch 2 in position set 2
31,pea2_pos3_sb,pea2_pos3,position_reference,peanut,2.0,3.0,peanut batch 2 in position set 3
32,pea2_pos4_sb,pea2_pos4,position_reference,peanut,2.0,4.0,peanut batch 2 in position set 4
33,pea2_pos5_sb,pea2_pos5,position_reference,peanut,2.0,5.0,peanut batch 2 in position set 5
34,pea3_pos1_sb,pea3_pos1,position_reference,peanut,3.0,1.0,peanut batch 3 in position set 1
35,pea3_pos2_sb,pea3_pos2,position_reference,peanut,3.0,2.0,peanut batch 3 in position set 2
36,pea3_pos3_sb,pea3_pos3,position_reference,peanut,3.0,3.0,peanut batch 3 in position set 3
37,pea3_pos4_sb,pea3_pos4,position_reference,peanut,3.0,4.0,peanut batch 3 in position set 4
38,pea3_pos5_sb,pea3_pos5,position_reference,peanut,3.0,5.0,peanut batch 3 in position set 5
39,pea4_pos1_sb,pea4_pos1,position_reference,peanut,4.0,1.0,peanut batch 4 in position set 1
40,pea4_pos2_sb,pea4_pos2,position_reference,peanut,4.0,2.0,peanut batch 4 in position set 2
41,pea4_pos3_sb,pea4_pos3,position_reference,peanut,4.0,3.0,peanut batch 4 in position set 3
42,pea4_pos4_sb,pea4_pos4,position_reference,peanut,4.0,4.0,peanut batch 4 in position set 4
43,pea4_pos5_sb,pea4_pos5,position_reference,peanut,4.0,5.0,peanut batch 4 in position set 5
44,peanut1_sb,peanut1,pure,peanut,1.0,NaN,"pure peanut, batch 1"
45,peanut2_sb,peanut2,pure,peanut,2.0,NaN,"pure peanut, batch 2"
46,peanut3_sb,peanut3,pure,peanut,3.0,NaN,"pure peanut, batch 3"
47,peanut4_sb,peanut4,pure,peanut,4.0,NaN,"pure peanut, batch 4"

Number of selected images: 48
['alm1pea1_sb', 'alm1pea2_sb', 'alm1pea3_sb', 'alm1pea4_sb', 'alm2pea1_sb', 'alm2pea2_sb', 'alm2pea3_sb', 'alm2pea4_sb', 'alm3pea1_sb', 'alm3pea2_sb', 'alm3pea3_sb', 'alm3pea4_sb', 'alm4pea1_sb', 'alm4pea2_sb', 'alm4pea3_sb', 'alm4pea4_sb', 'alm5pea1_sb', 'alm5pea2_sb', 'alm5pea3_sb', 'alm5pea4_sb', 'almond1_sb', 'almond2_sb', 'almond3_sb', 'almond4_sb', 'pea1_pos1_sb', 'pea1_pos2_sb', 'pea1_pos3_sb', 'pea1_pos4_sb', 'pea1_pos5_sb', 'pea2_pos1_sb', 'pea2_pos2_sb', 'pea2_pos3_sb', 'pea2_pos4_sb', 'pea2_pos5_sb', 'pea3_pos1_sb', 'pea3_pos2_sb', 'pea3_pos3_sb', 'pea3_pos4_sb', 'pea3_pos5_sb', 'pea4_pos1_sb', 'pea4_pos2_sb', 'pea4_pos3_sb', 'pea4_pos4_sb', 'pea4_pos5_sb', 'peanut1_sb', 'peanut2_sb', 'peanut3_sb', 'peanut4_sb']

In [10]:
image_type_summary = (
    parsed_df
    .groupby(["sample_kind", "nut_type"], dropna=False)
    .size()
    .reset_index(name="n_images")
    .sort_values(["sample_kind", "nut_type"])
)

batch_summary = (
    parsed_df
    .groupby(["sample_kind", "nut_type", "batch"], dropna=False)
    .size()
    .reset_index(name="n_images")
    .sort_values(["sample_kind", "nut_type", "batch"])
)

display(image_type_summary)
display(batch_summary)

          sample_kind nut_type  n_images
0             mixture  mixture        20
1  position_reference   peanut        20
2                pure   almond         4
3                pure   peanut         4

           sample_kind nut_type  batch  n_images
0              mixture  mixture    NaN        20
1   position_reference   peanut    1.0         5
2   position_reference   peanut    2.0         5
3   position_reference   peanut    3.0         5
4   position_reference   peanut    4.0         5
5                 pure   almond    1.0         1
6                 pure   almond    2.0         1
7                 pure   almond    3.0         1
8                 pure   almond    4.0         1
9                 pure   peanut    1.0         1
10                pure   peanut    2.0         1
11                pure   peanut    3.0         1
12                pure   peanut    4.0         1

In [11]:
wavelengths = make_wavelengths(start_nm=N_START, end_nm=N_END, original_bands=N_BANDS_RAW, n_remove_start=N_REMOVE_START, n_stop_end=N_STOP_END)

print("Wavelength axis built from fixed NIR UCO configuration.")
print("START_NM:", N_START)
print("END_NM:", N_END)
print("ORIGINAL_BANDS:", N_BANDS_RAW)
print("N_REMOVE_START:", N_REMOVE_START)
print("N_STOP_END:", N_STOP_END)
print("Number of wavelengths kept:", len(wavelengths))
print("First wavelengths:", wavelengths[:5])
print("Last wavelengths:", wavelengths[-5:])

Wavelength axis built from fixed NIR UCO configuration.
START_NM: 889
END_NM: 1702
ORIGINAL_BANDS: 69
N_REMOVE_START: 6
N_STOP_END: None
Number of wavelengths kept: 63
First wavelengths: [ 960.73529412  972.69117647  984.64705882  996.60294118 1008.55882353]
Last wavelengths: [1654.17647059 1666.13235294 1678.08823529 1690.04411765 1702.        ]

In [12]:
band_check_rows = []

for key in selected_keys:
    raw_cube = np.asarray(raw_data[key])
    clean_cube = preprocess_nir_uco_cube(raw_cube, n_remove_start=N_REMOVE_START, n_stop_end=N_STOP_END)

    band_check_rows.append({
        "key": key,
        "raw_shape": raw_cube.shape,
        "clean_shape": clean_cube.shape,
        "n_removed_start": N_REMOVE_START,
        "n_stop_end": N_STOP_END,
        "raw_min": float(np.nanmin(raw_cube)),
        "raw_max": float(np.nanmax(raw_cube)),
        "clean_min": float(np.nanmin(clean_cube)),
        "clean_max": float(np.nanmax(clean_cube)),
    })

band_check_df = pd.DataFrame(band_check_rows)

display(band_check_df)

if wavelengths is not None:
    expected_n_bands = band_check_df["clean_shape"].iloc[0][2]
    if len(wavelengths) != expected_n_bands:
        raise ValueError(
            f"wavelengths length ({len(wavelengths)}) does not match "
            f"clean cube band count ({expected_n_bands})."
        )

,key,raw_shape,clean_shape,n_removed_start,n_stop_end,raw_min,raw_max,clean_min,clean_max
0,alm1pea1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.639295,1.254187,-0.059712,1.254187
1,alm1pea2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.656057,0.983311,-0.022599,0.838548
2,alm1pea3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.772735,1.065624,-0.026507,0.865334
3,alm1pea4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.602139,1.308940,-0.022299,1.014218
4,alm2pea1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.666472,0.991487,-0.032010,0.829993
5,alm2pea2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-1.063412,1.129765,-0.038481,0.901163
6,alm2pea3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.758614,0.986584,-0.045499,0.812725
7,alm2pea4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.508938,1.294200,-0.033658,1.111447
8,alm3pea1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.601609,1.146167,-0.018868,1.026362
9,alm3pea2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.553906,1.076803,-0.003675,1.076803
10,alm3pea3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.796888,1.019553,-0.020804,0.903062
11,alm3pea4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.588328,1.277941,-0.021976,1.277941
12,alm4pea1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.564544,1.249980,-0.030892,0.903432
13,alm4pea2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.554586,1.176281,0.000000,0.979227
14,alm4pea3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.698723,1.338419,-0.015113,0.953819
15,alm4pea4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.522363,1.087628,-0.035714,0.965829
16,alm5pea1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.565226,1.117321,-0.018898,0.860296
17,alm5pea2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.627373,1.176281,-0.035049,1.027992
18,alm5pea3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.599134,1.155427,-0.032017,0.976479
19,alm5pea4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.635205,1.102581,-0.017376,0.965388
20,almond1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.636029,1.086040,-0.020620,0.946537
21,almond2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.612211,1.038601,-0.021183,0.858365
22,almond3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.634336,1.064208,-0.032221,0.895927
23,almond4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.554152,1.111754,-0.137935,0.976905
24,pea1_pos1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.637174,1.065181,-0.006008,0.951310
25,pea1_pos2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.730471,1.144468,0.000000,0.722485
26,pea1_pos3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.659928,1.020124,-0.003036,1.020124
27,pea1_pos4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.404559,0.847150,0.000000,0.797860
28,pea1_pos5_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.320069,0.915037,-0.015521,0.859312
29,pea2_pos1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.553586,0.910127,-0.016817,0.805330
30,pea2_pos2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.502663,0.978002,0.000000,0.899746
31,pea2_pos3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.478632,0.982546,-0.006136,0.777999
32,pea2_pos4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.309139,0.970040,0.000000,0.837370
33,pea2_pos5_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.357322,1.020438,-0.013022,0.827999
34,pea3_pos1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.665399,1.218316,-0.000020,0.765378
35,pea3_pos2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.662646,0.898674,-0.000573,0.756436
36,pea3_pos3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.574024,1.107289,-0.006946,0.803617
37,pea3_pos4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.318334,0.882276,0.000000,0.703040
38,pea3_pos5_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.401579,0.945554,-0.039068,0.849087
39,pea4_pos1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.331016,0.908503,0.000000,0.908503
40,pea4_pos2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.377136,0.885534,0.000000,0.883045
41,pea4_pos3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.309299,0.848846,0.000000,0.848846
42,pea4_pos4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.708480,0.818867,0.000000,0.700086
43,pea4_pos5_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.321119,0.958323,0.000000,0.958323
44,peanut1_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.510248,1.111339,-0.010083,1.016183
45,peanut2_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.720593,1.099750,-0.005373,0.975594
46,peanut3_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.631650,1.008047,-0.017288,0.863229
47,peanut4_sb,"(370, 318, 69)","(370, 318, 63)",6,None,-0.668336,1.144443,-0.013706,0.923257

In [13]:
print("Building NIR UCO databases...")
print(f"Number of images to process: {len(selected_keys)}")
print("Segmentation parameters:")
print(json.dumps(SEGMENTATION_KWARGS, indent=2))
print("Object extraction min_area:", OBJECT_MIN_AREA)
print("Forced split:", FORCED_SPLIT)

t0 = time.time()

object_db, image_db = build_minimal_nir_uco_object_database(
    data=raw_data,
    selected_keys=selected_keys,
    preprocess_func=preprocess_nir_uco_cube,
    n_remove_start=N_REMOVE_START,
    n_stop_end=N_STOP_END,
    wavelengths=wavelengths,
    data_mode=DATA_MODE,
    min_area=OBJECT_MIN_AREA,
    split=FORCED_SPLIT,
    skip_unknown=SKIP_UNKNOWN,
    segmentation_kwargs=SEGMENTATION_KWARGS,
)

elapsed = time.time() - t0

print("\nDone.")
print(f"Elapsed time: {elapsed:.2f} s")
print(f"Number of images in image_db: {len(image_db)}")
print(f"Number of objects in object_db: {len(object_db)}")

Building NIR UCO databases...
Number of images to process: 48
Segmentation parameters:
{
  "reference_method": "max",
  "threshold_method": "fixed",
  "tau_min": 0.02,
  "min_area": 10,
  "opening_radius": 0,
  "closing_radius": 1,
  "fill_holes": true,
  "min_distance": 10,
  "use_watershed": false
}
Object extraction min_area: 10
Forced split: projection
Processing alm1pea1_sb | kind=mixture | components={'almond': {'batch': 1, 'token': 'alm'}, 'peanut': {'batch': 1, 'token': 'pea'}}

C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\src\data\segmentation.py:118: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = morphology.remove_small_objects(mask, min_size=min_area)

  -> 42 objects detected
Processing alm1pea2_sb | kind=mixture | components={'almond': {'batch': 1, 'token': 'alm'}, 'peanut': {'batch': 2, 'token': 'pea'}}
  -> 40 objects detected
Processing alm1pea3_sb | kind=mixture | components={'almond': {'batch': 1, 'token': 'alm'}, 'peanut': {'batch': 3, 'token': 'pea'}}
  -> 40 objects detected
Processing alm1pea4_sb | kind=mixture | components={'almond': {'batch': 1, 'token': 'alm'}, 'peanut': {'batch': 4, 'token': 'pea'}}
  -> 27 objects detected
Processing alm2pea1_sb | kind=mixture | components={'almond': {'batch': 2, 'token': 'alm'}, 'peanut': {'batch': 1, 'token': 'pea'}}
  -> 40 objects detected
Processing alm2pea2_sb | kind=mixture | components={'almond': {'batch': 2, 'token': 'alm'}, 'peanut': {'batch': 2, 'token': 'pea'}}
  -> 40 objects detected
Processing alm2pea3_sb | kind=mixture | components={'almond': {'batch': 2, 'token': 'alm'}, 'peanut': {'batch': 3, 'token': 'pea'}}
  -> 44 objects detected
Processing alm2pea4_sb | kind=mixture | components={'almond': {'batch': 2, 'token': 'alm'}, 'peanut': {'batch': 4, 'token': 'pea'}}
  -> 33 objects detected
Processing alm3pea1_sb | kind=mixture | components={'almond': {'batch': 3, 'token': 'alm'}, 'peanut': {'batch': 1, 'token': 'pea'}}
  -> 42 objects detected
Processing alm3pea2_sb | kind=mixture | components={'almond': {'batch': 3, 'token': 'alm'}, 'peanut': {'batch': 2, 'token': 'pea'}}
  -> 39 objects detected
Processing alm3pea3_sb | kind=mixture | components={'almond': {'batch': 3, 'token': 'alm'}, 'peanut': {'batch': 3, 'token': 'pea'}}
  -> 39 objects detected
Processing alm3pea4_sb | kind=mixture | components={'almond': {'batch': 3, 'token': 'alm'}, 'peanut': {'batch': 4, 'token': 'pea'}}
  -> 34 objects detected
Processing alm4pea1_sb | kind=mixture | components={'almond': {'batch': 4, 'token': 'alm'}, 'peanut': {'batch': 1, 'token': 'pea'}}
  -> 30 objects detected
Processing alm4pea2_sb | kind=mixture | components={'almond': {'batch': 4, 'token': 'alm'}, 'peanut': {'batch': 2, 'token': 'pea'}}
  -> 31 objects detected
Processing alm4pea3_sb | kind=mixture | components={'almond': {'batch': 4, 'token': 'alm'}, 'peanut': {'batch': 3, 'token': 'pea'}}
  -> 37 objects detected
Processing alm4pea4_sb | kind=mixture | components={'almond': {'batch': 4, 'token': 'alm'}, 'peanut': {'batch': 4, 'token': 'pea'}}
  -> 36 objects detected
Processing alm5pea1_sb | kind=mixture | components={'almond': {'batch': 5, 'token': 'alm'}, 'peanut': {'batch': 1, 'token': 'pea'}}
  -> 32 objects detected
Processing alm5pea2_sb | kind=mixture | components={'almond': {'batch': 5, 'token': 'alm'}, 'peanut': {'batch': 2, 'token': 'pea'}}
  -> 33 objects detected
Processing alm5pea3_sb | kind=mixture | components={'almond': {'batch': 5, 'token': 'alm'}, 'peanut': {'batch': 3, 'token': 'pea'}}
  -> 38 objects detected
Processing alm5pea4_sb | kind=mixture | components={'almond': {'batch': 5, 'token': 'alm'}, 'peanut': {'batch': 4, 'token': 'pea'}}
  -> 25 objects detected
Processing almond1_sb | kind=pure | components={'almond': {'batch': 1, 'token': 'almond'}}
  -> 52 objects detected
Processing almond2_sb | kind=pure | components={'almond': {'batch': 2, 'token': 'almond'}}
  -> 59 objects detected
Processing almond3_sb | kind=pure | components={'almond': {'batch': 3, 'token': 'almond'}}
  -> 55 objects detected
Processing almond4_sb | kind=pure | components={'almond': {'batch': 4, 'token': 'almond'}}
  -> 48 objects detected
Processing pea1_pos1_sb | kind=position_reference | components={'peanut': {'batch': 1, 'token': 'pea'}}
  -> 15 objects detected
Processing pea1_pos2_sb | kind=position_reference | components={'peanut': {'batch': 1, 'token': 'pea'}}
  -> 15 objects detected
Processing pea1_pos3_sb | kind=position_reference | components={'peanut': {'batch': 1, 'token': 'pea'}}
  -> 15 objects detected
Processing pea1_pos4_sb | kind=position_reference | components={'peanut': {'batch': 1, 'token': 'pea'}}
  -> 1 objects detected
Processing pea1_pos5_sb | kind=position_reference | components={'peanut': {'batch': 1, 'token': 'pea'}}
  -> 1 objects detected
Processing pea2_pos1_sb | kind=position_reference | components={'peanut': {'batch': 2, 'token': 'pea'}}
  -> 15 objects detected
Processing pea2_pos2_sb | kind=position_reference | components={'peanut': {'batch': 2, 'token': 'pea'}}
  -> 15 objects detected
Processing pea2_pos3_sb | kind=position_reference | components={'peanut': {'batch': 2, 'token': 'pea'}}
  -> 15 objects detected
Processing pea2_pos4_sb | kind=position_reference | components={'peanut': {'batch': 2, 'token': 'pea'}}
  -> 1 objects detected
Processing pea2_pos5_sb | kind=position_reference | components={'peanut': {'batch': 2, 'token': 'pea'}}
  -> 1 objects detected
Processing pea3_pos1_sb | kind=position_reference | components={'peanut': {'batch': 3, 'token': 'pea'}}
  -> 15 objects detected
Processing pea3_pos2_sb | kind=position_reference | components={'peanut': {'batch': 3, 'token': 'pea'}}
  -> 15 objects detected
Processing pea3_pos3_sb | kind=position_reference | components={'peanut': {'batch': 3, 'token': 'pea'}}
  -> 15 objects detected
Processing pea3_pos4_sb | kind=position_reference | components={'peanut': {'batch': 3, 'token': 'pea'}}
  -> 1 objects detected
Processing pea3_pos5_sb | kind=position_reference | components={'peanut': {'batch': 3, 'token': 'pea'}}
  -> 1 objects detected
Processing pea4_pos1_sb | kind=position_reference | components={'peanut': {'batch': 4, 'token': 'pea'}}
  -> 1 objects detected
Processing pea4_pos2_sb | kind=position_reference | components={'peanut': {'batch': 4, 'token': 'pea'}}
  -> 1 objects detected
Processing pea4_pos3_sb | kind=position_reference | components={'peanut': {'batch': 4, 'token': 'pea'}}
  -> 1 objects detected
Processing pea4_pos4_sb | kind=position_reference | components={'peanut': {'batch': 4, 'token': 'pea'}}
  -> 1 objects detected
Processing pea4_pos5_sb | kind=position_reference | components={'peanut': {'batch': 4, 'token': 'pea'}}
  -> 1 objects detected
Processing peanut1_sb | kind=pure | components={'peanut': {'batch': 1, 'token': 'peanut'}}
  -> 46 objects detected
Processing peanut2_sb | kind=pure | components={'peanut': {'batch': 2, 'token': 'peanut'}}
  -> 52 objects detected
Processing peanut3_sb | kind=pure | components={'peanut': {'batch': 3, 'token': 'peanut'}}
  -> 53 objects detected
Processing peanut4_sb | kind=pure | components={'peanut': {'batch': 4, 'token': 'peanut'}}
  -> 29 objects detected

Done.
Elapsed time: 27.78 s
Number of images in image_db: 48
Number of objects in object_db: 1262

In [14]:
database_inventory_df = build_database_inventory_table(
    image_db=image_db,
    object_db=object_db,
)

display(database_inventory_df)

save_parquet(
    database_inventory_df,
    RESULTS_DIR / "database_inventory.parquet",
)

,nut_type,batch,sample_kind,n_objects,n_object_pixels,median_object_area,mean_object_area,n_source_images,n_images
0,mixture,NaN,mixture,NaN,NaN,NaN,NaN,NaN,20.0
1,unknown,NaN,mixture,722.0,63772.0,82.0,88.326870,20.0,NaN
2,peanut,1.0,position_reference,47.0,3388.0,69.0,72.085106,5.0,5.0
3,peanut,2.0,position_reference,47.0,3145.0,65.0,66.914894,5.0,5.0
4,peanut,3.0,position_reference,47.0,2998.0,59.0,63.787234,5.0,5.0
5,peanut,4.0,position_reference,5.0,683.0,127.0,136.600000,5.0,5.0
6,almond,1.0,pure,52.0,4176.0,78.0,80.307692,1.0,1.0
7,almond,2.0,pure,59.0,3753.0,61.0,63.610169,1.0,1.0
8,almond,3.0,pure,55.0,3615.0,63.0,65.727273,1.0,1.0
9,almond,4.0,pure,48.0,5237.0,111.0,109.104167,1.0,1.0
10,peanut,1.0,pure,46.0,3184.0,67.5,69.217391,1.0,1.0
11,peanut,2.0,pure,52.0,3871.0,72.5,74.442308,1.0,1.0
12,peanut,3.0,pure,53.0,3197.0,60.0,60.320755,1.0,1.0
13,peanut,4.0,pure,29.0,3164.0,107.0,109.103448,1.0,1.0

WindowsPath('C:/Users/alixg/OneDrive - Université Paris-Dauphine/hsi_nuts/results/00_database/database_inventory.parquet')

In [15]:
print("=" * 80)
print("Compatibility check with old script")
print("=" * 80)

print("Expected old-script-compatible settings:")
print(" - N_REMOVE_START :", N_REMOVE_START)
print(" - N_STOP_END     :", N_STOP_END)
print(" - OBJECT_MIN_AREA:", OBJECT_MIN_AREA)
print(" - FORCED_SPLIT   :", FORCED_SPLIT)
print(" - DATA_MODE      :", DATA_MODE)
print(" - wavelengths len:", len(wavelengths))
print()

print("Object split distribution:")
display(
    pd.Series(
        [obj.get("split") for obj in object_db.values()],
        name="split",
    ).value_counts(dropna=False).reset_index(name="n_objects")
)

print("Object area min / median / max:")
areas = np.asarray([obj["area_pixels"] for obj in object_db.values()])
print("min   :", areas.min())
print("median:", np.median(areas))
print("max   :", areas.max())

if areas.min() < OBJECT_MIN_AREA:
    print("[WARNING] Some objects have area below OBJECT_MIN_AREA.")
else:
    print("[OK] No extracted object below OBJECT_MIN_AREA.")

================================================================================
Compatibility check with old script
================================================================================
Expected old-script-compatible settings:
 - N_REMOVE_START : 6
 - N_STOP_END     : None
 - OBJECT_MIN_AREA: 10
 - FORCED_SPLIT   : projection
 - DATA_MODE      : reflectance
 - wavelengths len: 63

Object split distribution:

        split  n_objects
0  projection       1262

Object area min / median / max:
min   : 12
median: 77.0
max   : 224
[OK] No extracted object below OBJECT_MIN_AREA.

In [16]:
image_rows = []

for image_key, img in image_db.items():
    cube = np.asarray(img["cube"])
    labels = np.asarray(img["labels"])
    n_labels = int(labels.max()) if labels.size else 0

    image_rows.append({
        "clean_key": image_key,
        "image_id": img.get("image_id"),
        "sample_kind": img.get("sample_kind"),
        "nut_type": img.get("nut_type"),
        "batch": img.get("batch"),
        "position_set": img.get("position_set"),
        "is_pure": img.get("is_pure"),
        "is_mixture": img.get("is_mixture"),
        "is_position_reference": img.get("is_position_reference"),
        "n_objects": img.get("n_objects"),
        "n_labels": n_labels,
        "height": cube.shape[0],
        "width": cube.shape[1],
        "n_bands": cube.shape[2],
        "threshold": img.get("threshold"),
        "data_mode": img.get("data_mode"),
        "description": img.get("description"),
    })

image_summary_df = (
    pd.DataFrame(image_rows)
    .sort_values(["sample_kind", "nut_type", "batch", "clean_key"], na_position="last")
    .reset_index(drop=True)
)

image_summary_df

,clean_key,image_id,sample_kind,nut_type,batch,position_set,is_pure,is_mixture,is_position_reference,n_objects,n_labels,height,width,n_bands,threshold,data_mode,description
0,alm1pea1,alm1pea1_sb,mixture,mixture,NaN,NaN,False,True,False,42,42,370,318,63,0.02,reflectance,mixture: almond batch 1 + peanut batch 1
1,alm1pea2,alm1pea2_sb,mixture,mixture,NaN,NaN,False,True,False,40,40,370,318,63,0.02,reflectance,mixture: almond batch 1 + peanut batch 2
2,alm1pea3,alm1pea3_sb,mixture,mixture,NaN,NaN,False,True,False,40,40,370,318,63,0.02,reflectance,mixture: almond batch 1 + peanut batch 3
3,alm1pea4,alm1pea4_sb,mixture,mixture,NaN,NaN,False,True,False,27,27,370,318,63,0.02,reflectance,mixture: almond batch 1 + peanut batch 4
4,alm2pea1,alm2pea1_sb,mixture,mixture,NaN,NaN,False,True,False,40,40,370,318,63,0.02,reflectance,mixture: almond batch 2 + peanut batch 1
5,alm2pea2,alm2pea2_sb,mixture,mixture,NaN,NaN,False,True,False,40,40,370,318,63,0.02,reflectance,mixture: almond batch 2 + peanut batch 2
6,alm2pea3,alm2pea3_sb,mixture,mixture,NaN,NaN,False,True,False,44,44,370,318,63,0.02,reflectance,mixture: almond batch 2 + peanut batch 3
7,alm2pea4,alm2pea4_sb,mixture,mixture,NaN,NaN,False,True,False,33,33,370,318,63,0.02,reflectance,mixture: almond batch 2 + peanut batch 4
8,alm3pea1,alm3pea1_sb,mixture,mixture,NaN,NaN,False,True,False,42,42,370,318,63,0.02,reflectance,mixture: almond batch 3 + peanut batch 1
9,alm3pea2,alm3pea2_sb,mixture,mixture,NaN,NaN,False,True,False,39,39,370,318,63,0.02,reflectance,mixture: almond batch 3 + peanut batch 2
10,alm3pea3,alm3pea3_sb,mixture,mixture,NaN,NaN,False,True,False,39,39,370,318,63,0.02,reflectance,mixture: almond batch 3 + peanut batch 3
11,alm3pea4,alm3pea4_sb,mixture,mixture,NaN,NaN,False,True,False,34,34,370,318,63,0.02,reflectance,mixture: almond batch 3 + peanut batch 4
12,alm4pea1,alm4pea1_sb,mixture,mixture,NaN,NaN,False,True,False,30,30,370,318,63,0.02,reflectance,mixture: almond batch 4 + peanut batch 1
13,alm4pea2,alm4pea2_sb,mixture,mixture,NaN,NaN,False,True,False,31,31,370,318,63,0.02,reflectance,mixture: almond batch 4 + peanut batch 2
14,alm4pea3,alm4pea3_sb,mixture,mixture,NaN,NaN,False,True,False,37,37,370,318,63,0.02,reflectance,mixture: almond batch 4 + peanut batch 3
15,alm4pea4,alm4pea4_sb,mixture,mixture,NaN,NaN,False,True,False,36,36,370,318,63,0.02,reflectance,mixture: almond batch 4 + peanut batch 4
16,alm5pea1,alm5pea1_sb,mixture,mixture,NaN,NaN,False,True,False,32,32,370,318,63,0.02,reflectance,mixture: almond batch 5 + peanut batch 1
17,alm5pea2,alm5pea2_sb,mixture,mixture,NaN,NaN,False,True,False,33,33,370,318,63,0.02,reflectance,mixture: almond batch 5 + peanut batch 2
18,alm5pea3,alm5pea3_sb,mixture,mixture,NaN,NaN,False,True,False,38,38,370,318,63,0.02,reflectance,mixture: almond batch 5 + peanut batch 3
19,alm5pea4,alm5pea4_sb,mixture,mixture,NaN,NaN,False,True,False,25,25,370,318,63,0.02,reflectance,mixture: almond batch 5 + peanut batch 4
20,pea1_pos1,pea1_pos1_sb,position_reference,peanut,1.0,1.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 1 in position set 1
21,pea1_pos2,pea1_pos2_sb,position_reference,peanut,1.0,2.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 1 in position set 2
22,pea1_pos3,pea1_pos3_sb,position_reference,peanut,1.0,3.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 1 in position set 3
23,pea1_pos4,pea1_pos4_sb,position_reference,peanut,1.0,4.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 1 in position set 4
24,pea1_pos5,pea1_pos5_sb,position_reference,peanut,1.0,5.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 1 in position set 5
25,pea2_pos1,pea2_pos1_sb,position_reference,peanut,2.0,1.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 2 in position set 1
26,pea2_pos2,pea2_pos2_sb,position_reference,peanut,2.0,2.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 2 in position set 2
27,pea2_pos3,pea2_pos3_sb,position_reference,peanut,2.0,3.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 2 in position set 3
28,pea2_pos4,pea2_pos4_sb,position_reference,peanut,2.0,4.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 2 in position set 4
29,pea2_pos5,pea2_pos5_sb,position_reference,peanut,2.0,5.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 2 in position set 5
30,pea3_pos1,pea3_pos1_sb,position_reference,peanut,3.0,1.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 3 in position set 1
31,pea3_pos2,pea3_pos2_sb,position_reference,peanut,3.0,2.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 3 in position set 2
32,pea3_pos3,pea3_pos3_sb,position_reference,peanut,3.0,3.0,False,False,True,15,15,370,318,63,0.02,reflectance,peanut batch 3 in position set 3
33,pea3_pos4,pea3_pos4_sb,position_reference,peanut,3.0,4.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 3 in position set 4
34,pea3_pos5,pea3_pos5_sb,position_reference,peanut,3.0,5.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 3 in position set 5
35,pea4_pos1,pea4_pos1_sb,position_reference,peanut,4.0,1.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 4 in position set 1
36,pea4_pos2,pea4_pos2_sb,position_reference,peanut,4.0,2.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 4 in position set 2
37,pea4_pos3,pea4_pos3_sb,position_reference,peanut,4.0,3.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 4 in position set 3
38,pea4_pos4,pea4_pos4_sb,position_reference,peanut,4.0,4.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 4 in position set 4
39,pea4_pos5,pea4_pos5_sb,position_reference,peanut,4.0,5.0,False,False,True,1,1,370,318,63,0.02,reflectance,peanut batch 4 in position set 5
40,almond1,almond1_sb,pure,almond,1.0,NaN,True,False,False,52,52,370,318,63,0.02,reflectance,"pure almond, batch 1"
41,almond2,almond2_sb,pure,almond,2.0,NaN,True,False,False,59,59,370,318,63,0.02,reflectance,"pure almond, batch 2"
42,almond3,almond3_sb,pure,almond,3.0,NaN,True,False,False,55,55,370,318,63,0.02,reflectance,"pure almond, batch 3"
43,almond4,almond4_sb,pure,almond,4.0,NaN,True,False,False,48,48,370,318,63,0.02,reflectance,"pure almond, batch 4"
44,peanut1,peanut1_sb,pure,peanut,1.0,NaN,True,False,False,46,46,370,318,63,0.02,reflectance,"pure peanut, batch 1"
45,peanut2,peanut2_sb,pure,peanut,2.0,NaN,True,False,False,52,52,370,318,63,0.02,reflectance,"pure peanut, batch 2"
46,peanut3,peanut3_sb,pure,peanut,3.0,NaN,True,False,False,53,53,370,318,63,0.02,reflectance,"pure peanut, batch 3"
47,peanut4,peanut4_sb,pure,peanut,4.0,NaN,True,False,False,29,29,370,318,63,0.02,reflectance,"pure peanut, batch 4"

In [17]:
object_rows = []

for object_id, obj in object_db.items():
    centroid = obj.get("centroid", (np.nan, np.nan))

    object_rows.append({
        "object_id": object_id,
        "source_clean_key": obj.get("source_clean_key"),
        "source_image": obj.get("source_image"),
        "sample_kind": obj.get("sample_kind"),
        "image_nut_type": obj.get("image_nut_type"),
        "object_nut_type": obj.get("object_nut_type"),
        "batch": obj.get("batch"),
        "position_set": obj.get("position_set"),
        "split": obj.get("split"),
        "is_pure": obj.get("is_pure"),
        "is_mixture": obj.get("is_mixture"),
        "is_position_reference": obj.get("is_position_reference"),
        "label_id": obj.get("label_id"),
        "object_index": obj.get("object_index"),
        "area_pixels": obj.get("area_pixels"),
        "n_pixels": obj.get("n_pixels"),
        "n_bands": obj.get("n_bands"),
        "centroid_row": centroid[0] if centroid is not None else np.nan,
        "centroid_col": centroid[1] if centroid is not None else np.nan,
        "bbox": obj.get("bbox"),
        "data_mode": obj.get("data_mode"),
    })

object_summary_df = (
    pd.DataFrame(object_rows)
    .sort_values(["sample_kind", "object_nut_type", "batch", "source_clean_key", "object_index"], na_position="last")
    .reset_index(drop=True)
)

object_summary_df

,object_id,source_clean_key,source_image,sample_kind,image_nut_type,object_nut_type,batch,position_set,split,is_pure,is_mixture,is_position_reference,label_id,object_index,area_pixels,n_pixels,n_bands,centroid_row,centroid_col,bbox,data_mode
0,alm1pea1_obj001,alm1pea1,alm1pea1_sb,mixture,mixture,unknown,NaN,NaN,projection,False,True,False,1,1,84,84,63,85.726190,45.107143,"(81, 39, 92, 51)",reflectance
1,alm1pea1_obj002,alm1pea1,alm1pea1_sb,mixture,mixture,unknown,NaN,NaN,projection,False,True,False,2,2,73,73,63,87.739726,123.767123,"(82, 120, 94, 128)",reflectance
2,alm1pea1_obj003,alm1pea1,alm1pea1_sb,mixture,mixture,unknown,NaN,NaN,projection,False,True,False,3,3,91,91,63,90.032967,157.340659,"(85, 152, 96, 164)",reflectance
3,alm1pea1_obj004,alm1pea1,alm1pea1_sb,mixture,mixture,unknown,NaN,NaN,projection,False,True,False,4,4,73,73,63,93.589041,90.164384,"(88, 87, 100, 96)",reflectance
4,alm1pea1_obj005,alm1pea1,alm1pea1_sb,mixture,mixture,unknown,NaN,NaN,projection,False,True,False,5,5,126,126,63,98.825397,70.579365,"(91, 65, 107, 76)",reflectance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,peanut4_obj025,peanut4,peanut4_sb,pure,peanut,peanut,4.0,NaN,projection,True,False,False,25,25,195,195,63,286.112821,96.984615,"(278, 89, 295, 106)",reflectance
1258,peanut4_obj026,peanut4,peanut4_sb,pure,peanut,peanut,4.0,NaN,projection,True,False,False,26,26,99,99,63,294.868687,227.858586,"(287, 223, 302, 234)",reflectance
1259,peanut4_obj027,peanut4,peanut4_sb,pure,peanut,peanut,4.0,NaN,projection,True,False,False,27,27,124,124,63,295.508065,141.338710,"(288, 137, 304, 147)",reflectance
1260,peanut4_obj028,peanut4,peanut4_sb,pure,peanut,peanut,4.0,NaN,projection,True,False,False,28,28,88,88,63,303.704545,52.738636,"(299, 47, 311, 58)",reflectance
1261,peanut4_obj029,peanut4,peanut4_sb,pure,peanut,peanut,4.0,NaN,projection,True,False,False,29,29,101,101,63,307.732673,187.990099,"(303, 181, 314, 195)",reflectance

In [18]:
print("Image summary by sample kind and nut type")
display(
    image_summary_df
    .groupby(["sample_kind", "nut_type"], dropna=False)
    .agg(
        n_images=("clean_key", "count"),
        n_objects=("n_objects", "sum"),
    )
    .reset_index()
)

print("Object summary by sample kind and object nut type")
display(
    object_summary_df
    .groupby(["sample_kind", "object_nut_type"], dropna=False)
    .agg(
        n_objects=("object_id", "count"),
        median_area=("area_pixels", "median"),
        min_area=("area_pixels", "min"),
        max_area=("area_pixels", "max"),
    )
    .reset_index()
)

print("Object summary by batch")
display(
    object_summary_df
    .groupby(["sample_kind", "object_nut_type", "batch"], dropna=False)
    .agg(
        n_objects=("object_id", "count"),
        median_area=("area_pixels", "median"),
    )
    .reset_index()
)

Image summary by sample kind and nut type

          sample_kind nut_type  n_images  n_objects
0             mixture  mixture        20        722
1  position_reference   peanut        20        146
2                pure   almond         4        214
3                pure   peanut         4        180

Object summary by sample kind and object nut type

,sample_kind,object_nut_type,n_objects,median_area,min_area,max_area
0,mixture,unknown,722,82.0,16,224
1,position_reference,peanut,146,64.5,12,221
2,pure,almond,214,76.0,21,188
3,pure,peanut,180,70.0,15,195

Object summary by batch

           sample_kind object_nut_type  batch  n_objects  median_area
0              mixture         unknown    NaN        722         82.0
1   position_reference          peanut    1.0         47         69.0
2   position_reference          peanut    2.0         47         65.0
3   position_reference          peanut    3.0         47         59.0
4   position_reference          peanut    4.0          5        127.0
5                 pure          almond    1.0         52         78.0
6                 pure          almond    2.0         59         61.0
7                 pure          almond    3.0         55         63.0
8                 pure          almond    4.0         48        111.0
9                 pure          peanut    1.0         46         67.5
10                pure          peanut    2.0         52         72.5
11                pure          peanut    3.0         53         60.0
12                pure          peanut    4.0         29        107.0

In [19]:
save_parquet(image_summary_df, IMAGE_SUMMARY_PATH)
save_parquet(object_summary_df, OBJECT_SUMMARY_PATH)

print("Saved essential database summaries:")
print(" -", IMAGE_SUMMARY_PATH)
print(" -", OBJECT_SUMMARY_PATH)

Saved essential database summaries:
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\image_summary.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\object_summary.parquet

In [20]:
if RUN_QC_PLOTS:
    qc_image_keys = image_summary_df["clean_key"].head(N_QC_IMAGES).tolist()

    for image_key in qc_image_keys:
        print("QC image:", image_key)
        plot_label_overlay_from_image_db(
            image_db=image_db,
            image_key=image_key,
            base="image_ref",
            title=f"Segmentation labels — {image_key}",
            crop_to_objects=True,
            padding=5,
            show=True,
        )
else:
    print("QC plots skipped.")

QC image: alm1pea1

QC image: alm1pea2

QC image: alm1pea3

In [21]:
if RUN_QC_PLOTS and len(object_db) > 0:
    first_image_key = image_summary_df.loc[
        image_summary_df["n_objects"] > 0,
        "clean_key",
    ].iloc[0]

    print("Object grid for:", first_image_key)

    plot_object_grid(
        object_db,
        source_image=first_image_key,
        title=f"Detected objects — {first_image_key}",
        max_objects=N_QC_OBJECTS,
        show=True,
    )

    first_object_id = object_summary_df.loc[
        object_summary_df["source_clean_key"].eq(first_image_key),
        "object_id",
    ].iloc[0]

    print("Single object view:", first_object_id)

    plot_object_view(
        object_db,
        object_id=first_object_id,
        spectrum_field="mean_spectrum",
        show=True,
    )
else:
    print("Object QC plots skipped.")

Object grid for: alm1pea1

Single object view: alm1pea1_obj001

In [22]:
if OVERWRITE_OUTPUTS and DB_H5_PATH.exists():
    DB_H5_PATH.unlink()

saved_paths = []

saved_h5_path = save_nir_uco_h5(
    object_database=object_db,
    image_database=image_db,
    path=DB_H5_PATH,
    include_heavy_object_arrays=INCLUDE_HEAVY_OBJECT_ARRAYS,
    compression="gzip",
    compression_opts=4,
)
saved_paths.append(saved_h5_path)

print("Saved database:")
for path in saved_paths:
    print(f"  [OK] {path}")
    print(f"       size={path.stat().st_size / 1024**2:.2f} MB")

Saved database:
  [OK] C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\HSI Data\processed\nir_uco_database.h5
       size=115.60 MB

In [23]:
object_db_reload, image_db_reload = load_nir_uco_h5(
    DB_H5_PATH,
    reconstruct_heavy_object_arrays=True,
)

print("Reload check:")
print("Original image_db:", len(image_db))
print("Reloaded image_db:", len(image_db_reload))
print("Original object_db:", len(object_db))
print("Reloaded object_db:", len(object_db_reload))

assert len(image_db_reload) == len(image_db)
assert len(object_db_reload) == len(object_db)

# Check one object contains required fields after reload.
sample_object_id = next(iter(object_db_reload.keys()))
sample_obj = object_db_reload[sample_object_id]

required_object_fields = [
    "object_id",
    "source_clean_key",
    "object_nut_type",
    "mask",
    "spectra",
    "mean_spectrum",
    "median_spectrum",
    "std_spectrum",
    "positions_global",
    "bbox",
    "centroid",
]

missing = [field for field in required_object_fields if field not in sample_obj]

if missing:
    raise KeyError(f"Reloaded object is missing fields: {missing}")

print("Smoke test passed.")
print("Sample object:", sample_object_id)
print("Available keys:", sorted(sample_obj.keys()))

Reload check:
Original image_db: 48
Reloaded image_db: 48
Original object_db: 1262
Reloaded object_db: 1262
Smoke test passed.
Sample object: alm1pea1_obj001
Available keys: ['area_pixels', 'batch', 'bbox', 'centroid', 'components', 'cube_crop', 'data_mode', 'description', 'image_nut_type', 'image_ref_crop', 'is_mixture', 'is_position_reference', 'is_pure', 'is_unknown', 'label_id', 'mask', 'mask_global', 'mean_spectrum', 'median_spectrum', 'n_bands', 'n_pixels', 'object_id', 'object_index', 'object_nut_type', 'position_set', 'positions_global', 'positions_local', 'sample_kind', 'source_clean_key', 'source_image', 'spectra', 'split', 'std_spectrum', 'wavelengths']

In [24]:
database_manifest_df = pd.DataFrame([{
    "raw_mat_path": str(RAW_MAT_PATH),
    "db_h5_path": str(DB_H5_PATH),
    "results_dir": str(RESULTS_DIR),

    "data_mode": DATA_MODE,
    "wavelength_mode": WAVELENGTH_MODE,
    "results_tag": RESULTS_TAG,

    "start_nm": float(N_START),
    "end_nm": float(N_END),
    "original_bands": int(N_BANDS_RAW),
    "n_remove_start": int(N_REMOVE_START),
    "n_stop_end": N_STOP_END,
    "n_bands_non_noisy": int(len(wavelengths)),
    "min_wavelength_nm": float(np.min(wavelengths)),
    "max_wavelength_nm": float(np.max(wavelengths)),

    "min_area": int(OBJECT_MIN_AREA),
    "forced_split": FORCED_SPLIT,
    "skip_unknown": bool(SKIP_UNKNOWN),
    "include_heavy_object_arrays": bool(INCLUDE_HEAVY_OBJECT_ARRAYS),

    "n_images": int(len(image_db)),
    "n_objects": int(len(object_db)),
}])

save_parquet(database_manifest_df, DATABASE_MANIFEST_PATH)

print("Saved database manifest:")
print(DATABASE_MANIFEST_PATH)

display(database_manifest_df)

Saved database manifest:
C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\database_manifest.parquet

,raw_mat_path,db_h5_path,results_dir,data_mode,wavelength_mode,results_tag,start_nm,end_nm,original_bands,n_remove_start,n_stop_end,n_bands_non_noisy,min_wavelength_nm,max_wavelength_nm,min_area,forced_split,skip_unknown,include_heavy_object_arrays,n_images,n_objects
0,C:\Users\alixg\OneDrive - Université Paris-Dau...,C:\Users\alixg\OneDrive - Université Paris-Dau...,C:\Users\alixg\OneDrive - Université Paris-Dau...,reflectance,non_noisy_all,non_noisy_all,889.0,1702.0,69,6,None,63,960.735294,1702.0,10,projection,True,False,48,1262

In [25]:
print("00_building_database.ipynb completed.")
print()
print("Essential outputs:")
print(" -", DB_H5_PATH)
print(" -", IMAGE_SUMMARY_PATH)
print(" -", OBJECT_SUMMARY_PATH)
print(" -", DATABASE_MANIFEST_PATH)
print()
print("Next notebook:")
print("01_database_quality_check.ipynb")

00_building_database.ipynb completed.

Essential outputs:
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\HSI Data\processed\nir_uco_database.h5
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\image_summary.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\object_summary.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\00_database\database_manifest.parquet

Next notebook:
01_database_quality_check.ipynb