# 04A — SIMCA grid validation

Goal: run the main SIMCA grid search on pure validation data.

Protocol:

- calibration: pure peanut objects from batches 1 and 2;
- validation: pure almond and pure peanut objects from batch 3;
- no batch 4 is used in this notebook;
- no mixture image is used in this notebook.

This notebook produces a broad candidate panel. Robustness filtering is done later in:

`04B_simca_validation_robustness.ipynb`.

Essential outputs:

- `standard_grid_summary.parquet`
- `empirical_cv_grid_summary.parquet`
- `combined_grid_summary.parquet`
- `selected_candidate_configs.parquet`
- `grid_validation_protocol.parquet`

In [1]:
from __future__ import annotations

import sys
import json
import gc
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option("display.max_columns", 220)
pd.set_option("display.max_rows", 300)

CURRENT_DIR = Path.cwd().resolve()
if (CURRENT_DIR / "src").exists():
    PROJECT_ROOT = CURRENT_DIR
elif (CURRENT_DIR.parent / "src").exists():
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    raise RuntimeError(
        "Could not find project root. Run this notebook from the project root or notebooks/."
    )

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)

PROJECT_ROOT: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts

In [2]:
from src.io.database_h5 import load_nir_uco_h5

from src.utils import (
    save_parquet,
    save_parquet_if_nonempty,
    load_parquet,
    list_result_files,
)

from src.spectra.preprocessing_configs import normalize_preprocessing_configs
from src.spectra.band_selection import (
    select_wavelength_range_from_database,
    wavelength_selection_summary,
)

from src.decision.uncertainty import (
    calibrate_three_way_thresholds_by_config,
)

from src.workflows.simca import (
    make_target_train_filters,
    run_simca_pixel_projection_grid,
    run_simca_rule_variant_grid,
    refit_selected_simca_configs,
)

from src.workflows.simca_selection_utils import (
    normalize_simca_rule_columns,
    add_detection_selection_score,
    sort_detection_selection,
    add_reference_selection_scores,
    select_top_models,
    ensure_candidate_columns,
    fill_selected_config_defaults,
    summarize_parameter_tendencies,
    sequential_pareto_filter,
)

from src.visualization.plot_diagnostics import (
    plot_metric_heatmap,
)

%load_ext autoreload
%autoreload 2

# 1. Params & config

In [3]:
# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------
DB_H5_PATH = PROJECT_ROOT / "HSI Data" / "processed" / "nir_uco_database.h5"

# ---------------------------------------------------------------------
# Spectral configuration
# ---------------------------------------------------------------------
USE_WAVELENGTH_WINDOW = False
WAVELENGTH_MODE = "non_noisy_all"

WINDOW_MIN_NM = 1225.0
WINDOW_MAX_NM = 1675.0

if USE_WAVELENGTH_WINDOW:
    RESULTS_TAG = f"{int(WINDOW_MIN_NM)}_{int(WINDOW_MAX_NM)}"
else:
    RESULTS_TAG = "non_noisy_all"

# ---------------------------------------------------------------------
# Output paths
# ---------------------------------------------------------------------
RESULTS_DIR = PROJECT_ROOT / "results" / f"04A_simca_grid_validation_{RESULTS_TAG}"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

#STANDARD_GRID_SUMMARY_PATH = RESULTS_DIR / "standard_grid_summary.parquet"
#STANDARD_GRID_ERRORS_PATH = RESULTS_DIR / "standard_grid_errors.parquet"

#EMPIRICAL_GRID_SUMMARY_PATH = RESULTS_DIR / "empirical_cv_grid_summary.parquet"
#EMPIRICAL_GRID_ERRORS_PATH = RESULTS_DIR / "empirical_cv_grid_errors.parquet"

GRID_SUMMARY_PATH = RESULTS_DIR / "grid_summary.parquet"
PARETO_2WAY_PATH = RESULTS_DIR / "pareto_2way_candidates_large.parquet"
THREE_WAY_GRID_PATH = RESULTS_DIR / "three_way_threshold_grid.parquet"
SELECTED_CANDIDATE_CONFIGS_PATH = RESULTS_DIR / "selected_candidate_configs.parquet"
GRID_VALIDATION_PROTOCOL_PATH = RESULTS_DIR / "grid_validation_protocol.parquet"

PCA_SELECTED_PREPROCESSINGS_PATH = (
    PROJECT_ROOT
    / "results"
    / f"03_pca_{RESULTS_TAG}"
    / "pca_selected_preprocessings.parquet"
)



# ---------------------------------------------------------------------
# Detection protocol
# ---------------------------------------------------------------------
TARGET_CLASS = "peanut"
NON_TARGET_LABEL = "non_target"
REFERENCE_CLASSES = ("almond", TARGET_CLASS)

TRAIN_FILTERS = make_target_train_filters(
    target_class=TARGET_CLASS,
    train_batches=[1, 2],
)

VALIDATION_FILTERS = {
    "sample_kind": ["pure"],
    "object_nut_type": list(REFERENCE_CLASSES),
    "batch": [3],
}

# Explicitly documented but not used in 04A.
TEST_FILTERS = {
    "sample_kind": ["pure"],
    "object_nut_type": list(REFERENCE_CLASSES),
    "batch": [4],
}

# ---------------------------------------------------------------------
# Matrix search space
# ---------------------------------------------------------------------
RUN_ALL_PIXELS_STANDARD = False
RUN_EMPIRICAL_FOR_ALL_PIXELS = False

STANDARD_MATRIX_METHODS = [
    "object_mean",
    "object_median",
    "balanced_pixels",
]

if RUN_ALL_PIXELS_STANDARD:
    STANDARD_MATRIX_METHODS.append("all_pixels")

# ---------------------------------------------------------------------
# SIMCA rules
# ---------------------------------------------------------------------
SIMCA_RULE_VARIANTS_MAIN = (
    "simple_chi2",
    "simple_emp_cv",
    "alternative_chi2_fixed2",
    "alternative_chi2_emp_cv",
    "alternative_empHQ_fixed2",
    "alternative_empHQ_emp_cv",
    "data_driven_chi2",
    "data_driven_emp_cv",
    "combined_index_chi2",
)

# ---------------------------------------------------------------------
# Preprocessing search space
# ---------------------------------------------------------------------
DEFAULT_PREPROCESSING_CONFIGS = {
    "snv": ("snv",),
    "absorbance": ("absorbance",),
    "absorbance_snv": ("absorbance", "snv"),
    "absorbance_sg_smooth": ("absorbance", "sg_smooth"),
    "absorbance_sg_d1": ("absorbance", "sg_d1"),
    "absorbance_snv_sg_smooth": ("absorbance", "snv", "sg_smooth"),
    "absorbance_snv_sg_d1": ("absorbance", "snv", "sg_d1"),
    "snv_sg_d1": ("snv", "sg_d1"),
}


def _parse_preprocessing_steps(value):
    if isinstance(value, (list, tuple)):
        return tuple(str(v) for v in value)

    value = str(value)

    if "+" in value:
        return tuple(v.strip() for v in value.split("+") if v.strip())

    return (value.strip(),)


if PCA_SELECTED_PREPROCESSINGS_PATH.exists():
    pca_selected_preprocessings_df = load_parquet(PCA_SELECTED_PREPROCESSINGS_PATH)

    PREPROCESSING_CONFIGS = {
        str(row["preprocessing"]): _parse_preprocessing_steps(row["preprocessing_steps"])
        for _, row in pca_selected_preprocessings_df.drop_duplicates("preprocessing").iterrows()
    }

    print("Loaded preprocessing shortlist from PCA notebook:")
    print(PCA_SELECTED_PREPROCESSINGS_PATH)

else:
    pca_selected_preprocessings_df = pd.DataFrame()
    PREPROCESSING_CONFIGS = DEFAULT_PREPROCESSING_CONFIGS.copy()

    print("[WARNING] PCA preprocessing shortlist not found.")
    print("Using default preprocessing search space instead:")
    print(PCA_SELECTED_PREPROCESSINGS_PATH)

PREPROCESSING_CONFIGS = normalize_preprocessing_configs(PREPROCESSING_CONFIGS)

# ---------------------------------------------------------------------
# Hyperparameter search space
# ---------------------------------------------------------------------
N_COMPONENTS_VALUES = [3, 4, 5, 6, 7, 8, 10, 11, 12]
ALPHA_VALUES = [0.05, 0.01]
OBJECT_THRESHOLDS = [0.70, 0.75, 0.80, 0.85, 0.90]

M_VALUES = [40]
BALANCED_PIXEL_STRATEGY_VALUES = ["random", "center"]

SG_WINDOW_LENGTH_VALUES = [11]
SG_POLYORDER_VALUES = [2]
POSITION_DILATION_RADIUS_VALUES = [3]

DEFAULT_M = 40
DEFAULT_SG_WINDOW_LENGTH = 11
DEFAULT_SG_POLYORDER = 2

REPLACE_BALANCED_PIXELS = False
RANDOM_STATE = 42

CV_N_SPLITS = 5
CV_GROUP_COL = "object_id"

TWO_WAY_PARETO_PASSES = [
    {
        "name": "within_same_model_preprocessing",
        "group_cols": [
            "matrix_family",
            "training_matrix_id",
            "rule_variant",
            "limit_source",
            "n_components",
            "alpha",
            "object_threshold",
            "sg_window_length",
            "sg_polyorder",
            "position_dilation_radius",
            "m_effective",
            "balanced_pixel_strategy_effective",
        ],
        "minimize_cols": ["fn_rate", "fp_rate"],
        "maximize_cols": ["balanced_accuracy"],
    },
    {
        "name": "within_same_family_components",
        "group_cols": [
            "matrix_family",
            "n_components",
            "object_threshold",
        ],
        "minimize_cols": ["fn_rate", "fp_rate"],
        "maximize_cols": ["balanced_accuracy"],
    },
    {
        "name": "family_level_pareto",
        "group_cols": [
            "matrix_family",
        ],
        "minimize_cols": ["fn_rate", "fp_rate"],
        "maximize_cols": ["balanced_accuracy"],
    },
]

# ---------------------------------------------------------------------
# Runtime flags
# ---------------------------------------------------------------------
RUN_STANDARD_GRID = False
RUN_EMPIRICAL_CV_GRID = True
RUN_DIAGNOSTIC_PLOTS = True

# Important: broad panel, not final models.
N_SELECTED_PER_TRAINING_MATRIX = 8
N_SELECTED_PER_MATRIX_FAMILY = 25
N_SELECTED_OVERALL = 50

print("DB_H5_PATH:", DB_H5_PATH)
print("RESULTS_DIR:", RESULTS_DIR)
print("WAVELENGTH_MODE:", WAVELENGTH_MODE)
print("RESULTS_TAG:", RESULTS_TAG)
print("TRAIN_FILTERS:", TRAIN_FILTERS)
print("VALIDATION_FILTERS:", VALIDATION_FILTERS)
print("STANDARD_MATRIX_METHODS:", STANDARD_MATRIX_METHODS)
print("Number of preprocessing configs:", len(PREPROCESSING_CONFIGS))

Loaded preprocessing shortlist from PCA notebook:
C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\03_pca_non_noisy_all\pca_selected_preprocessings.parquet
DB_H5_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\HSI Data\processed\nir_uco_database.h5
RESULTS_DIR: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04A_simca_grid_validation_non_noisy_all
WAVELENGTH_MODE: non_noisy_all
RESULTS_TAG: non_noisy_all
TRAIN_FILTERS: {'sample_kind': ['pure'], 'object_nut_type': ['peanut'], 'batch': [1, 2]}
VALIDATION_FILTERS: {'sample_kind': ['pure'], 'object_nut_type': ['almond', 'peanut'], 'batch': [3]}
STANDARD_MATRIX_METHODS: ['object_mean', 'object_median', 'balanced_pixels']
Number of preprocessing configs: 13

In [4]:
if not DB_H5_PATH.exists():
    raise FileNotFoundError(f"Database not found: {DB_H5_PATH}. Run notebook 00 first.")

object_db, image_db = load_nir_uco_h5(
    DB_H5_PATH,
    reconstruct_heavy_object_arrays=True,
)

if USE_WAVELENGTH_WINDOW:
    object_db, image_db, wavelengths, wavelength_info = select_wavelength_range_from_database(
        object_db=object_db,
        image_db=image_db,
        min_nm=WINDOW_MIN_NM,
        max_nm=WINDOW_MAX_NM,
    )

    wavelength_selection_df = wavelength_selection_summary(wavelength_info)

else:
    first_obj = next(iter(object_db.values()))
    wavelengths = first_obj.get("wavelengths")
    wavelengths = np.asarray(wavelengths, dtype=float) if wavelengths is not None else None
    wavelength_selection_df = pd.DataFrame()

if wavelengths is None:
    raise RuntimeError("No wavelength axis found in object_db.")

wavelength_config_df = pd.DataFrame([{
    "wavelength_mode": WAVELENGTH_MODE,
    "use_wavelength_window": bool(USE_WAVELENGTH_WINDOW),
    "results_tag": RESULTS_TAG,
    "window_min_nm": WINDOW_MIN_NM if USE_WAVELENGTH_WINDOW else np.nan,
    "window_max_nm": WINDOW_MAX_NM if USE_WAVELENGTH_WINDOW else np.nan,
    "n_bands": int(len(wavelengths)),
    "min_wavelength_nm": float(np.min(wavelengths)),
    "max_wavelength_nm": float(np.max(wavelengths)),
}])

print("Number of images:", len(image_db))
print("Number of objects:", len(object_db))
display(wavelength_config_df)

object_meta_df = pd.DataFrame([
    {
        "object_id": object_id,
        "source_image": obj.get("source_clean_key"),
        "sample_kind": obj.get("sample_kind"),
        "object_nut_type": obj.get("object_nut_type"),
        "batch": obj.get("batch"),
        "split": obj.get("split"),
        "area_pixels": obj.get("area_pixels"),
        "n_pixels": obj.get("n_pixels"),
        "n_bands": obj.get("n_bands"),
    }
    for object_id, obj in object_db.items()
])

display(
    object_meta_df
    .groupby(["sample_kind", "object_nut_type", "batch"], dropna=False)
    .size()
    .reset_index(name="n_objects")
    .sort_values(["sample_kind", "object_nut_type", "batch"], na_position="last")
)

Number of images: 48
Number of objects: 1262

,wavelength_mode,use_wavelength_window,results_tag,window_min_nm,window_max_nm,n_bands,min_wavelength_nm,max_wavelength_nm
0,non_noisy_all,False,non_noisy_all,NaN,NaN,63,960.735294,1702.0

           sample_kind object_nut_type  batch  n_objects
0              mixture         unknown    NaN        722
1   position_reference          peanut    1.0         47
2   position_reference          peanut    2.0         47
3   position_reference          peanut    3.0         47
4   position_reference          peanut    4.0          5
5                 pure          almond    1.0         52
6                 pure          almond    2.0         59
7                 pure          almond    3.0         55
8                 pure          almond    4.0         48
9                 pure          peanut    1.0         46
10                pure          peanut    2.0         52
11                pure          peanut    3.0         53
12                pure          peanut    4.0         29

In [5]:
def load_parquet_or_empty(path: Path) -> pd.DataFrame:
    """Load a parquet file if it exists, otherwise return an empty dataframe."""
    if Path(path).exists():
        return load_parquet(path)
    return pd.DataFrame()


def display_available_columns(df: pd.DataFrame, columns: list[str], n: int = 20):
    """Display only columns available in a dataframe."""
    available = [col for col in columns if col in df.columns]
    if not available:
        display(df.head(n))
    else:
        display(df[available].head(n))

# 2. Grid search

In [6]:
grid_summary_df, grid_results, grid_errors_df = run_simca_rule_variant_grid(
    object_db=object_db,
    image_db=image_db,
    train_filters=TRAIN_FILTERS,
    projection_filters=VALIDATION_FILTERS,
    preprocessing_configs=PREPROCESSING_CONFIGS,
    matrix_methods=["object_mean", "object_median", "balanced_pixels"],
    rule_variants=SIMCA_RULE_VARIANTS_MAIN,
    n_components_values=N_COMPONENTS_VALUES,
    alpha_values=ALPHA_VALUES,
    object_thresholds=OBJECT_THRESHOLDS,
    m_values=M_VALUES,
    balanced_pixel_strategy_values=BALANCED_PIXEL_STRATEGY_VALUES,
    sg_window_length_values=SG_WINDOW_LENGTH_VALUES,
    sg_polyorder_values=SG_POLYORDER_VALUES,
    position_dilation_radius_values=POSITION_DILATION_RADIUS_VALUES,
    random_state=42,
    wavelengths=wavelengths,
    keep_pixel_tables=False,
    keep_cv_tables=False,
    verbose=True,
    target_class=TARGET_CLASS,
    non_target_label=NON_TARGET_LABEL,
)

[1/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[2/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[3/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[4/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[5/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[6/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[7/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[8/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[9/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[10/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[11/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[12/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[13/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[14/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[15/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[16/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[17/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[18/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d1 | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[19/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[20/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[21/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[22/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[23/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[24/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[25/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[26/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[27/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[28/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[29/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[30/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[31/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[32/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[33/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[34/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[35/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[36/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_d2 | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[37/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[38/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[39/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[40/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[41/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[42/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[43/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[44/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[45/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[46/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[47/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[48/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[49/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[50/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[51/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[52/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[53/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[54/936] empirical_cv | matrix=object_mean | preprocessing=absorbance | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[55/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[56/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[57/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[58/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[59/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[60/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[61/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[62/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[63/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[64/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[65/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[66/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[67/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[68/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[69/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[70/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[71/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[72/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_sg_smooth | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[73/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[74/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[75/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[76/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[77/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[78/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[79/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[80/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[81/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[82/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[83/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[84/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[85/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[86/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[87/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[88/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[89/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[90/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv_sg_smooth | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[91/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[92/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[93/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[94/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[95/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[96/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[97/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[98/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[99/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[100/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[101/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[102/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[103/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[104/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[105/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[106/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[107/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[108/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_msc | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[109/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[110/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[111/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[112/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[113/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[114/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[115/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[116/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[117/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[118/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[119/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[120/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[121/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[122/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[123/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[124/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[125/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[126/936] empirical_cv | matrix=object_mean | preprocessing=absorbance_snv | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[127/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[128/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[129/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[130/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[131/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[132/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[133/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[134/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[135/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[136/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[137/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[138/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[139/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[140/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[141/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[142/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[143/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[144/936] empirical_cv | matrix=object_mean | preprocessing=snv_sg_smooth | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[145/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[146/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[147/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=4 | alpha=0.05 | SG=(11,2) | dilation=3

[148/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=4 | alpha=0.01 | SG=(11,2) | dilation=3

[149/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=5 | alpha=0.05 | SG=(11,2) | dilation=3

[150/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=5 | alpha=0.01 | SG=(11,2) | dilation=3

[151/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=6 | alpha=0.05 | SG=(11,2) | dilation=3

[152/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=6 | alpha=0.01 | SG=(11,2) | dilation=3

[153/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=7 | alpha=0.05 | SG=(11,2) | dilation=3

[154/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=7 | alpha=0.01 | SG=(11,2) | dilation=3

[155/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=8 | alpha=0.05 | SG=(11,2) | dilation=3

[156/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=8 | alpha=0.01 | SG=(11,2) | dilation=3

[157/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=10 | alpha=0.05 | SG=(11,2) | dilation=3

[158/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=10 | alpha=0.01 | SG=(11,2) | dilation=3

[159/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=11 | alpha=0.05 | SG=(11,2) | dilation=3

[160/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=11 | alpha=0.01 | SG=(11,2) | dilation=3

[161/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=12 | alpha=0.05 | SG=(11,2) | dilation=3

[162/936] empirical_cv | matrix=object_mean | preprocessing=sg_smooth | A=12 | alpha=0.01 | SG=(11,2) | dilation=3

[163/936] empirical_cv | matrix=object_mean | preprocessing=raw | A=3 | alpha=0.05 | SG=(11,2) | dilation=3

[164/936] empirical_cv | matrix=object_mean | preprocessing=raw | A=3 | alpha=0.01 | SG=(11,2) | dilation=3

[165/936] empirical_cv | matrix=object_mean | preprocessing=raw | A=4 | alpha=0.05 | SG=(11,2) | dilation=3


In [7]:
grid_summary_df = normalize_simca_rule_columns(grid_summary_df)
grid_summary_df["selection_split"] = "validation_batch_3"
grid_summary_df["selection_strategy"] = "04A_grid_rule_variant_universe"

save_parquet(grid_summary_df, GRID_SUMMARY_PATH)

display_cols = [
    "model_family",
    "matrix_family",
    "training_matrix_id",
    "matrix_method",
    "balanced_pixel_strategy",
    "balanced_pixel_strategy_effective",
    "m",
    "m_effective",
    "preprocessing",
    "rule",
    "rule_variant",
    "selected_rule_name",
    "rule_for_refit",
    "limit_source",
    "n_components",
    "alpha",
    "object_threshold",
    "sg_window_length",
    "sg_polyorder",
    "position_dilation_radius",
    "balanced_accuracy",
    "target_sensitivity",
    "non_target_specificity",
    "fn_rate",
    "fp_rate",
    "f1_score",
    "accuracy",
    "selection_score",
    "score_conservative_target",
    "score_balanced_reference",
    "score_specificity_control",
]
display_cols = [col for col in display_cols if col in grid_summary_df.columns]

display(grid_summary_df[display_cols].head(30))

,model_family,matrix_family,training_matrix_id,matrix_method,balanced_pixel_strategy,balanced_pixel_strategy_effective,m,m_effective,preprocessing,rule,rule_variant,selected_rule_name,rule_for_refit,limit_source,n_components,alpha,object_threshold,sg_window_length,sg_polyorder,position_dilation_radius,balanced_accuracy,target_sensitivity,non_target_specificity,fn_rate,fp_rate,f1_score,accuracy,selection_score
0,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_chi2,simple_chi2,simple_chi2,chi2,7,0.01,0.75,11,2,3,0.945455,1.0,0.890909,0.0,0.109091,0.946429,0.944444,-0.042881
1,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_chi2,simple_chi2,simple_chi2,chi2,7,0.01,0.70,11,2,3,0.936364,1.0,0.872727,0.0,0.127273,0.938053,0.935185,-0.061666
2,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,7,0.05,0.75,11,2,3,0.927273,1.0,0.854545,0.0,0.145455,0.929825,0.925926,-0.080445
3,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.918182,1.0,0.836364,0.0,0.163636,0.921739,0.916667,-0.099216
4,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.05,0.75,11,2,3,0.918182,1.0,0.836364,0.0,0.163636,0.921739,0.916667,-0.099216
5,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,6,0.05,0.75,11,2,3,0.909091,1.0,0.818182,0.0,0.181818,0.913793,0.907407,-0.117980
6,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,6,0.05,0.75,11,2,3,0.909091,1.0,0.818182,0.0,0.181818,0.913793,0.907407,-0.117980
7,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,7,0.05,0.75,11,2,3,0.909091,1.0,0.818182,0.0,0.181818,0.913793,0.907407,-0.117980
8,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,7,0.05,0.75,11,2,3,0.909091,1.0,0.818182,0.0,0.181818,0.913793,0.907407,-0.117980
9,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.05,0.70,11,2,3,0.900000,1.0,0.800000,0.0,0.200000,0.905983,0.898148,-0.136738
10,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,6,0.05,0.70,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
11,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,6,0.05,0.70,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
12,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,11,0.05,0.75,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
13,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,11,0.05,0.75,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
14,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_empHQ_fixed2,alternative_empHQ_fixed2,alternative_empHQ_fixed2,chi2,7,0.05,0.80,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
15,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,data_driven,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,7,0.01,0.75,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
16,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,alternative,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
17,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,alternative,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,11,0.05,0.75,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
18,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
19,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
20,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
21,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,data_driven,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,7,0.01,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
22,empirical_cv_rule,pixel_matrix,balanced_pixel_center_m40,balanced_pixels,center,center,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.01,0.75,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
23,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,alternative,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,empirical_cv,11,0.05,0.70,11,2,3,0.872727,1.0,0.745455,0.0,0.254545,0.883333,0.870370,-0.192971
24,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_chi2,simple_chi2,simple_chi2,chi2,6,0.01,0.75,11,2,3,0.872727,1.0,0.745455,0.0,0.254545,0.883333,0.870370,-0.192971
25,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_empHQ_fixed2,alternative_empHQ_fixed2,alternative_empHQ_fixed2,chi2,7,0.05,0.75,11,2,3,0.872727,1.0,0.745455,0.0,0.254545,0.883333,0.870370,-0.192971
26,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_empHQ_fixed2,alternative_empHQ_fixed2,alternative_empHQ_fixed2,chi2,7,0.05,0.70,11,2,3,0.863636,1.0,0.727273,0.0,0.272727,0.876033,0.861111,-0.211703
27,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.01,0.80,11,2,3,0.863636,1.0,0.727273,0.0,0.272727,0.876033,0.861111,-0.211703
28,empirical_cv_rule,pixel_matrix,balanced_pixel_center_m40,balanced_pixels,center,center,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.01,0.70,11,2,3,0.863636,1.0,0.727273,0.0,0.272727,0.876033,0.861111,-0.211703
29,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,alternative,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,empirical_cv,7,0.05,0.75,11,2,3,0.854545,1.0,0.709091,0.0,0.290909,0.868852,0.851852,-0.230429

In [8]:
print("Columns available in grid_summary_df:")
print(sorted(grid_summary_df.columns))

print("\nNumber of configurations by family:")
display(
    grid_summary_df
    .groupby(["model_family", "matrix_family", "training_matrix_id"], dropna=False)
    .size()
    .reset_index(name="n_configs")
    .sort_values(["model_family", "matrix_family", "training_matrix_id"])
)

print("\nTop validation configurations:")
display(grid_summary_df[display_cols].head(30))

if RUN_DIAGNOSTIC_PLOTS and len(grid_summary_df) > 0:
    plot_metric_heatmap(
        grid_summary_df,
        index_col="preprocessing",
        columns_col="selected_rule_name",
        value_col="balanced_accuracy",
        title="Validation balanced accuracy by preprocessing and SIMCA rule",
        show=True,
    )

    plot_metric_heatmap(
        grid_summary_df,
        index_col="preprocessing",
        columns_col="selected_rule_name",
        value_col="fn_rate",
        title="Validation FN rate by preprocessing and SIMCA rule",
        show=True,
    )
else:
    print("Diagnostic plots skipped.")

Columns available in grid_summary_df:
['H_emp_cv', 'Q_emp_cv', 'accuracy', 'alpha', 'alternative_chi2_emp_cv', 'alternative_empHQ_emp_cv', 'balanced_accuracy', 'balanced_pixel_strategy', 'balanced_pixel_strategy_effective', 'cv_abs_rejection_error', 'cv_expected_rejection_rate', 'cv_n_splits', 'cv_rule_limit', 'cv_target_acceptance_rate', 'cv_target_rejection_rate', 'data_driven_emp_cv', 'f1_score', 'fn', 'fn_rate', 'fp', 'fp_rate', 'limit_source', 'm', 'm_effective', 'matrix_family', 'matrix_method', 'model_family', 'n', 'n_components', 'n_cv_groups', 'n_cv_observations', 'non_target_class', 'non_target_label', 'non_target_specificity', 'object_threshold', 'position_dilation_radius', 'precision', 'preprocessing', 'preprocessing_steps', 'rule', 'rule_for_refit', 'rule_original', 'rule_token', 'rule_variant', 'rule_variant_original', 'search_method', 'selected_rule_name', 'selection_score', 'selection_split', 'selection_strategy', 'sg_polyorder', 'sg_window_length', 'simple_emp_cv', 'target_class', 'target_sensitivity', 'tn', 'tp', 'training_matrix_id']

Number of configurations by family:

        model_family  matrix_family         training_matrix_id  n_configs
0  empirical_cv_rule  object_matrix                object_mean      10530
1  empirical_cv_rule  object_matrix              object_median      10530
2  empirical_cv_rule   pixel_matrix  balanced_pixel_center_m40      10530
3  empirical_cv_rule   pixel_matrix  balanced_pixel_random_m40      10530

Top validation configurations:

,model_family,matrix_family,training_matrix_id,matrix_method,balanced_pixel_strategy,balanced_pixel_strategy_effective,m,m_effective,preprocessing,rule,rule_variant,selected_rule_name,rule_for_refit,limit_source,n_components,alpha,object_threshold,sg_window_length,sg_polyorder,position_dilation_radius,balanced_accuracy,target_sensitivity,non_target_specificity,fn_rate,fp_rate,f1_score,accuracy,selection_score
0,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_chi2,simple_chi2,simple_chi2,chi2,7,0.01,0.75,11,2,3,0.945455,1.0,0.890909,0.0,0.109091,0.946429,0.944444,-0.042881
1,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_chi2,simple_chi2,simple_chi2,chi2,7,0.01,0.70,11,2,3,0.936364,1.0,0.872727,0.0,0.127273,0.938053,0.935185,-0.061666
2,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,7,0.05,0.75,11,2,3,0.927273,1.0,0.854545,0.0,0.145455,0.929825,0.925926,-0.080445
3,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.918182,1.0,0.836364,0.0,0.163636,0.921739,0.916667,-0.099216
4,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.05,0.75,11,2,3,0.918182,1.0,0.836364,0.0,0.163636,0.921739,0.916667,-0.099216
5,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,6,0.05,0.75,11,2,3,0.909091,1.0,0.818182,0.0,0.181818,0.913793,0.907407,-0.117980
6,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,6,0.05,0.75,11,2,3,0.909091,1.0,0.818182,0.0,0.181818,0.913793,0.907407,-0.117980
7,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,7,0.05,0.75,11,2,3,0.909091,1.0,0.818182,0.0,0.181818,0.913793,0.907407,-0.117980
8,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,7,0.05,0.75,11,2,3,0.909091,1.0,0.818182,0.0,0.181818,0.913793,0.907407,-0.117980
9,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.05,0.70,11,2,3,0.900000,1.0,0.800000,0.0,0.200000,0.905983,0.898148,-0.136738
10,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,6,0.05,0.70,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
11,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,6,0.05,0.70,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
12,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,simple,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,11,0.05,0.75,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
13,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,11,0.05,0.75,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
14,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_empHQ_fixed2,alternative_empHQ_fixed2,alternative_empHQ_fixed2,chi2,7,0.05,0.80,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
15,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,data_driven,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,7,0.01,0.75,11,2,3,0.890909,1.0,0.781818,0.0,0.218182,0.898305,0.888889,-0.155489
16,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,alternative,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
17,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,alternative,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,11,0.05,0.75,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
18,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
19,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
20,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,data_driven,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,7,0.05,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
21,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,data_driven,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,7,0.01,0.70,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
22,empirical_cv_rule,pixel_matrix,balanced_pixel_center_m40,balanced_pixels,center,center,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.01,0.75,11,2,3,0.881818,1.0,0.763636,0.0,0.236364,0.890756,0.879630,-0.174233
23,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,alternative,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,empirical_cv,11,0.05,0.70,11,2,3,0.872727,1.0,0.745455,0.0,0.254545,0.883333,0.870370,-0.192971
24,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,simple,simple_chi2,simple_chi2,simple_chi2,chi2,6,0.01,0.75,11,2,3,0.872727,1.0,0.745455,0.0,0.254545,0.883333,0.870370,-0.192971
25,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_empHQ_fixed2,alternative_empHQ_fixed2,alternative_empHQ_fixed2,chi2,7,0.05,0.75,11,2,3,0.872727,1.0,0.745455,0.0,0.254545,0.883333,0.870370,-0.192971
26,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_empHQ_fixed2,alternative_empHQ_fixed2,alternative_empHQ_fixed2,chi2,7,0.05,0.70,11,2,3,0.863636,1.0,0.727273,0.0,0.272727,0.876033,0.861111,-0.211703
27,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.01,0.80,11,2,3,0.863636,1.0,0.727273,0.0,0.272727,0.876033,0.861111,-0.211703
28,empirical_cv_rule,pixel_matrix,balanced_pixel_center_m40,balanced_pixels,center,center,40.0,40,absorbance_sg_smooth,alternative,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,7,0.01,0.70,11,2,3,0.863636,1.0,0.727273,0.0,0.272727,0.876033,0.861111,-0.211703
29,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,random,random,40.0,40,absorbance_sg_d1,alternative,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,alternative_empHQ_emp_cv,empirical_cv,7,0.05,0.75,11,2,3,0.854545,1.0,0.709091,0.0,0.290909,0.868852,0.851852,-0.230429

# 3. Models selection

## 2-way

In [9]:
pareto_2way_df, pareto_audit_df = sequential_pareto_filter(
    grid_summary_df,
    passes=TWO_WAY_PARETO_PASSES,
)

display(pareto_2way_df.head(30))
display(pareto_audit_df.head(30))

,target_class,non_target_class,n,tp,fn,fp,tn,target_sensitivity,non_target_specificity,balanced_accuracy,accuracy,precision,f1_score,fn_rate,fp_rate,object_threshold,selection_score,search_method,model_family,matrix_family,training_matrix_id,matrix_method,m,m_effective,balanced_pixel_strategy,balanced_pixel_strategy_effective,preprocessing,preprocessing_steps,rule_variant,rule,n_components,alpha,non_target_label,sg_window_length,sg_polyorder,position_dilation_radius,cv_n_splits,n_cv_observations,n_cv_groups,H_emp_cv,Q_emp_cv,simple_emp_cv,alternative_chi2_emp_cv,alternative_empHQ_emp_cv,data_driven_emp_cv,cv_target_rejection_rate,cv_target_acceptance_rate,cv_expected_rejection_rate,cv_abs_rejection_error,cv_rule_limit,rule_original,rule_variant_original,rule_token,selected_rule_name,rule_for_refit,limit_source,selection_split,selection_strategy,kept_after_within_same_model_preprocessing,kept_after_within_same_family_components,kept_after_family_level_pareto
0,peanut,non_target,108,52,1,43,12,0.981132,0.218182,0.599657,0.592593,0.547368,0.702703,0.018868,0.781818,0.70,-0.923510,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,absorbance_sg_d2,absorbance+sg_d2,data_driven_emp_cv,data_driven,3,0.01,non_target,11,2,3,5,98,98,17.640046,2.147866e-09,4.319395,4.536808,1.380628,384.212136,0.010204,0.989796,0.01,0.000204,384.212136,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
1,peanut,non_target,108,49,4,37,18,0.924528,0.327273,0.625901,0.620370,0.569767,0.705036,0.075472,0.672727,0.70,-1.379785,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,absorbance_sg_d2,absorbance+sg_d2,simple_emp_cv,simple,3,0.01,non_target,11,2,3,5,98,98,17.640046,2.147866e-09,4.319395,4.536808,1.380628,384.212136,0.010204,0.989796,0.01,0.000204,4.319395,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
2,peanut,non_target,108,50,3,41,14,0.943396,0.254545,0.598971,0.592593,0.549451,0.694444,0.056604,0.745455,0.75,-1.264918,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,absorbance_sg_d2,absorbance+sg_d2,data_driven_emp_cv,data_driven,3,0.01,non_target,11,2,3,5,98,98,17.640046,2.147866e-09,4.319395,4.536808,1.380628,384.212136,0.010204,0.989796,0.01,0.000204,384.212136,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
3,peanut,non_target,108,46,7,33,22,0.867925,0.400000,0.633962,0.629630,0.582278,0.696970,0.132075,0.600000,0.75,-1.873314,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,absorbance_sg_d2,absorbance+sg_d2,simple_emp_cv,simple,3,0.01,non_target,11,2,3,5,98,98,17.640046,2.147866e-09,4.319395,4.536808,1.380628,384.212136,0.010204,0.989796,0.01,0.000204,4.319395,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
4,peanut,non_target,108,25,28,0,55,0.471698,1.000000,0.735849,0.740741,1.000000,0.641026,0.528302,0.000000,0.70,-5.236153,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,snv_sg_smooth,snv+sg_smooth,data_driven_chi2,data_driven,4,0.01,non_target,11,2,3,5,98,98,18.895228,2.341019e-01,3.433846,4.875279,2.000000,76.558987,NaN,NaN,NaN,NaN,NaN,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
5,peanut,non_target,108,25,28,0,55,0.471698,1.000000,0.735849,0.740741,1.000000,0.641026,0.528302,0.000000,0.70,-5.236153,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,snv_sg_smooth,snv+sg_smooth,simple_chi2,simple,4,0.01,non_target,11,2,3,5,98,98,18.895228,2.341019e-01,3.433846,4.875279,2.000000,76.558987,0.081633,0.918367,0.01,0.071633,1.000000,simple_chi2,simple_chi2,simple_chi2,simple_chi2,simple_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
6,peanut,non_target,108,34,19,7,48,0.641509,0.872727,0.757118,0.759259,0.829268,0.723404,0.358491,0.127273,0.70,-3.660823,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,snv_sg_smooth,snv+sg_smooth,alternative_chi2_fixed2,alternative,5,0.01,non_target,11,2,3,5,98,98,45.136574,1.327660e-01,3.030255,4.622751,1.606315,74.430072,0.051020,0.948980,0.01,0.041020,2.000000,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
7,peanut,non_target,108,36,17,8,47,0.679245,0.854545,0.766895,0.768519,0.818182,0.742268,0.320755,0.145455,0.70,-3.300518,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,snv_sg_smooth,snv+sg_smooth,data_driven_emp_cv,data_driven,5,0.05,non_target,11,2,3,5,98,98,18.624849,5.885094e-02,2.043967,2.754401,1.716303,33.656979,0.051020,0.948980,0.05,0.001020,33.656979,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
8,peanut,non_target,108,43,10,31,24,0.811321,0.436364,0.623842,0.620370,0.581081,0.677165,0.188679,0.563636,0.75,-2.404163,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,raw,raw,data_driven_emp_cv,data_driven,5,0.01,non_target,11,2,3,5,98,98,21.229577,2.463414e-03,2.673598,3.849419,1.824855,100.195705,0.010204,0.989796,0.01,0.000204,100.195705,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
9,peanut,non_target,108,32,21,3,52,0.603774,0.945455,0.774614,0.777778,0.914286,0.727273,0.396226,0.054545,0.70,-3.964890,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,sg_smooth,sg_smooth,simple_emp_cv,simple,6,0.05,non_target,11,2,3,5,98,98,14.797680,5.433677e-04,1.782483,2.369317,1.716960,29.574876,0.051020,0.948980,0.05,0.001020,1.782483,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
10,peanut,non_target,108,44,9,32,23,0.830189,0.418182,0.624185,0.620370,0.578947,0.682171,0.169811,0.581818,0.75,-2.233415,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,raw,raw,alternative_chi2_emp_cv,alternative,7,0.01,non_target,11,2,3,5,98,98,27.217186,2.211840e-03,3.327402,4.558000,1.824633,133.510948,0.010204,0.989796,0.01,0.000204,4.558000,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
11,peanut,non_target,108,30,23,1,54,0.566038,0.981818,0.773928,0.777778,0.967742,0.714286,0.433962,0.018182,0.75,-4.306535,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,sg_smooth,sg_smooth,simple_emp_cv,simple,7,0.05,non_target,11,2,3,5,98,98,20.100980,3.305598e-04,2.015471,2.496171,1.739322,32.016064,0.051020,0.948980,0.05,0.001020,2.015471,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
12,peanut,non_target,108,53,0,52,3,1.000000,0.054545,0.527273,0.518519,0.504762,0.670886,0.000000,0.945455,0.75,-0.901540,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_mean,object_mean,NaN,40,not_applicable,random,absorbance_sg_smooth,absorbance+sg_smooth,data_driven_emp_cv,data_driven,11,0.01,non_target,11,2,3,5,98,98,66.668455,5.685526e-05,16.527747,17.928278,1.512749,1333.969396,0.010204,0.989796,0.01,0.000204,1333.969396,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
13,peanut,non_target,108,42,11,21,34,0.792453,0.618182,0.705317,0.703704,0.666667,0.724138,0.207547,0.381818,0.75,-2.407009,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_mean,object_mean,NaN,40,not_applicable,random,sg_smooth,sg_smooth,data_driven_emp_cv,data_driven,11,0.01,non_target,11,2,3,5,98,98,62.957511,7.068460e-05,30.627501,32.347995,1.667018,2450.343326,0.010204,0.989796,0.01,0.000204,2450.343326,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
14,peanut,non_target,108,40,13,15,40,0.754717,0.727273,0.740995,0.740741,0.727273,0.740741,0.245283,0.272727,0.80,-2.673706,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_mean,object_mean,NaN,40,not_applicable,random,sg_smooth,sg_smooth,data_driven_emp_cv,data_driven,11,0.01,non_target,11,2,3,5,98,98,62.957511,7.068460e-05,30.627501,32.347995,1.667018,2450.343326,0.010204,0.989796,0.01,0.000204,2450.343326,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
15,peanut,non_target,108,41,12,18,37,0.773585,0.672727,0.723156,0.722222,0.694915,0.732143,0.226415,0.327273,0.80,-2.540372,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_mean,object_mean,NaN,40,not_applicable,random,sg_smooth,sg_smooth,simple_emp_cv,simple,11,0.01,non_target,11,2,3,5,98,98,62.957511,7.068460e-05,30.627501,32.347995,1.667018,2450.343326,0.010204,0.989796,0.01,0.000204,30.627501,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
16,peanut,non_target,108,47,6,1,54,0.886792,0.981818,0.934305,0.935185,0.979167,0.930693,0.113208,0.018182,0.75,-1.085019,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_snv_sg_smooth,absorbance+snv+sg_smooth,simple_chi2,simple,6,0.05,non_target,11,2,3,5,3813,98,17.033529,7.378638e-02,1.882563,2.562897,1.865231,33.418789,0.135589,0.864411,0.05,0.085589,1.000000,simple_chi2,simple_chi2,simple_chi2,simple_chi2,simple_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
17,peanut,non_target,108,50,3,4,51,0.943396,0.927273,0.935334,0.935185,0.925926,0.934579,0.056604,0.072727,0.70,-0.573332,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_center_m40,balanced_pixels,40.0,40,center,center,absorbance_sg_smooth,absorbance+sg_smooth,simple_emp_cv,simple,7,0.05,non_target,11,2,3,5,3813,98,15.766826,6.045119e-04,1.484390,2.135544,1.804045,28.439537,0.050092,0.949908,0.05,0.000092,1.484390,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
18,peanut,non_target,108,53,0,6,49,1.000000,0.890909,0.945455,0.944444,0.898305,0.946429,0.000000,0.109091,0.75,-0.042881,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_sg_smooth,absorbance+sg_smooth,simple_chi2,simple,7,0.01,non_target,11,2,3,5,3813,98,44.364550,1.107117e-03,2.928617,3.657661,1.978258,65.289202,0.062418,0.937582,0.01,0.052418,1.000000,simple_chi2,simple_chi2,simple_chi2,simple_chi2,simple_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
19,peanut,non_target,108,49,4,3,52,0.924528,0.945455,0.934991,0.935185,0.942308,0.933333,0.075472,0.054545,0.80,-0.743892,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_sg_smooth,absorbance+sg_smooth,simple_chi2,simple,7,0.01,non_target,11,2,3,5,3813,98,44.364550,1.107117e-03,2.928617,3.657661,1.978258,65.289202,0.062418,0.937582,0.01,0.052418,1.000000,simple_chi2,simple_chi2,simple_chi2,simple_chi2,simple_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
20,peanut,non_target,108,50,3,4,51,0.943396,0.927273,0.935334,0.935185,0.925926,0.934579,0.056604,0.072727,0.70,-0.573332,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_snv_sg_d1,absorbance+snv+sg_d1,data_driven_chi2,data_driven,11,0.01,non_target,11,2,3,5,3813,98,75.529605,1.615514e-05,5.584598,7.789223,1.942916,454.098399,NaN,NaN,NaN,NaN,NaN,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True
21,peanut,non_target,108,46,7,0,55,0.867925,1.000000,0.933962,0.935185,1.000000,0.929293,0.132075,0.000000,0.70,-1.255586,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_snv_sg_d1,absorbance+snv+sg_d1,data_driven_chi2,data_driven,11,0.05,non_target,11,2,3,5,3813,98,28.840906,6.825617e-06,2.404213,3.441965,1.868725,182.643106,NaN,NaN,NaN,NaN,NaN,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True

                         pass_name  n_before  n_after  n_removed  removed_rate
0  within_same_model_preprocessing     42120    19145      22975      0.545465
1    within_same_family_components     19145     1079      18066      0.943641
2              family_level_pareto      1079       22       1057      0.979611

In [10]:
selected_04A_2way_df = (
    pareto_2way_df
    .sort_values(
        ["matrix_family", "fn_rate", "fp_rate", "balanced_accuracy"],
        ascending=[True, True, True, False],
    )
    .groupby("matrix_family", group_keys=False)
    .head(60)
    .reset_index(drop=True)
)

selected_04A_2way_df["selected_config_id"] = [
    f"04A_{row.matrix_family}_{i:04d}"
    for i, row in enumerate(selected_04A_2way_df.itertuples(), start=1)
]

In [11]:
(
    refit_04A_metrics_df,
    refit_04A_objects_df,
    refit_04A_pixels_df,
    refit_04A_pixel_errors_df,
    refit_04A_errors_df,
) = refit_selected_simca_configs(
    selected_configs_df=selected_04A_2way_df,
    object_db=object_db,
    image_db=image_db,
    train_filters=TRAIN_FILTERS,
    projection_filters=VALIDATION_FILTERS,
    preprocessing_configs=PREPROCESSING_CONFIGS,
    evaluation_split="validation_batch_3_refit",
    wavelengths=wavelengths,
    random_state=42,
    cv_n_splits=5,
    cv_group_col="object_id",
    target_class=TARGET_CLASS,
    non_target_label=NON_TARGET_LABEL,
)

[validation_batch_3_refit] 04A_object_matrix_0001
[validation_batch_3_refit] 04A_object_matrix_0002
[validation_batch_3_refit] 04A_object_matrix_0003
[validation_batch_3_refit] 04A_object_matrix_0004
[validation_batch_3_refit] 04A_object_matrix_0005
[validation_batch_3_refit] 04A_object_matrix_0006
[validation_batch_3_refit] 04A_object_matrix_0007
[validation_batch_3_refit] 04A_object_matrix_0008
[validation_batch_3_refit] 04A_object_matrix_0009
[validation_batch_3_refit] 04A_object_matrix_0010
[validation_batch_3_refit] 04A_object_matrix_0011
[validation_batch_3_refit] 04A_object_matrix_0012
[validation_batch_3_refit] 04A_object_matrix_0013
[validation_batch_3_refit] 04A_object_matrix_0014
[validation_batch_3_refit] 04A_object_matrix_0015
[validation_batch_3_refit] 04A_object_matrix_0016
[validation_batch_3_refit] 04A_pixel_matrix_0017
[validation_batch_3_refit] 04A_pixel_matrix_0018
[validation_batch_3_refit] 04A_pixel_matrix_0019
[validation_batch_3_refit] 04A_pixel_matrix_0020
[validation_batch_3_refit] 04A_pixel_matrix_0021
[validation_batch_3_refit] 04A_pixel_matrix_0022

## 3-way

In [12]:
THREE_WAY_CONFIG_COLS = ["selected_config_id"]

three_way_grid_04A_df, three_way_selected_04A_df = calibrate_three_way_thresholds_by_config(
    object_df=refit_04A_objects_df,
    config_cols=THREE_WAY_CONFIG_COLS,
    target_class=TARGET_CLASS,
    non_target_label=NON_TARGET_LABEL,
    lower_thresholds=np.round(np.arange(0.05, 0.61, 0.05), 2),
    upper_thresholds=np.round(np.arange(0.40, 0.96, 0.05), 2),
    max_target_miss_rate=0.00,
    max_false_accept_rate=0.35,
    max_uncertain_rate=0.60,
)

In [13]:
selected_04A_candidates_df = selected_04A_2way_df.merge(
    three_way_selected_04A_df[
        [
            "selected_config_id",
            "three_way_lower_threshold",
            "three_way_upper_threshold",
            "target_miss_rate",
            "non_target_false_accept_rate",
            "uncertain_rate",
            "coverage_rate",
        ]
    ].rename(
        columns={
            "target_miss_rate": "val3_target_miss_rate",
            "non_target_false_accept_rate": "val3_false_accept_rate",
            "uncertain_rate": "val3_uncertain_rate",
            "coverage_rate": "val3_coverage_rate",
        }
    ),
    on="selected_config_id",
    how="left",
)

display(selected_04A_candidates_df.head(30))

save_parquet(grid_summary_df, GRID_SUMMARY_PATH)
save_parquet(pareto_2way_df, PARETO_2WAY_PATH)
save_parquet(three_way_grid_04A_df, THREE_WAY_GRID_PATH)
save_parquet(selected_04A_candidates_df, SELECTED_CANDIDATE_CONFIGS_PATH)

,target_class,non_target_class,n,tp,fn,fp,tn,target_sensitivity,non_target_specificity,balanced_accuracy,accuracy,precision,f1_score,fn_rate,fp_rate,object_threshold,selection_score,search_method,model_family,matrix_family,training_matrix_id,matrix_method,m,m_effective,balanced_pixel_strategy,balanced_pixel_strategy_effective,preprocessing,preprocessing_steps,rule_variant,rule,n_components,alpha,non_target_label,sg_window_length,sg_polyorder,position_dilation_radius,cv_n_splits,n_cv_observations,n_cv_groups,H_emp_cv,Q_emp_cv,simple_emp_cv,alternative_chi2_emp_cv,alternative_empHQ_emp_cv,data_driven_emp_cv,cv_target_rejection_rate,cv_target_acceptance_rate,cv_expected_rejection_rate,cv_abs_rejection_error,cv_rule_limit,rule_original,rule_variant_original,rule_token,selected_rule_name,rule_for_refit,limit_source,selection_split,selection_strategy,kept_after_within_same_model_preprocessing,kept_after_within_same_family_components,kept_after_family_level_pareto,selected_config_id,three_way_lower_threshold,three_way_upper_threshold,val3_target_miss_rate,val3_false_accept_rate,val3_uncertain_rate,val3_coverage_rate
0,peanut,non_target,108,53,0,52,3,1.000000,0.054545,0.527273,0.518519,0.504762,0.670886,0.000000,0.945455,0.75,-0.901540,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_mean,object_mean,NaN,40,not_applicable,random,absorbance_sg_smooth,absorbance+sg_smooth,data_driven_emp_cv,data_driven,11,0.01,non_target,11,2,3,5,98,98,66.668455,5.685526e-05,16.527747,17.928278,1.512749,1333.969396,0.010204,0.989796,0.01,0.000204,1333.969396,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0001,0.05,0.95,0.0,0.545455,0.435185,0.564815
1,peanut,non_target,108,52,1,43,12,0.981132,0.218182,0.599657,0.592593,0.547368,0.702703,0.018868,0.781818,0.70,-0.923510,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,absorbance_sg_d2,absorbance+sg_d2,data_driven_emp_cv,data_driven,3,0.01,non_target,11,2,3,5,98,98,17.640046,2.147866e-09,4.319395,4.536808,1.380628,384.212136,0.010204,0.989796,0.01,0.000204,384.212136,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0002,0.55,0.95,0.0,0.218182,0.712963,0.287037
2,peanut,non_target,108,50,3,41,14,0.943396,0.254545,0.598971,0.592593,0.549451,0.694444,0.056604,0.745455,0.75,-1.264918,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,absorbance_sg_d2,absorbance+sg_d2,data_driven_emp_cv,data_driven,3,0.01,non_target,11,2,3,5,98,98,17.640046,2.147866e-09,4.319395,4.536808,1.380628,384.212136,0.010204,0.989796,0.01,0.000204,384.212136,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0003,0.55,0.95,0.0,0.218182,0.712963,0.287037
3,peanut,non_target,108,49,4,37,18,0.924528,0.327273,0.625901,0.620370,0.569767,0.705036,0.075472,0.672727,0.70,-1.379785,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,absorbance_sg_d2,absorbance+sg_d2,simple_emp_cv,simple,3,0.01,non_target,11,2,3,5,98,98,17.640046,2.147866e-09,4.319395,4.536808,1.380628,384.212136,0.010204,0.989796,0.01,0.000204,4.319395,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0004,0.55,0.95,0.0,0.109091,0.814815,0.185185
4,peanut,non_target,108,46,7,33,22,0.867925,0.400000,0.633962,0.629630,0.582278,0.696970,0.132075,0.600000,0.75,-1.873314,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,absorbance_sg_d2,absorbance+sg_d2,simple_emp_cv,simple,3,0.01,non_target,11,2,3,5,98,98,17.640046,2.147866e-09,4.319395,4.536808,1.380628,384.212136,0.010204,0.989796,0.01,0.000204,4.319395,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0005,0.55,0.95,0.0,0.109091,0.814815,0.185185
5,peanut,non_target,108,44,9,32,23,0.830189,0.418182,0.624185,0.620370,0.578947,0.682171,0.169811,0.581818,0.75,-2.233415,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,raw,raw,alternative_chi2_emp_cv,alternative,7,0.01,non_target,11,2,3,5,98,98,27.217186,2.211840e-03,3.327402,4.558000,1.824633,133.510948,0.010204,0.989796,0.01,0.000204,4.558000,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,alternative_chi2_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0006,0.30,0.90,0.0,0.272727,0.546296,0.453704
6,peanut,non_target,108,43,10,31,24,0.811321,0.436364,0.623842,0.620370,0.581081,0.677165,0.188679,0.563636,0.75,-2.404163,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,raw,raw,data_driven_emp_cv,data_driven,5,0.01,non_target,11,2,3,5,98,98,21.229577,2.463414e-03,2.673598,3.849419,1.824855,100.195705,0.010204,0.989796,0.01,0.000204,100.195705,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0007,0.35,0.85,0.0,0.327273,0.500000,0.500000
7,peanut,non_target,108,42,11,21,34,0.792453,0.618182,0.705317,0.703704,0.666667,0.724138,0.207547,0.381818,0.75,-2.407009,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_mean,object_mean,NaN,40,not_applicable,random,sg_smooth,sg_smooth,data_driven_emp_cv,data_driven,11,0.01,non_target,11,2,3,5,98,98,62.957511,7.068460e-05,30.627501,32.347995,1.667018,2450.343326,0.010204,0.989796,0.01,0.000204,2450.343326,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0008,0.40,0.80,0.0,0.272727,0.472222,0.527778
8,peanut,non_target,108,41,12,18,37,0.773585,0.672727,0.723156,0.722222,0.694915,0.732143,0.226415,0.327273,0.80,-2.540372,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_mean,object_mean,NaN,40,not_applicable,random,sg_smooth,sg_smooth,simple_emp_cv,simple,11,0.01,non_target,11,2,3,5,98,98,62.957511,7.068460e-05,30.627501,32.347995,1.667018,2450.343326,0.010204,0.989796,0.01,0.000204,30.627501,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0009,0.45,0.80,0.0,0.327273,0.435185,0.564815
9,peanut,non_target,108,40,13,15,40,0.754717,0.727273,0.740995,0.740741,0.727273,0.740741,0.245283,0.272727,0.80,-2.673706,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_mean,object_mean,NaN,40,not_applicable,random,sg_smooth,sg_smooth,data_driven_emp_cv,data_driven,11,0.01,non_target,11,2,3,5,98,98,62.957511,7.068460e-05,30.627501,32.347995,1.667018,2450.343326,0.010204,0.989796,0.01,0.000204,2450.343326,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0010,0.40,0.80,0.0,0.272727,0.472222,0.527778
10,peanut,non_target,108,36,17,8,47,0.679245,0.854545,0.766895,0.768519,0.818182,0.742268,0.320755,0.145455,0.70,-3.300518,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,snv_sg_smooth,snv+sg_smooth,data_driven_emp_cv,data_driven,5,0.05,non_target,11,2,3,5,98,98,18.624849,5.885094e-02,2.043967,2.754401,1.716303,33.656979,0.051020,0.948980,0.05,0.001020,33.656979,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,data_driven_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0011,0.20,0.75,0.0,0.090909,0.583333,0.416667
11,peanut,non_target,108,34,19,7,48,0.641509,0.872727,0.757118,0.759259,0.829268,0.723404,0.358491,0.127273,0.70,-3.660823,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,snv_sg_smooth,snv+sg_smooth,alternative_chi2_fixed2,alternative,5,0.01,non_target,11,2,3,5,98,98,45.136574,1.327660e-01,3.030255,4.622751,1.606315,74.430072,0.051020,0.948980,0.01,0.041020,2.000000,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,alternative_chi2_fixed2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0012,0.20,0.70,0.0,0.127273,0.500000,0.500000
12,peanut,non_target,108,32,21,3,52,0.603774,0.945455,0.774614,0.777778,0.914286,0.727273,0.396226,0.054545,0.70,-3.964890,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,sg_smooth,sg_smooth,simple_emp_cv,simple,6,0.05,non_target,11,2,3,5,98,98,14.797680,5.433677e-04,1.782483,2.369317,1.716960,29.574876,0.051020,0.948980,0.05,0.001020,1.782483,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0013,0.10,0.60,0.0,0.090909,0.564815,0.435185
13,peanut,non_target,108,30,23,1,54,0.566038,0.981818,0.773928,0.777778,0.967742,0.714286,0.433962,0.018182,0.75,-4.306535,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,sg_smooth,sg_smooth,simple_emp_cv,simple,7,0.05,non_target,11,2,3,5,98,98,20.100980,3.305598e-04,2.015471,2.496171,1.739322,32.016064,0.051020,0.948980,0.05,0.001020,2.015471,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0014,0.15,0.70,0.0,0.090909,0.574074,0.425926
14,peanut,non_target,108,25,28,0,55,0.471698,1.000000,0.735849,0.740741,1.000000,0.641026,0.528302,0.000000,0.70,-5.236153,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,snv_sg_smooth,snv+sg_smooth,data_driven_chi2,data_driven,4,0.01,non_target,11,2,3,5,98,98,18.895228,2.341019e-01,3.433846,4.875279,2.000000,76.558987,NaN,NaN,NaN,NaN,NaN,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0015,0.15,0.65,0.0,0.036364,0.564815,0.435185
15,peanut,non_target,108,25,28,0,55,0.471698,1.000000,0.735849,0.740741,1.000000,0.641026,0.528302,0.000000,0.70,-5.236153,grid_empirical_cv_rules,empirical_cv_rule,object_matrix,object_median,object_median,NaN,40,not_applicable,random,snv_sg_smooth,snv+sg_smooth,simple_chi2,simple,4,0.01,non_target,11,2,3,5,98,98,18.895228,2.341019e-01,3.433846,4.875279,2.000000,76.558987,0.081633,0.918367,0.01,0.071633,1.000000,simple_chi2,simple_chi2,simple_chi2,simple_chi2,simple_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_object_matrix_0016,0.15,0.65,0.0,0.072727,0.574074,0.425926
16,peanut,non_target,108,53,0,6,49,1.000000,0.890909,0.945455,0.944444,0.898305,0.946429,0.000000,0.109091,0.75,-0.042881,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_sg_smooth,absorbance+sg_smooth,simple_chi2,simple,7,0.01,non_target,11,2,3,5,3813,98,44.364550,1.107117e-03,2.928617,3.657661,1.978258,65.289202,0.062418,0.937582,0.01,0.052418,1.000000,simple_chi2,simple_chi2,simple_chi2,simple_chi2,simple_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_pixel_matrix_0017,0.55,0.95,0.0,0.000000,0.314815,0.685185
17,peanut,non_target,108,50,3,4,51,0.943396,0.927273,0.935334,0.935185,0.925926,0.934579,0.056604,0.072727,0.70,-0.573332,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_center_m40,balanced_pixels,40.0,40,center,center,absorbance_sg_smooth,absorbance+sg_smooth,simple_emp_cv,simple,7,0.05,non_target,11,2,3,5,3813,98,15.766826,6.045119e-04,1.484390,2.135544,1.804045,28.439537,0.050092,0.949908,0.05,0.000092,1.484390,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,simple_emp_cv,empirical_cv,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_pixel_matrix_0018,0.55,0.90,0.0,0.000000,0.287037,0.712963
18,peanut,non_target,108,50,3,4,51,0.943396,0.927273,0.935334,0.935185,0.925926,0.934579,0.056604,0.072727,0.70,-0.573332,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_snv_sg_d1,absorbance+snv+sg_d1,data_driven_chi2,data_driven,11,0.01,non_target,11,2,3,5,3813,98,75.529605,1.615514e-05,5.584598,7.789223,1.942916,454.098399,NaN,NaN,NaN,NaN,NaN,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_pixel_matrix_0019,0.60,0.75,0.0,0.000000,0.166667,0.833333
19,peanut,non_target,108,49,4,3,52,0.924528,0.945455,0.934991,0.935185,0.942308,0.933333,0.075472,0.054545,0.80,-0.743892,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_sg_smooth,absorbance+sg_smooth,simple_chi2,simple,7,0.01,non_target,11,2,3,5,3813,98,44.364550,1.107117e-03,2.928617,3.657661,1.978258,65.289202,0.062418,0.937582,0.01,0.052418,1.000000,simple_chi2,simple_chi2,simple_chi2,simple_chi2,simple_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_pixel_matrix_0020,0.55,0.95,0.0,0.000000,0.314815,0.685185
20,peanut,non_target,108,47,6,1,54,0.886792,0.981818,0.934305,0.935185,0.979167,0.930693,0.113208,0.018182,0.75,-1.085019,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_snv_sg_smooth,absorbance+snv+sg_smooth,simple_chi2,simple,6,0.05,non_target,11,2,3,5,3813,98,17.033529,7.378638e-02,1.882563,2.562897,1.865231,33.418789,0.135589,0.864411,0.05,0.085589,1.000000,simple_chi2,simple_chi2,simple_chi2,simple_chi2,simple_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_pixel_matrix_0021,0.50,0.80,0.0,0.000000,0.157407,0.842593
21,peanut,non_target,108,46,7,0,55,0.867925,1.000000,0.933962,0.935185,1.000000,0.929293,0.132075,0.000000,0.70,-1.255586,grid_empirical_cv_rules,empirical_cv_rule,pixel_matrix,balanced_pixel_random_m40,balanced_pixels,40.0,40,random,random,absorbance_snv_sg_d1,absorbance+snv+sg_d1,data_driven_chi2,data_driven,11,0.05,non_target,11,2,3,5,3813,98,28.840906,6.825617e-06,2.404213,3.441965,1.868725,182.643106,NaN,NaN,NaN,NaN,NaN,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,data_driven_chi2,chi2,validation_batch_3,04A_grid_rule_variant_universe,True,True,True,04A_pixel_matrix_0022,0.50,0.70,0.0,0.000000,0.148148,0.851852

WindowsPath('C:/Users/alixg/OneDrive - Université Paris-Dauphine/hsi_nuts/results/04A_simca_grid_validation_non_noisy_all/selected_candidate_configs.parquet')

## Pixel matrices

### Best balanced accuracy

In [14]:
#combined_summary_df[(combined_summary_df['matrix_family']=='pixel_matrix') & (combined_summary_df['balanced_accuracy']>0.92)].sort_values('balanced_accuracy', ascending=False)[cols].drop_duplicates()

In [15]:
#selected_indices = combined_summary_df[(combined_summary_df['matrix_family']=='pixel_matrix') & (combined_summary_df['balanced_accuracy']>0.92)].sort_values('balanced_accuracy', ascending=False)[cols].drop_duplicates().index
#pixel_best_ba = combined_summary_df.filter(items=selected_indices, axis=0)

### Best fn_rate

In [16]:
#combined_summary_df[(combined_summary_df['matrix_family']=='pixel_matrix') & (combined_summary_df['fn']==0) & (combined_summary_df['fp_rate']<0.50)].sort_values('fp_rate')[cols].drop_duplicates().head(20)

In [17]:
#selected_indices = combined_summary_df[(combined_summary_df['matrix_family']=='pixel_matrix') & (combined_summary_df['fn']==0) & (combined_summary_df['fp_rate']<0.50)].sort_values('fp_rate')[cols].drop_duplicates().head(20).index
#pixel_best_fn = combined_summary_df.filter(items=selected_indices, axis=0)

### Best score

In [18]:
#combined_summary_df[(combined_summary_df['matrix_family']=='pixel_matrix') ].sort_values('selection_score', ascending=False)[cols].drop_duplicates().head(15)

In [19]:
#selected_indices = combined_summary_df[(combined_summary_df['matrix_family']=='pixel_matrix') ].sort_values('selection_score', ascending=False)[cols].drop_duplicates().head(15).index
#pixel_best_selection_score = combined_summary_df.filter(items=selected_indices, axis=0)

In [20]:
#pixel_best_ba.shape[0], pixel_best_fn.shape[0], pixel_best_selection_score.shape[0]

In [21]:
#best_pixel = pd.concat([pixel_best_ba, pixel_best_fn, pixel_best_selection_score], axis=0).drop_duplicates()
#best_pixel[cols]

In [22]:
#best_pixel.shape[0]

## Object matrices

In [23]:
#combined_summary_df[combined_summary_df['matrix_family']=='object_matrix'][cols]

### Best balanced accuracy

In [24]:
#combined_summary_df[(combined_summary_df['matrix_family']=='object_matrix') & (combined_summary_df['balanced_accuracy']>0.71)][cols].drop_duplicates().sort_values('balanced_accuracy', ascending=False)

In [25]:
# selected_indices = combined_summary_df[(combined_summary_df['matrix_family']=='object_matrix') & (combined_summary_df['balanced_accuracy']>0.71)][cols].drop_duplicates().sort_values('balanced_accuracy', ascending=False).index
# object_best_ba = combined_summary_df.filter(items=selected_indices, axis=0)
# object_best_ba.shape[0]

### Best fn_rate

In [26]:
# object_best_fn = combined_summary_df[(combined_summary_df['matrix_family']=='object_matrix') & (combined_summary_df['fn']==0)].sort_values('fp_rate')
# object_best_fn[cols]

### Best selection score

In [27]:
# object_best_score = combined_summary_df[(combined_summary_df['matrix_family']=='object_matrix') & (combined_summary_df['non_target_specificity'] > 0.2)].sort_values('selection_score', ascending=False).head(10)
# object_best_score[cols]

In [28]:
# object_best_index = pd.concat([object_best_ba, object_best_fn, object_best_score])[cols].drop_duplicates().index
# object_best = combined_summary_df.filter(items=object_best_index, axis=0).sort_values('balanced_accuracy', ascending=False)
# object_best[cols]

## Automatic selection

In [29]:
# selected_candidates_df = select_top_models(
#     combined_summary_df,
#     n_per_training_matrix=N_SELECTED_PER_TRAINING_MATRIX,
#     n_per_matrix_family=N_SELECTED_PER_MATRIX_FAMILY,
#     n_overall=N_SELECTED_OVERALL,
# )

# selected_candidates_df = ensure_candidate_columns(selected_candidates_df)
# selected_candidates_df = normalize_simca_rule_columns(selected_candidates_df)
# selected_candidates_df = fill_selected_config_defaults(
#     selected_candidates_df,
#     default_values={
#         "target_class": TARGET_CLASS,
#         "non_target_label": NON_TARGET_LABEL,
#         "m": DEFAULT_M,
#         "sg_window_length": DEFAULT_SG_WINDOW_LENGTH,
#         "sg_polyorder": DEFAULT_SG_POLYORDER,
#         "position_dilation_radius": POSITION_DILATION_RADIUS_VALUES[0],
#         "alpha": ALPHA_VALUES[0],
#         "object_threshold": OBJECT_THRESHOLDS[0],
#     },
# )

# selected_candidates_df = add_detection_selection_score(selected_candidates_df)
# selected_candidates_df = add_reference_selection_scores(selected_candidates_df)
# selected_candidates_df = sort_detection_selection(selected_candidates_df, add_score=False)

# selected_candidates_df = selected_candidates_df.reset_index(drop=True)
# selected_candidates_df["selected_config_id"] = [
#     f"valcand_{i:03d}" for i in range(len(selected_candidates_df))
# ]
# selected_candidates_df["selection_split"] = "validation_batch_3"
# selected_candidates_df["selection_strategy"] = "04A_grid_validation_broad_panel"

# keep_cols = [
#     "selected_config_id",
#     "selection_split",
#     "selection_strategy",

#     "model_family",
#     "matrix_family",
#     "training_matrix_id",
#     "matrix_method",
#     "balanced_pixel_strategy",
#     "balanced_pixel_strategy_effective",
#     "m",
#     "m_effective",

#     "preprocessing",
#     "preprocessing_steps",

#     "rule",
#     "rule_variant",
#     "selected_rule_name",
#     "rule_for_refit",
#     "limit_source",

#     "target_class",
#     "non_target_label",

#     "n",
#     "tp",
#     "fn",
#     "fp",
#     "tn",
#     "balanced_accuracy",
#     "target_sensitivity",
#     "non_target_specificity",
#     "fn_rate",
#     "fp_rate",
#     "f1_score",
#     "accuracy",
#     "precision",

#     "selection_score",
#     "score_conservative_target",
#     "score_balanced_reference",
#     "score_specificity_control",

#     "n_components",
#     "alpha",
#     "object_threshold",
#     "sg_window_length",
#     "sg_polyorder",
#     "position_dilation_radius",

#     "n_train_observations",
#     "n_projected_pixels",

#     "cv_target_rejection_rate",
#     "cv_target_acceptance_rate",
#     "cv_expected_rejection_rate",
#     "cv_abs_rejection_error",
#     "cv_rule_limit",
# ]

# keep_cols = [col for col in keep_cols if col in selected_candidates_df.columns]
# selected_candidates_df = selected_candidates_df[keep_cols].copy()

# if selected_candidates_df.empty:
#     raise RuntimeError("No candidate configuration was selected.")

# save_parquet(selected_candidates_df, SELECTED_CANDIDATE_CONFIGS_PATH)

# print("Selected candidate configurations:", selected_candidates_df.shape)
# print("Saved:", SELECTED_CANDIDATE_CONFIGS_PATH)

# display(selected_candidates_df)

## Selected models

In [30]:
parameter_tendencies_df = summarize_parameter_tendencies(
    grid_summary_df,
    top_fraction=0.15,
    min_top_n=20,
)

print("Parameter tendencies among top-ranked validation models:")
display(parameter_tendencies_df.head(80))

Parameter tendencies among top-ranked validation models:

,parameter,value,count,rate_in_top_models,matrix_family,n_top_models
0,alpha,0.01,2503,0.792339,object_matrix,3159
1,alpha,0.05,656,0.207661,object_matrix,3159
2,balanced_pixel_strategy,not_applicable,3159,1.000000,object_matrix,3159
3,m,NaN,3159,1.000000,object_matrix,3159
4,matrix_method,object_median,3011,0.953150,object_matrix,3159
5,matrix_method,object_mean,148,0.046850,object_matrix,3159
6,n_components,3,455,0.144033,object_matrix,3159
7,n_components,4,385,0.121874,object_matrix,3159
8,n_components,5,366,0.115859,object_matrix,3159
9,n_components,6,356,0.112694,object_matrix,3159
10,n_components,8,327,0.103514,object_matrix,3159
11,n_components,10,323,0.102248,object_matrix,3159
12,n_components,7,322,0.101931,object_matrix,3159
13,n_components,11,319,0.100981,object_matrix,3159
14,n_components,12,306,0.096866,object_matrix,3159
15,object_threshold,0.7,958,0.303261,object_matrix,3159
16,object_threshold,0.75,826,0.261475,object_matrix,3159
17,object_threshold,0.8,646,0.204495,object_matrix,3159
18,object_threshold,0.85,449,0.142134,object_matrix,3159
19,object_threshold,0.9,280,0.088636,object_matrix,3159
20,position_dilation_radius,3,3159,1.000000,object_matrix,3159
21,preprocessing,snv_sg_d1,513,0.162393,object_matrix,3159
22,preprocessing,snv_sg_smooth,493,0.156062,object_matrix,3159
23,preprocessing,sg_smooth,389,0.123140,object_matrix,3159
24,preprocessing,snv,317,0.100348,object_matrix,3159
25,preprocessing,absorbance_snv_sg_d1,303,0.095916,object_matrix,3159
26,preprocessing,absorbance_snv_sg_smooth,263,0.083254,object_matrix,3159
27,preprocessing,raw,253,0.080089,object_matrix,3159
28,preprocessing,absorbance_msc,149,0.047167,object_matrix,3159
29,preprocessing,absorbance_snv,142,0.044951,object_matrix,3159
30,preprocessing,absorbance_sg_d1,131,0.041469,object_matrix,3159
31,preprocessing,absorbance_sg_smooth,129,0.040836,object_matrix,3159
32,preprocessing,absorbance_sg_d2,57,0.018044,object_matrix,3159
33,preprocessing,absorbance,20,0.006331,object_matrix,3159
34,rule,alternative,1749,0.553656,object_matrix,3159
35,rule,simple,660,0.208927,object_matrix,3159
36,rule,data_driven,625,0.197847,object_matrix,3159
37,rule,combined_index,125,0.039569,object_matrix,3159
38,rule_variant,simple_emp_cv,633,0.200380,object_matrix,3159
39,rule_variant,alternative_empHQ_fixed2,600,0.189934,object_matrix,3159
40,rule_variant,data_driven_emp_cv,591,0.187085,object_matrix,3159
41,rule_variant,alternative_chi2_emp_cv,561,0.177588,object_matrix,3159
42,rule_variant,alternative_empHQ_emp_cv,484,0.153213,object_matrix,3159
43,rule_variant,combined_index_chi2,125,0.039569,object_matrix,3159
44,rule_variant,alternative_chi2_fixed2,104,0.032922,object_matrix,3159
45,rule_variant,data_driven_chi2,34,0.010763,object_matrix,3159
46,rule_variant,simple_chi2,27,0.008547,object_matrix,3159
47,selected_rule_name,simple_emp_cv,633,0.200380,object_matrix,3159
48,selected_rule_name,alternative_empHQ_fixed2,600,0.189934,object_matrix,3159
49,selected_rule_name,data_driven_emp_cv,591,0.187085,object_matrix,3159
50,selected_rule_name,alternative_chi2_emp_cv,561,0.177588,object_matrix,3159
51,selected_rule_name,alternative_empHQ_emp_cv,484,0.153213,object_matrix,3159
52,selected_rule_name,combined_index_chi2,125,0.039569,object_matrix,3159
53,selected_rule_name,alternative_chi2_fixed2,104,0.032922,object_matrix,3159
54,selected_rule_name,data_driven_chi2,34,0.010763,object_matrix,3159
55,selected_rule_name,simple_chi2,27,0.008547,object_matrix,3159
56,sg_polyorder,2,3159,1.000000,object_matrix,3159
57,sg_window_length,11,3159,1.000000,object_matrix,3159
58,training_matrix_id,object_median,3011,0.953150,object_matrix,3159
59,training_matrix_id,object_mean,148,0.046850,object_matrix,3159
60,alpha,0.01,1915,0.606204,pixel_matrix,3159
61,alpha,0.05,1244,0.393796,pixel_matrix,3159
62,balanced_pixel_strategy,random,2012,0.636910,pixel_matrix,3159
63,balanced_pixel_strategy,center,1147,0.363090,pixel_matrix,3159
64,m,40.0,3159,1.000000,pixel_matrix,3159
65,matrix_method,balanced_pixels,3159,1.000000,pixel_matrix,3159
66,n_components,8,427,0.135169,pixel_matrix,3159
67,n_components,7,424,0.134220,pixel_matrix,3159
68,n_components,10,413,0.130738,pixel_matrix,3159
69,n_components,11,401,0.126939,pixel_matrix,3159
70,n_components,6,398,0.125989,pixel_matrix,3159
71,n_components,12,388,0.122824,pixel_matrix,3159
72,n_components,5,278,0.088003,pixel_matrix,3159
73,n_components,4,218,0.069009,pixel_matrix,3159
74,n_components,3,212,0.067110,pixel_matrix,3159
75,object_threshold,0.7,943,0.298512,pixel_matrix,3159
76,object_threshold,0.75,733,0.232035,pixel_matrix,3159
77,object_threshold,0.8,632,0.200063,pixel_matrix,3159
78,object_threshold,0.85,453,0.143400,pixel_matrix,3159
79,object_threshold,0.9,398,0.125989,pixel_matrix,3159

In [31]:
grid_validation_protocol_df = pd.DataFrame([{
    "db_h5_path": str(DB_H5_PATH),
    "results_dir": str(RESULTS_DIR),

    "wavelength_mode": WAVELENGTH_MODE,
    "use_wavelength_window": bool(USE_WAVELENGTH_WINDOW),
    "results_tag": RESULTS_TAG,
    "window_min_nm": WINDOW_MIN_NM if USE_WAVELENGTH_WINDOW else np.nan,
    "window_max_nm": WINDOW_MAX_NM if USE_WAVELENGTH_WINDOW else np.nan,
    "n_active_bands": int(len(wavelengths)) if wavelengths is not None else np.nan,

    "target_class": TARGET_CLASS,
    "non_target_label": NON_TARGET_LABEL,
    "reference_classes_json": json.dumps(list(REFERENCE_CLASSES)),

    "train_filters_json": json.dumps(TRAIN_FILTERS, default=str),
    "validation_filters_json": json.dumps(VALIDATION_FILTERS, default=str),
    "test_filters_json": json.dumps(TEST_FILTERS, default=str),

    "standard_matrix_methods_json": json.dumps(STANDARD_MATRIX_METHODS),
    "run_all_pixels_standard": bool(RUN_ALL_PIXELS_STANDARD),
    "run_empirical_for_all_pixels": bool(RUN_EMPIRICAL_FOR_ALL_PIXELS),

    "rule_names_json": json.dumps(SIMCA_RULE_VARIANTS_MAIN),

    "preprocessing_configs_json": json.dumps(
        {name: list(steps) for name, steps in PREPROCESSING_CONFIGS.items()},
        default=str,
    ),
    "pca_selected_preprocessings_path": str(PCA_SELECTED_PREPROCESSINGS_PATH),
    "used_pca_preprocessing_shortlist": bool(PCA_SELECTED_PREPROCESSINGS_PATH.exists()),

    "n_components_values_json": json.dumps(N_COMPONENTS_VALUES),
    "alpha_values_json": json.dumps(ALPHA_VALUES),
    "object_thresholds_json": json.dumps(OBJECT_THRESHOLDS),
    "m_values_json": json.dumps(M_VALUES),
    "balanced_pixel_strategy_values_json": json.dumps(BALANCED_PIXEL_STRATEGY_VALUES),
    "sg_window_length_values_json": json.dumps(SG_WINDOW_LENGTH_VALUES),
    "sg_polyorder_values_json": json.dumps(SG_POLYORDER_VALUES),
    "position_dilation_radius_values_json": json.dumps(POSITION_DILATION_RADIUS_VALUES),

    "random_state": int(RANDOM_STATE),
    "replace_balanced_pixels": bool(REPLACE_BALANCED_PIXELS),
    "cv_n_splits": int(CV_N_SPLITS) if CV_N_SPLITS is not None else np.nan,
    "cv_group_col": CV_GROUP_COL,

    "n_grid_rows": int(len(grid_summary_df)),
    "n_selected_candidate_configs": int(len(selected_04A_candidates_df)),

    "grid_summary_path": str(SIMCA_RULE_VARIANTS_MAIN),
    "combined_grid_summary_path": str(GRID_SUMMARY_PATH),
    "selected_candidate_configs_path": str(SELECTED_CANDIDATE_CONFIGS_PATH),
}])

save_parquet(grid_validation_protocol_df, GRID_VALIDATION_PROTOCOL_PATH)

print("Saved grid validation protocol:")
print(GRID_VALIDATION_PROTOCOL_PATH)

display(grid_validation_protocol_df)

Saved grid validation protocol:
C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04A_simca_grid_validation_non_noisy_all\grid_validation_protocol.parquet

,db_h5_path,results_dir,wavelength_mode,use_wavelength_window,results_tag,window_min_nm,window_max_nm,n_active_bands,target_class,non_target_label,reference_classes_json,train_filters_json,validation_filters_json,test_filters_json,standard_matrix_methods_json,run_all_pixels_standard,run_empirical_for_all_pixels,rule_names_json,preprocessing_configs_json,pca_selected_preprocessings_path,used_pca_preprocessing_shortlist,n_components_values_json,alpha_values_json,object_thresholds_json,m_values_json,balanced_pixel_strategy_values_json,sg_window_length_values_json,sg_polyorder_values_json,position_dilation_radius_values_json,random_state,replace_balanced_pixels,cv_n_splits,cv_group_col,n_grid_rows,n_selected_candidate_configs,grid_summary_path,combined_grid_summary_path,selected_candidate_configs_path
0,C:\Users\alixg\OneDrive - Université Paris-Dau...,C:\Users\alixg\OneDrive - Université Paris-Dau...,non_noisy_all,False,non_noisy_all,NaN,NaN,63,peanut,non_target,"[""almond"", ""peanut""]","{""sample_kind"": [""pure""], ""object_nut_type"": [...","{""sample_kind"": [""pure""], ""object_nut_type"": [...","{""sample_kind"": [""pure""], ""object_nut_type"": [...","[""object_mean"", ""object_median"", ""balanced_pix...",False,False,"[""simple_chi2"", ""simple_emp_cv"", ""alternative_...","{""absorbance_sg_d1"": [""absorbance"", ""sg_d1""], ...",C:\Users\alixg\OneDrive - Université Paris-Dau...,True,"[3, 4, 5, 6, 7, 8, 10, 11, 12]","[0.05, 0.01]","[0.7, 0.75, 0.8, 0.85, 0.9]",[40],"[""random"", ""center""]",[11],[2],[3],42,False,5,object_id,42120,22,"('simple_chi2', 'simple_emp_cv', 'alternative_...",C:\Users\alixg\OneDrive - Université Paris-Dau...,C:\Users\alixg\OneDrive - Université Paris-Dau...

In [32]:
print("04A_simca_grid_validation.ipynb completed.")
print()
print("Essential outputs:")
print(" -", GRID_SUMMARY_PATH)
print(" -", GRID_SUMMARY_PATH)
print(" -", SELECTED_CANDIDATE_CONFIGS_PATH)
print(" -", GRID_VALIDATION_PROTOCOL_PATH)

print()
print("Summary:")
print(f" - Wavelength mode: {WAVELENGTH_MODE}")
print(f" - Active bands: {len(wavelengths) if wavelengths is not None else 'unknown'}")
print(f" - Grid rows: {len(grid_summary_df)}")
print(f" - Selected candidate configs: {len(selected_04A_candidates_df)}")
print()
print("Next notebook:")
print("04B_simca_validation_robustness.ipynb")

04A_simca_grid_validation.ipynb completed.

Essential outputs:
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04A_simca_grid_validation_non_noisy_all\grid_summary.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04A_simca_grid_validation_non_noisy_all\grid_summary.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04A_simca_grid_validation_non_noisy_all\selected_candidate_configs.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04A_simca_grid_validation_non_noisy_all\grid_validation_protocol.parquet

Summary:
 - Wavelength mode: non_noisy_all
 - Active bands: 63
 - Grid rows: 42120
 - Selected candidate configs: 22

Next notebook:
04B_simca_validation_robustness.ipynb