# 04B - SIMCA Optuna Search

This notebook runs Optuna challenger searches for the new workflow. The search space uses the same PCA preprocessing scope as 04A, with object and pixel matrix families kept separate.

It does not select final models. It writes all completed Optuna model candidates and a separate table containing only candidates not already present in the 04A grid.

## Inputs and outputs

Inputs:
- `results/03_pca_<RESULTS_TAG>/pca_selected_preprocessings.parquet`
- `results/04A_simca_grid_search_<RESULTS_TAG>/grid_model_candidates.parquet`
- `HSI Data/processed/nir_uco_database.h5`

Outputs:
- `optuna_trials.parquet`: all Optuna trials
- `optuna_completed_trials.parquet`: completed trials only
- `optuna_model_candidates.parquet`: all deduplicated Optuna candidates
- `optuna_new_model_candidates.parquet`: candidates not already generated by 04A
- `optuna_candidate_metrics.parquet`: validation 2-way metrics for Optuna candidates
- `optuna_search_protocol.parquet`: run configuration

In [1]:
from pathlib import Path
import sys
import json

import numpy as np
import optuna
import pandas as pd

CURRENT_DIR = Path.cwd().resolve()
if (CURRENT_DIR / "src").exists():
    PROJECT_ROOT = CURRENT_DIR
elif (CURRENT_DIR.parent / "src").exists():
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    raise RuntimeError(
        "Could not find project root. Run this notebook from the project root or notebooks/."
    )

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)

from src import experiment_config as expcfg
from src.io.database_h5 import load_nir_uco_h5
from src.utils import load_parquet, save_parquet, list_result_files
from src.workflows.simca_tables import compact_simca_table_for_path
from src.spectra.band_selection import (
    select_wavelength_range_from_database,
    wavelength_selection_summary,
)
from src.workflows.simca import make_target_train_filters
from src.workflows.simca_candidates import (
    add_selection_track,
    build_pca_preprocessing_configs_by_matrix_family,
    deduplicate_simca_candidates,
    filter_simca_candidates_by_pca_preprocessing,
    validate_simca_candidate_contract,
    validate_simca_evaluation_contract,
)
from src.workflows.simca_optuna import (
    close_optuna_study,
    make_optuna_binary_pareto_objective,
    optuna_trials_dataframe,
    optuna_trials_to_candidate_configs,
)

PROJECT_ROOT: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts

## Configuration

Optuna is run separately for object and pixel matrix families. The saved candidates use the same candidate contract as 04A so that 04C can concatenate both sources directly.

In [ ]:
PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DB_H5_PATH = PROJECT_ROOT / "HSI Data" / "processed" / "nir_uco_database.h5"

WAVELENGTH_MODE = expcfg.DEFAULT_WAVELENGTH_MODE
RESULTS_TAG = expcfg.DEFAULT_RESULTS_TAG
RESULTS_03_DIR = PROJECT_ROOT / "results" / f"03_pca_{RESULTS_TAG}"
RESULTS_04A_DIR = PROJECT_ROOT / "results" / f"04A_simca_grid_search_{RESULTS_TAG}"
RESULTS_DIR = PROJECT_ROOT / "results" / f"04B_simca_optuna_search_{RESULTS_TAG}"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

PCA_SELECTED_PREPROCESSINGS_PATH = RESULTS_03_DIR / "pca_selected_preprocessings.parquet"
GRID_MODEL_CANDIDATES_PATH = RESULTS_04A_DIR / "grid_model_candidates.parquet"

OPTUNA_TRIALS_PATH = RESULTS_DIR / "optuna_trials.parquet"
OPTUNA_COMPLETED_TRIALS_PATH = RESULTS_DIR / "optuna_completed_trials.parquet"
OPTUNA_MODEL_CANDIDATES_PATH = RESULTS_DIR / "optuna_model_candidates.parquet"
OPTUNA_NEW_MODEL_CANDIDATES_PATH = RESULTS_DIR / "optuna_new_model_candidates.parquet"
OPTUNA_CANDIDATE_METRICS_PATH = RESULTS_DIR / "optuna_candidate_metrics.parquet"
OPTUNA_DIAGNOSTICS_PATH = RESULTS_DIR / "optuna_search_diagnostics.parquet"
OPTUNA_PROTOCOL_PATH = RESULTS_DIR / "optuna_search_protocol.parquet"
WAVELENGTH_CONFIG_PATH = RESULTS_DIR / "wavelength_config.parquet"
PREPROCESSING_SCOPE_PATH = RESULTS_DIR / "preprocessing_scope.parquet"

TARGET_CLASS = expcfg.TARGET_CLASS
NON_TARGET_LABEL = expcfg.NON_TARGET_LABEL
REFERENCE_CLASSES = list(expcfg.REFERENCE_CLASSES)

TRAIN_FILTERS = make_target_train_filters(
    target_class=TARGET_CLASS,
    train_batches=expcfg.SIMCA_TRAIN_BATCHES,
)
VALIDATION_FILTERS = {
    "sample_kind": ["pure"],
    "object_nut_type": REFERENCE_CLASSES,
    "batch": list(expcfg.SIMCA_VALIDATION_BATCHES),
}

OPTUNA_MATRIX_FAMILY_SPACES = {
    "object_matrix": {
        "matrix_methods": ["object_mean", "object_median"],
        "study_name": f"04B_object_matrix_{RESULTS_TAG}",
        "storage_path": RESULTS_DIR / "optuna_object_matrix.sqlite3",
    },
    "pixel_matrix": {
        "matrix_methods": ["balanced_pixels"],
        "study_name": f"04B_pixel_matrix_{RESULTS_TAG}",
        "storage_path": RESULTS_DIR / "optuna_pixel_matrix.sqlite3",
    },
}

RULE_VARIANTS = [
    "simple_chi2",
    "simple_emp_cv",
    "alternative_chi2_fixed2",
    "alternative_chi2_emp_cv",
    "alternative_empHQ_fixed2",
    "alternative_empHQ_emp_cv",
    "data_driven_chi2",
    "data_driven_emp_cv",
    "combined_index_chi2",
]

N_COMPONENTS_CHOICES = [3, 4, 5, 6, 7, 8, 10, 11, 12]
ALPHA_CHOICES = list(expcfg.SIMCA_ALPHA_VALUES)
OBJECT_THRESHOLDS = list(expcfg.SIMCA_OBJECT_THRESHOLDS)
M_CHOICES = [20, 40, 60, 80]
BALANCED_PIXEL_STRATEGY_CHOICES = list(expcfg.BALANCED_PIXEL_STRATEGIES)
SG_WINDOW_CHOICES = [7, 9, 11, 13, 15]
SG_POLYORDER_CHOICES = [2]
POSITION_DILATION_RADIUS_CHOICES = [2, 3, 4, 5]

USE_WAVELENGTH_WINDOW = False
WINDOW_MIN_NM = 1225.0
WINDOW_MAX_NM = 1675.0

RUN_OPTUNA = True
LOAD_EXISTING_STUDY = True
N_TRIALS_PER_FAMILY = {
    "object_matrix": 200,
    "pixel_matrix": 300,
}
OBJECTIVE_SEEDS = [0, 1, 2]
MAX_FN_RATE_FOR_THRESHOLD = 0.00
MAX_FP_RATE_FOR_THRESHOLD = 0.50
RANDOM_STATE = expcfg.RANDOM_STATE
REPLACE_BALANCED_PIXELS = expcfg.REPLACE_BALANCED_PIXELS

track_specs_df = pd.DataFrame([
    {"selection_track": track, **spec}
    for track, spec in expcfg.SIMCA_SELECTION_TRACK_SPECS.items()
])

display(track_specs_df)
print("DB_H5_PATH:", DB_H5_PATH)
print("PCA_SELECTED_PREPROCESSINGS_PATH:", PCA_SELECTED_PREPROCESSINGS_PATH)
print("GRID_MODEL_CANDIDATES_PATH:", GRID_MODEL_CANDIDATES_PATH)
print("RESULTS_DIR:", RESULTS_DIR)

,selection_track,matrix_family,decision_mode,primary_metric_level,secondary_metric_level
0,object_matrix_2way,object_matrix,2way,object,pixel
1,object_matrix_3way,object_matrix,3way,object,pixel
2,pixel_matrix_2way,pixel_matrix,2way,pixel,object
3,pixel_matrix_3way,pixel_matrix,3way,pixel,object

DB_H5_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\HSI Data\processed\nir_uco_database.h5
PCA_SELECTED_PREPROCESSINGS_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\03_pca_non_noisy_all\pca_selected_preprocessings.parquet
GRID_MODEL_CANDIDATES_PATH: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04A_simca_grid_search_non_noisy_all\grid_model_candidates.parquet
RESULTS_DIR: C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04B_simca_optuna_search_non_noisy_all

## Load inputs

In [3]:
if not DB_H5_PATH.exists():
    raise FileNotFoundError(f"Database not found: {DB_H5_PATH}. Run notebook 00 first.")
if not PCA_SELECTED_PREPROCESSINGS_PATH.exists():
    raise FileNotFoundError(
        f"PCA shortlist not found: {PCA_SELECTED_PREPROCESSINGS_PATH}. Run notebook 03 first."
    )
if not GRID_MODEL_CANDIDATES_PATH.exists():
    raise FileNotFoundError(
        f"04A grid candidates not found: {GRID_MODEL_CANDIDATES_PATH}. Run notebook 04A first."
    )

object_db, image_db = load_nir_uco_h5(
    DB_H5_PATH,
    reconstruct_heavy_object_arrays=True,
)

if USE_WAVELENGTH_WINDOW:
    object_db, image_db, wavelengths, wavelength_info = select_wavelength_range_from_database(
        object_db=object_db,
        image_db=image_db,
        min_nm=WINDOW_MIN_NM,
        max_nm=WINDOW_MAX_NM,
    )
    wavelength_selection_df = wavelength_selection_summary(wavelength_info)
else:
    first_obj = next(iter(object_db.values()))
    wavelengths = first_obj.get("wavelengths")
    wavelengths = np.asarray(wavelengths, dtype=float) if wavelengths is not None else None
    wavelength_selection_df = pd.DataFrame()

if wavelengths is None:
    raise RuntimeError("No wavelength axis found in object_db.")

pca_selected_preprocessings_df = load_parquet(PCA_SELECTED_PREPROCESSINGS_PATH)
grid_model_candidates_df = load_parquet(GRID_MODEL_CANDIDATES_PATH)
preprocessing_configs_by_family = build_pca_preprocessing_configs_by_matrix_family(
    pca_selected_preprocessings_df
)

preprocessing_scope_df = pd.DataFrame([
    {
        "matrix_family": family,
        "preprocessing": name,
        "preprocessing_steps": "+".join(steps),
    }
    for family, configs in preprocessing_configs_by_family.items()
    for name, steps in configs.items()
])

wavelength_config_df = pd.DataFrame([{
    "wavelength_mode": WAVELENGTH_MODE,
    "use_wavelength_window": bool(USE_WAVELENGTH_WINDOW),
    "results_tag": RESULTS_TAG,
    "window_min_nm": WINDOW_MIN_NM if USE_WAVELENGTH_WINDOW else np.nan,
    "window_max_nm": WINDOW_MAX_NM if USE_WAVELENGTH_WINDOW else np.nan,
    "n_bands": int(len(wavelengths)),
    "min_wavelength_nm": float(np.min(wavelengths)),
    "max_wavelength_nm": float(np.max(wavelengths)),
}])

save_parquet(compact_simca_table_for_path(wavelength_config_df, WAVELENGTH_CONFIG_PATH), WAVELENGTH_CONFIG_PATH)
save_parquet(compact_simca_table_for_path(preprocessing_scope_df, PREPROCESSING_SCOPE_PATH), PREPROCESSING_SCOPE_PATH)

print("Number of images:", len(image_db))
print("Number of objects:", len(object_db))
print("04A grid candidates:", grid_model_candidates_df.shape)
display(wavelength_config_df)
display(preprocessing_scope_df.sort_values(["matrix_family", "preprocessing"]))

Number of images: 48
Number of objects: 1262
04A grid candidates: (3240, 44)

,wavelength_mode,use_wavelength_window,results_tag,window_min_nm,window_max_nm,n_bands,min_wavelength_nm,max_wavelength_nm
0,non_noisy_all,False,non_noisy_all,NaN,NaN,63,960.735294,1702.0

   matrix_family             preprocessing       preprocessing_steps
0  object_matrix          absorbance_sg_d1          absorbance+sg_d1
1  object_matrix          absorbance_sg_d2          absorbance+sg_d2
4  object_matrix      absorbance_snv_sg_d1      absorbance+snv+sg_d1
2  object_matrix      absorbance_snv_sg_d2      absorbance+snv+sg_d2
3  object_matrix                 snv_sg_d2                 snv+sg_d2
6   pixel_matrix  absorbance_snv_sg_smooth  absorbance+snv+sg_smooth
9   pixel_matrix                       raw                       raw
8   pixel_matrix                 sg_smooth                 sg_smooth
7   pixel_matrix                       snv                       snv
5   pixel_matrix             snv_sg_smooth             snv+sg_smooth

## Run Optuna

Optuna optimizes validation 2-way object-level metrics. The generated model candidates are later refit and evaluated for both 2-way and 3-way decision layers.

In [4]:
optuna_trials_parts = []
studies = {}

for matrix_family, space in OPTUNA_MATRIX_FAMILY_SPACES.items():
    print("=" * 80)
    print(f"Optuna study for matrix_family={matrix_family}")
    print("=" * 80)

    storage_path = Path(space["storage_path"])
    storage_path.parent.mkdir(parents=True, exist_ok=True)

    objective = make_optuna_binary_pareto_objective(
        object_db=object_db,
        image_db=image_db,
        train_filters=TRAIN_FILTERS,
        projection_filters=VALIDATION_FILTERS,
        preprocessing_configs=preprocessing_configs_by_family,
        matrix_methods=space["matrix_methods"],
        rule_variants=RULE_VARIANTS,
        object_thresholds=OBJECT_THRESHOLDS,
        seeds=OBJECTIVE_SEEDS,
        max_fn_rate=MAX_FN_RATE_FOR_THRESHOLD,
        max_fp_rate=MAX_FP_RATE_FOR_THRESHOLD,
        wavelengths=wavelengths,
        target_class=TARGET_CLASS,
        non_target_label=NON_TARGET_LABEL,
        n_components_choices=N_COMPONENTS_CHOICES,
        alpha_choices=ALPHA_CHOICES,
        m_choices=M_CHOICES,
        balanced_pixel_strategy_choices=BALANCED_PIXEL_STRATEGY_CHOICES,
        sg_window_choices=SG_WINDOW_CHOICES,
        sg_polyorder_choices=SG_POLYORDER_CHOICES,
        position_dilation_radius_choices=POSITION_DILATION_RADIUS_CHOICES,
    )

    sampler = optuna.samplers.TPESampler(
        seed=RANDOM_STATE,
        multivariate=True,
        group=True,
        n_startup_trials=30,
    )
    storage = optuna.storages.RDBStorage(
        url=f"sqlite:///{storage_path.as_posix()}",
        engine_kwargs={"connect_args": {"timeout": 30.0}},
    )

    study = optuna.create_study(
        study_name=space["study_name"],
        directions=["minimize", "minimize", "maximize"],
        sampler=sampler,
        storage=storage,
        load_if_exists=LOAD_EXISTING_STUDY,
    )

    if RUN_OPTUNA:
        study.optimize(
            objective,
            n_trials=int(N_TRIALS_PER_FAMILY[matrix_family]),
            n_jobs=1,
            show_progress_bar=True,
        )

    trials_df = optuna_trials_dataframe(study)
    trials_df["matrix_family_study"] = matrix_family
    trials_df["study_name"] = space["study_name"]
    trials_df["storage_path"] = str(storage_path)
    optuna_trials_parts.append(trials_df)
    studies[matrix_family] = study

    close_optuna_study(study)

optuna_trials_df = (
    pd.concat(optuna_trials_parts, ignore_index=True, sort=False)
    if optuna_trials_parts
    else pd.DataFrame()
)
optuna_completed_trials_df = (
    optuna_trials_df.loc[optuna_trials_df["state"].astype(str).eq("COMPLETE")].copy()
    if len(optuna_trials_df) > 0
    else pd.DataFrame()
)

print("Optuna trials:", optuna_trials_df.shape)
print("Completed trials:", optuna_completed_trials_df.shape)
display(optuna_completed_trials_df.head())

================================================================================
Optuna study for matrix_family=object_matrix
================================================================================

c:\Users\alixg\anaconda3\envs\hsi-nuts\Lib\site-packages\optuna\_experimental.py:33: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  optuna_warn(
c:\Users\alixg\anaconda3\envs\hsi-nuts\Lib\site-packages\optuna\_experimental.py:33: ExperimentalWarning: Argument ``group`` is an experimental feature. The interface can change in the future.
  optuna_warn(
[I 2026-07-21 18:08:08,613] Using an existing study with name '04B_object_matrix_non_noisy_all' instead of creating a new one.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-07-21 18:08:14,213] Trial 200 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'simple_chi2', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:08:18,331] Trial 201 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'simple_chi2', 'n_components': 4, 'alpha': 0.01, 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:08:21,411] Trial 202 finished with values: [0.6037735849056604, 0.2909090909090909, 0.5526586620926244] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 4, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:08:24,221] Trial 203 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_chi2', 'n_components': 10, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:08:26,872] Trial 204 finished with values: [0.1320754716981132, 0.6, 0.6339622641509435] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:08:29,684] Trial 205 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 6, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:08:32,396] Trial 206 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'data_driven_chi2', 'n_components': 5, 'alpha': 0.01, 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:08:35,059] Trial 207 finished with values: [0.4528301886792453, 0.34545454545454546, 0.6008576329331046] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 8, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:08:37,885] Trial 208 finished with values: [0.1320754716981132, 0.8545454545454545, 0.5066895368782162] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'snv_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 5, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:08:40,863] Trial 209 finished with values: [0.18867924528301888, 0.8181818181818182, 0.49656946826758147] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'data_driven_emp_cv', 'n_components': 4, 'alpha': 0.01, 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:08:43,799] Trial 210 finished with values: [0.1320754716981132, 0.6, 0.6339622641509435] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:08:46,482] Trial 211 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d1', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 10, 'alpha': 0.01, 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:08:49,107] Trial 212 finished with values: [0.5283018867924528, 0.43636363636363634, 0.5176672384219554] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:08:51,819] Trial 213 finished with values: [0.5660377358490566, 0.12727272727272726, 0.653344768439108] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d1', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:08:54,549] Trial 214 finished with values: [0.8301886792452831, 0.21818181818181817, 0.4758147512864494] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:08:57,240] Trial 215 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 11, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:09:00,119] Trial 216 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'data_driven_emp_cv', 'n_components': 6, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:09:02,817] Trial 217 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 8, 'alpha': 0.01, 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:09:05,507] Trial 218 finished with values: [0.8490566037735849, 0.12727272727272726, 0.5118353344768439] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'snv_sg_d2', 'rule_variant': 'data_driven_emp_cv', 'n_components': 12, 'alpha': 0.01, 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:09:08,178] Trial 219 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d1', 'rule_variant': 'data_driven_chi2', 'n_components': 12, 'alpha': 0.01, 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:09:10,844] Trial 220 finished with values: [0.660377358490566, 0.0909090909090909, 0.6243567753001715] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 5, 'alpha': 0.01, 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:09:13,547] Trial 221 finished with values: [0.2641509433962264, 0.7090909090909091, 0.5133790737564322] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:16,400] Trial 222 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 6, 'alpha': 0.01, 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:19,035] Trial 223 finished with values: [0.9433962264150944, 0.0909090909090909, 0.48284734133790735] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 12, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:21,768] Trial 224 finished with values: [0.6792452830188679, 0.05454545454545454, 0.6331046312178388] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:24,412] Trial 225 finished with values: [0.8490566037735849, 0.0, 0.5754716981132075] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'snv_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 6, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:09:27,081] Trial 226 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'data_driven_chi2', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:29,850] Trial 227 finished with values: [0.1320754716981132, 0.6, 0.6339622641509435] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:09:32,567] Trial 228 finished with values: [0.2830188679245283, 0.5454545454545454, 0.5857632933104631] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d1', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 7, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:35,442] Trial 229 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 11, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:09:38,144] Trial 230 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:09:40,769] Trial 231 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 7, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:43,439] Trial 232 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 11, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:09:46,327] Trial 233 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 8, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:09:51,001] Trial 234 finished with values: [0.05660377358490566, 0.7454545454545455, 0.5989708404802745] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'data_driven_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:54,936] Trial 235 finished with values: [0.6226415094339622, 0.3090909090909091, 0.5341337907375643] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d1', 'rule_variant': 'data_driven_emp_cv', 'n_components': 12, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:09:57,720] Trial 236 finished with values: [0.05660377358490566, 0.7454545454545455, 0.5989708404802745] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'data_driven_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:00,448] Trial 237 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'snv_sg_d2', 'rule_variant': 'data_driven_chi2', 'n_components': 6, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:10:03,109] Trial 238 finished with values: [0.3018867924528302, 0.5636363636363636, 0.5672384219554031] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'data_driven_emp_cv', 'n_components': 7, 'alpha': 0.01, 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:05,876] Trial 239 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 7, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:10:08,654] Trial 240 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'alternative_empHQ_emp_cv', 'n_components': 10, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:11,253] Trial 241 finished with values: [0.7924528301886793, 0.14545454545454545, 0.5310463121783876] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'data_driven_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:13,907] Trial 242 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'data_driven_chi2', 'n_components': 12, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:10:16,699] Trial 243 finished with values: [0.1320754716981132, 0.8181818181818182, 0.5248713550600344] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'snv_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:19,496] Trial 244 finished with values: [0.24528301886792453, 0.6727272727272727, 0.5409948542024015] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'data_driven_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:10:22,098] Trial 245 finished with values: [0.6981132075471698, 0.03636363636363636, 0.6327615780445969] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 4, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:10:24,809] Trial 246 finished with values: [0.9622641509433962, 0.05454545454545454, 0.4915951972555746] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 12, 'alpha': 0.01, 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:27,361] Trial 247 finished with values: [0.03773584905660377, 0.8363636363636363, 0.5629502572898799] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:29,964] Trial 248 finished with values: [0.5283018867924528, 0.43636363636363634, 0.5176672384219554] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:32,725] Trial 249 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d1', 'rule_variant': 'alternative_empHQ_emp_cv', 'n_components': 8, 'alpha': 0.01, 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:10:35,318] Trial 250 finished with values: [0.8301886792452831, 0.20000000000000004, 0.4849056603773585] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'alternative_empHQ_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:38,065] Trial 251 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d1', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 7, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:40,795] Trial 252 finished with values: [0.6981132075471698, 0.12727272727272726, 0.5873070325900515] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 12, 'alpha': 0.01, 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:43,389] Trial 253 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'snv_sg_d2', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 8, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:10:46,440] Trial 254 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d1', 'rule_variant': 'data_driven_chi2', 'n_components': 6, 'alpha': 0.01, 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:49,048] Trial 255 finished with values: [1.0, 0.0, 0.5] and parameters: {'matrix_method': 'object_mean', 'preprocessing': 'absorbance_sg_d1', 'rule_variant': 'simple_chi2', 'n_components': 11, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:10:51,641] Trial 256 finished with values: [0.9056603773584906, 0.0909090909090909, 0.5017152658662093] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'data_driven_emp_cv', 'n_components': 5, 'alpha': 0.01, 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:55,855] Trial 257 finished with values: [0.1320754716981132, 0.6, 0.6339622641509435] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:10:58,863] Trial 258 finished with values: [0.03773584905660377, 0.9636363636363635, 0.49931389365351625] and parameters: {'matrix_method': 'object_median', 'preprocessing': 'absorbance_snv_sg_d2', 'rule_variant': 'simple_emp_cv', 'n_components': 10, 'alpha': 0.01, 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 2}.

c:\Users\alixg\anaconda3\envs\hsi-nuts\Lib\site-packages\optuna\_experimental.py:33: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  optuna_warn(
c:\Users\alixg\anaconda3\envs\hsi-nuts\Lib\site-packages\optuna\_experimental.py:33: ExperimentalWarning: Argument ``group`` is an experimental feature. The interface can change in the future.
  optuna_warn(
[I 2026-07-21 18:17:17,847] Using an existing study with name '04B_pixel_matrix_non_noisy_all' instead of creating a new one.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-07-21 18:17:23,334] Trial 300 finished with values: [0.0, 0.9454545454545454, 0.5272727272727272] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'alternative_empHQ_emp_cv', 'n_components': 7, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:17:27,252] Trial 301 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 6, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 2}.
[I 2026-07-21 18:17:32,920] Trial 302 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv_sg_smooth', 'rule_variant': 'combined_index_chi2', 'n_components': 10, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'center', 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:17:36,422] Trial 303 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'data_driven_emp_cv', 'n_components': 10, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 4}.
[I 2026-07-21 18:17:40,297] Trial 304 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'combined_index_chi2', 'n_components': 8, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 2}.
[I 2026-07-21 18:17:45,014] Trial 305 finished with values: [0.07547169811320754, 0.5636363636363636, 0.6804459691252144] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'data_driven_chi2', 'n_components': 5, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'center', 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:17:48,479] Trial 306 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 4, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 5}.
[I 2026-07-21 18:17:52,087] Trial 307 finished with values: [0.22641509433962265, 0.3090909090909091, 0.7322469982847343] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'simple_chi2', 'n_components': 3, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'center', 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:17:57,114] Trial 308 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv_sg_smooth', 'rule_variant': 'data_driven_emp_cv', 'n_components': 4, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'center', 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:18:00,016] Trial 309 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'combined_index_chi2', 'n_components': 6, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 4}.
[I 2026-07-21 18:18:03,996] Trial 310 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 3, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 5}.
[I 2026-07-21 18:18:08,946] Trial 311 finished with values: [0.07547169811320754, 0.6545454545454545, 0.634991423670669] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv_sg_smooth', 'rule_variant': 'data_driven_chi2', 'n_components': 8, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'center', 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:18:14,501] Trial 312 finished with values: [0.03773584905660377, 0.6848484848484849, 0.6387078330474557] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'simple_chi2', 'n_components': 8, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:18:18,229] Trial 313 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 2}.
[I 2026-07-21 18:18:22,919] Trial 314 finished with values: [0.018867924528301886, 0.7636363636363637, 0.6087478559176672] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'data_driven_chi2', 'n_components': 12, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:18:26,404] Trial 315 finished with values: [0.03773584905660377, 0.9333333333333332, 0.5207547169811321] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'simple_chi2', 'n_components': 4, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'random', 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:18:31,457] Trial 316 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'data_driven_emp_cv', 'n_components': 4, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'random', 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:18:34,506] Trial 317 finished with values: [0.0, 0.9818181818181818, 0.509090909090909] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 5, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 4}.
[I 2026-07-21 18:18:37,499] Trial 318 finished with values: [0.0, 0.9757575757575757, 0.5121212121212121] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'simple_emp_cv', 'n_components': 7, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 5}.
[I 2026-07-21 18:18:41,054] Trial 319 finished with values: [0.0, 0.9090909090909091, 0.5454545454545454] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 10, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'random', 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:18:46,127] Trial 320 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv_sg_smooth', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 7, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:18:50,699] Trial 321 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 3, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'center', 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:18:55,914] Trial 322 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv_sg_smooth', 'rule_variant': 'simple_emp_cv', 'n_components': 3, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'center', 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:19:00,459] Trial 323 finished with values: [0.018867924528301886, 0.9090909090909091, 0.5360205831903945] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 7, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 4}.
[I 2026-07-21 18:19:05,987] Trial 324 finished with values: [0.0, 0.9272727272727272, 0.5363636363636364] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 5, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 2}.
[I 2026-07-21 18:19:10,555] Trial 325 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 4, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 2}.
[I 2026-07-21 18:19:14,772] Trial 326 finished with values: [0.0, 0.9454545454545454, 0.5272727272727272] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'simple_emp_cv', 'n_components': 5, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'center', 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:19:18,883] Trial 327 finished with values: [0.07547169811320754, 0.4727272727272727, 0.7259005145797598] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'simple_chi2', 'n_components': 12, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 4}.
[I 2026-07-21 18:19:22,665] Trial 328 finished with values: [0.07547169811320754, 0.48484848484848486, 0.7198399085191537] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'simple_chi2', 'n_components': 12, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 3}.
[I 2026-07-21 18:19:26,398] Trial 329 finished with values: [0.05660377358490566, 0.7818181818181819, 0.5839336763865065] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'simple_chi2', 'n_components': 7, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 2}.
[I 2026-07-21 18:19:29,804] Trial 330 finished with values: [0.0, 0.9818181818181818, 0.509090909090909] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'alternative_empHQ_emp_cv', 'n_components': 4, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 3}.
[I 2026-07-21 18:19:35,511] Trial 331 finished with values: [0.07547169811320754, 0.6606060606060605, 0.6351057747284162] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'simple_chi2', 'n_components': 11, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'random', 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:19:39,972] Trial 332 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv_sg_smooth', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 8, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:19:43,385] Trial 333 finished with values: [0.0, 0.9454545454545454, 0.5272727272727272] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'simple_emp_cv', 'n_components': 7, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'center', 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:19:45,842] Trial 334 finished with values: [0.018867924528301886, 0.9818181818181818, 0.49965694682675815] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'alternative_empHQ_emp_cv', 'n_components': 4, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'center', 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:19:48,936] Trial 335 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'combined_index_chi2', 'n_components': 4, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:19:51,744] Trial 336 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 4, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 5}.
[I 2026-07-21 18:19:54,059] Trial 337 finished with values: [0.03773584905660377, 0.7757575757575758, 0.5932532875929103] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'simple_chi2', 'n_components': 5, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 5}.
[I 2026-07-21 18:19:55,991] Trial 338 finished with values: [0.0, 0.9818181818181818, 0.509090909090909] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 11, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 4}.
[I 2026-07-21 18:19:58,527] Trial 339 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'data_driven_emp_cv', 'n_components': 5, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 3}.
[I 2026-07-21 18:20:02,212] Trial 340 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'simple_emp_cv', 'n_components': 5, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'random', 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 4}.
[I 2026-07-21 18:20:06,032] Trial 341 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 5, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:20:08,976] Trial 342 finished with values: [0.18867924528301888, 0.34545454545454546, 0.7329331046312179] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv_sg_smooth', 'rule_variant': 'simple_chi2', 'n_components': 12, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'center', 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:20:11,971] Trial 343 finished with values: [0.0, 0.8545454545454545, 0.5727272727272728] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 11, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 3}.
[I 2026-07-21 18:20:14,293] Trial 344 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv_sg_smooth', 'rule_variant': 'simple_emp_cv', 'n_components': 6, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'random', 'sg_window_length': 11, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:20:16,952] Trial 345 finished with values: [0.018867924528301886, 0.9636363636363635, 0.5087478559176672] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'data_driven_chi2', 'n_components': 3, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 4}.
[I 2026-07-21 18:20:19,206] Trial 346 finished with values: [0.0, 0.9818181818181818, 0.509090909090909] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'data_driven_emp_cv', 'n_components': 12, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 2}.
[I 2026-07-21 18:20:21,494] Trial 347 finished with values: [0.0, 0.9818181818181818, 0.509090909090909] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'combined_index_chi2', 'n_components': 4, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'center', 'sg_window_length': 13, 'sg_polyorder': 2, 'position_dilation_radius': 2}.
[I 2026-07-21 18:20:24,412] Trial 348 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 7, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 5}.
[I 2026-07-21 18:20:28,156] Trial 349 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'alternative_empHQ_fixed2', 'n_components': 4, 'alpha': 0.01, 'm': 80, 'balanced_pixel_strategy': 'center', 'sg_window_length': 7, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:20:30,918] Trial 350 finished with values: [0.03773584905660377, 0.8060606060606061, 0.5843910806174958] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'snv', 'rule_variant': 'data_driven_chi2', 'n_components': 12, 'alpha': 0.01, 'm': 60, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 4}.
[I 2026-07-21 18:20:33,431] Trial 351 finished with values: [0.07547169811320754, 0.5272727272727272, 0.6986277873070326] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'data_driven_chi2', 'n_components': 11, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 5}.
[I 2026-07-21 18:20:36,580] Trial 352 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'absorbance_snv_sg_smooth', 'rule_variant': 'data_driven_emp_cv', 'n_components': 11, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'sg_window_length': 15, 'sg_polyorder': 2, 'position_dilation_radius': 3}.
[I 2026-07-21 18:20:39,305] Trial 353 finished with values: [0.0, 0.9515151515151515, 0.5242424242424243] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'sg_smooth', 'rule_variant': 'simple_emp_cv', 'n_components': 11, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'sg_window_length': 9, 'sg_polyorder': 2, 'position_dilation_radius': 5}.
[I 2026-07-21 18:20:41,606] Trial 354 finished with values: [0.0, 0.9151515151515152, 0.5424242424242424] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'alternative_chi2_fixed2', 'n_components': 5, 'alpha': 0.01, 'm': 40, 'balanced_pixel_strategy': 'random', 'position_dilation_radius': 3}.
[I 2026-07-21 18:20:43,614] Trial 355 finished with values: [0.0, 1.0, 0.5] and parameters: {'matrix_method': 'balanced_pixels', 'preprocessing': 'raw', 'rule_variant': 'alternative_chi2_emp_cv', 'n_components': 12, 'alpha': 0.01, 'm': 20, 'balanced_pixel_strategy': 'center', 'position_dilation_radius': 2}.

,number,state,value_0,value_1,value_2,objective_fn_rate_max,objective_fp_rate_mean,objective_balanced_accuracy_mean,value,matrix_method,...,fp_rate_std,m,matrix_family,model_family,object_threshold_median,preprocessing_steps,selection_strategy,matrix_family_study,study_name,storage_path
0,273,COMPLETE,0.000000,0.963636,0.518182,0.000000,0.963636,0.518182,NaN,object_median,...,1.110223e-16,40,object_matrix,rule_variant_grid,0.80,absorbance+sg_d2,optuna_binary_pareto,object_matrix,04B_object_matrix_non_noisy_all,C:\Users\alixg\OneDrive - Université Paris-Dau...
1,374,COMPLETE,0.000000,0.963636,0.518182,0.000000,0.963636,0.518182,NaN,object_median,...,1.110223e-16,40,object_matrix,rule_variant_grid,0.80,absorbance+sg_d2,optuna_binary_pareto,object_matrix,04B_object_matrix_non_noisy_all,C:\Users\alixg\OneDrive - Université Paris-Dau...
2,377,COMPLETE,0.000000,0.963636,0.518182,0.000000,0.963636,0.518182,NaN,object_median,...,1.110223e-16,40,object_matrix,rule_variant_grid,0.80,absorbance+sg_d2,optuna_binary_pareto,object_matrix,04B_object_matrix_non_noisy_all,C:\Users\alixg\OneDrive - Université Paris-Dau...
3,284,COMPLETE,0.018868,0.890909,0.545111,0.018868,0.890909,0.545111,NaN,object_median,...,1.110223e-16,40,object_matrix,rule_variant_grid,0.75,absorbance+sg_d2,optuna_binary_pareto,object_matrix,04B_object_matrix_non_noisy_all,C:\Users\alixg\OneDrive - Université Paris-Dau...
4,323,COMPLETE,0.018868,0.890909,0.545111,0.018868,0.890909,0.545111,NaN,object_median,...,1.110223e-16,40,object_matrix,rule_variant_grid,0.75,absorbance+sg_d2,optuna_binary_pareto,object_matrix,04B_object_matrix_non_noisy_all,C:\Users\alixg\OneDrive - Université Paris-Dau...

## Candidate tables

`optuna_model_candidates.parquet` contains every completed Optuna candidate. `optuna_new_model_candidates.parquet` removes configurations already generated by 04A.

In [5]:
optuna_model_candidates_df = optuna_trials_to_candidate_configs(
    optuna_completed_trials_df,
    n_per_matrix_family=0,
    n_overall=0,
    target_class=TARGET_CLASS,
    non_target_label=NON_TARGET_LABEL,
    selection_split="validation_batch_3",
    selection_strategy="04B_optuna_search",
)

if optuna_model_candidates_df.empty:
    raise RuntimeError("No completed Optuna candidate could be converted.")

optuna_model_candidates_df = filter_simca_candidates_by_pca_preprocessing(
    optuna_model_candidates_df,
    pca_selected_preprocessings_df,
    strict=True,
)
optuna_model_candidates_df = deduplicate_simca_candidates(
    optuna_model_candidates_df.assign(candidate_source="04B_optuna_search")
)
optuna_model_candidates_df["model_candidate_id"] = optuna_model_candidates_df["candidate_id"]
validate_simca_candidate_contract(optuna_model_candidates_df)

grid_candidate_ids = set(grid_model_candidates_df["candidate_id"].astype(str))
optuna_new_model_candidates_df = (
    optuna_model_candidates_df
    .loc[~optuna_model_candidates_df["candidate_id"].astype(str).isin(grid_candidate_ids)]
    .copy()
    .reset_index(drop=True)
)

optuna_candidate_metrics_df = optuna_model_candidates_df.copy()
optuna_candidate_metrics_df["decision_mode"] = "2way"
optuna_candidate_metrics_df["evaluation_stage"] = "validation_batch_3_multiseed"
optuna_candidate_metrics_df["metric_level"] = "object"
optuna_candidate_metrics_df = add_selection_track(optuna_candidate_metrics_df)
validate_simca_evaluation_contract(optuna_candidate_metrics_df)

print("All Optuna candidates:", optuna_model_candidates_df.shape)
print("New Optuna candidates vs 04A:", optuna_new_model_candidates_df.shape)
display(optuna_model_candidates_df.head())
display(optuna_new_model_candidates_df.head())

All Optuna candidates: (966, 52)
New Optuna candidates vs 04A: (966, 52)

,selected_config_id,selection_split,selection_strategy,candidate_source,optuna_trial_number,optuna_value,value_0,value_1,value_2,objective_fn_rate_max,...,alpha,object_threshold,sg_window_length,sg_polyorder,position_dilation_radius,candidate_id,candidate_sources,n_candidate_sources,n_duplicate_rows,model_candidate_id
0,optuna_0146,validation_batch_3,04B_optuna_search,04B_optuna_search,146,0.327273,0.0,0.448485,0.775758,0.0,...,0.01,0.75,15,2,4,simca_e67086871534e83d,04B_optuna_search,1,2,simca_e67086871534e83d
1,optuna_0083,validation_batch_3,04B_optuna_search,04B_optuna_search,83,-0.063636,0.0,0.709091,0.645455,0.0,...,0.01,0.75,13,2,5,simca_ca87aaf11a2e0148,04B_optuna_search,1,1,simca_ca87aaf11a2e0148
2,optuna_0090,validation_batch_3,04B_optuna_search,04B_optuna_search,90,-0.063636,0.0,0.709091,0.645455,0.0,...,0.01,0.75,15,2,5,simca_1697754d5f4757b4,04B_optuna_search,1,1,simca_1697754d5f4757b4
3,optuna_0079,validation_batch_3,04B_optuna_search,04B_optuna_search,79,-0.118182,0.0,0.745455,0.627273,0.0,...,0.01,0.75,11,2,5,simca_0a6a3e463243ade9,04B_optuna_search,1,1,simca_0a6a3e463243ade9
4,optuna_0497,validation_batch_3,04B_optuna_search,04B_optuna_search,497,-0.118182,0.0,0.745455,0.627273,0.0,...,0.01,0.75,7,2,4,simca_bd506962dd86a0c8,04B_optuna_search,1,1,simca_bd506962dd86a0c8

,selected_config_id,selection_split,selection_strategy,candidate_source,optuna_trial_number,optuna_value,value_0,value_1,value_2,objective_fn_rate_max,...,alpha,object_threshold,sg_window_length,sg_polyorder,position_dilation_radius,candidate_id,candidate_sources,n_candidate_sources,n_duplicate_rows,model_candidate_id
0,optuna_0146,validation_batch_3,04B_optuna_search,04B_optuna_search,146,0.327273,0.0,0.448485,0.775758,0.0,...,0.01,0.75,15,2,4,simca_e67086871534e83d,04B_optuna_search,1,2,simca_e67086871534e83d
1,optuna_0083,validation_batch_3,04B_optuna_search,04B_optuna_search,83,-0.063636,0.0,0.709091,0.645455,0.0,...,0.01,0.75,13,2,5,simca_ca87aaf11a2e0148,04B_optuna_search,1,1,simca_ca87aaf11a2e0148
2,optuna_0090,validation_batch_3,04B_optuna_search,04B_optuna_search,90,-0.063636,0.0,0.709091,0.645455,0.0,...,0.01,0.75,15,2,5,simca_1697754d5f4757b4,04B_optuna_search,1,1,simca_1697754d5f4757b4
3,optuna_0079,validation_batch_3,04B_optuna_search,04B_optuna_search,79,-0.118182,0.0,0.745455,0.627273,0.0,...,0.01,0.75,11,2,5,simca_0a6a3e463243ade9,04B_optuna_search,1,1,simca_0a6a3e463243ade9
4,optuna_0497,validation_batch_3,04B_optuna_search,04B_optuna_search,497,-0.118182,0.0,0.745455,0.627273,0.0,...,0.01,0.75,7,2,4,simca_bd506962dd86a0c8,04B_optuna_search,1,1,simca_bd506962dd86a0c8

## Diagnostics and save

In [6]:
optuna_diagnostics_df = (
    optuna_candidate_metrics_df
    .groupby(
        [
            "selection_track",
            "matrix_family",
            "matrix_method",
            "preprocessing",
            "rule_variant",
        ],
        dropna=False,
    )
    .agg(
        n_candidates=("candidate_id", "nunique"),
        best_fn_rate=("fn_rate", "min"),
        best_fp_rate=("fp_rate", "min"),
        best_balanced_accuracy=("balanced_accuracy", "max"),
    )
    .reset_index()
    .sort_values(
        ["matrix_family", "best_fn_rate", "best_fp_rate", "best_balanced_accuracy"],
        ascending=[True, True, True, False],
    )
    .reset_index(drop=True)
)

optuna_protocol_df = pd.DataFrame([{
    "notebook": "04B_simca_optuna_search",
    "results_tag": RESULTS_TAG,
    "db_h5_path": str(DB_H5_PATH),
    "pca_selected_preprocessings_path": str(PCA_SELECTED_PREPROCESSINGS_PATH),
    "grid_model_candidates_path": str(GRID_MODEL_CANDIDATES_PATH),
    "train_filters_json": json.dumps(TRAIN_FILTERS, default=str),
    "validation_filters_json": json.dumps(VALIDATION_FILTERS, default=str),
    "matrix_family_spaces_json": json.dumps(
        {
            family: {
                "matrix_methods": space["matrix_methods"],
                "study_name": space["study_name"],
                "storage_path": str(space["storage_path"]),
            }
            for family, space in OPTUNA_MATRIX_FAMILY_SPACES.items()
        },
        default=str,
    ),
    "rule_variants_json": json.dumps(RULE_VARIANTS),
    "n_components_choices_json": json.dumps(N_COMPONENTS_CHOICES),
    "alpha_choices_json": json.dumps(ALPHA_CHOICES),
    "object_thresholds_json": json.dumps(OBJECT_THRESHOLDS),
    "m_choices_json": json.dumps(M_CHOICES),
    "balanced_pixel_strategy_choices_json": json.dumps(BALANCED_PIXEL_STRATEGY_CHOICES),
    "sg_window_choices_json": json.dumps(SG_WINDOW_CHOICES),
    "sg_polyorder_choices_json": json.dumps(SG_POLYORDER_CHOICES),
    "position_dilation_radius_choices_json": json.dumps(POSITION_DILATION_RADIUS_CHOICES),
    "objective_seeds_json": json.dumps(OBJECTIVE_SEEDS),
    "generated_decision_modes_json": json.dumps(["2way"]),
    "downstream_decision_modes_json": json.dumps(list(expcfg.SIMCA_DECISION_MODES)),
    "n_trials": int(len(optuna_trials_df)),
    "n_completed_trials": int(len(optuna_completed_trials_df)),
    "n_optuna_model_candidates": int(len(optuna_model_candidates_df)),
    "n_optuna_new_model_candidates": int(len(optuna_new_model_candidates_df)),
    "optuna_trials_path": str(OPTUNA_TRIALS_PATH),
    "optuna_model_candidates_path": str(OPTUNA_MODEL_CANDIDATES_PATH),
    "optuna_new_model_candidates_path": str(OPTUNA_NEW_MODEL_CANDIDATES_PATH),
}])

save_parquet(compact_simca_table_for_path(optuna_trials_df, OPTUNA_TRIALS_PATH), OPTUNA_TRIALS_PATH)
save_parquet(compact_simca_table_for_path(optuna_completed_trials_df, OPTUNA_COMPLETED_TRIALS_PATH), OPTUNA_COMPLETED_TRIALS_PATH)
save_parquet(compact_simca_table_for_path(optuna_model_candidates_df, OPTUNA_MODEL_CANDIDATES_PATH), OPTUNA_MODEL_CANDIDATES_PATH)
save_parquet(compact_simca_table_for_path(optuna_new_model_candidates_df, OPTUNA_NEW_MODEL_CANDIDATES_PATH), OPTUNA_NEW_MODEL_CANDIDATES_PATH)
save_parquet(compact_simca_table_for_path(optuna_candidate_metrics_df, OPTUNA_CANDIDATE_METRICS_PATH), OPTUNA_CANDIDATE_METRICS_PATH)
save_parquet(compact_simca_table_for_path(optuna_diagnostics_df, OPTUNA_DIAGNOSTICS_PATH), OPTUNA_DIAGNOSTICS_PATH)
save_parquet(compact_simca_table_for_path(optuna_protocol_df, OPTUNA_PROTOCOL_PATH), OPTUNA_PROTOCOL_PATH)

print("Saved:")
for path in [
    OPTUNA_TRIALS_PATH,
    OPTUNA_COMPLETED_TRIALS_PATH,
    OPTUNA_MODEL_CANDIDATES_PATH,
    OPTUNA_NEW_MODEL_CANDIDATES_PATH,
    OPTUNA_CANDIDATE_METRICS_PATH,
    OPTUNA_DIAGNOSTICS_PATH,
    OPTUNA_PROTOCOL_PATH,
]:
    print(" -", path)

display(optuna_diagnostics_df.head(20))
display(list_result_files(RESULTS_DIR).head(20))

Saved:
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04B_simca_optuna_search_non_noisy_all\optuna_trials.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04B_simca_optuna_search_non_noisy_all\optuna_completed_trials.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04B_simca_optuna_search_non_noisy_all\optuna_model_candidates.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04B_simca_optuna_search_non_noisy_all\optuna_new_model_candidates.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04B_simca_optuna_search_non_noisy_all\optuna_candidate_metrics.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04B_simca_optuna_search_non_noisy_all\optuna_search_diagnostics.parquet
 - C:\Users\alixg\OneDrive - Université Paris-Dauphine\hsi_nuts\results\04B_simca_optuna_search_non_noisy_all\optuna_search_protocol.parquet

,selection_track,matrix_family,matrix_method,preprocessing,rule_variant,n_candidates,best_fn_rate,best_fp_rate,best_balanced_accuracy
0,object_matrix_2way,object_matrix,object_median,absorbance_sg_d2,data_driven_emp_cv,19,0.000000,0.072727,0.711664
1,object_matrix_2way,object_matrix,object_median,absorbance_sg_d2,simple_emp_cv,32,0.000000,0.090909,0.678731
2,object_matrix_2way,object_matrix,object_median,absorbance_sg_d1,simple_emp_cv,20,0.037736,0.018182,0.713379
3,object_matrix_2way,object_matrix,object_median,absorbance_snv_sg_d2,simple_emp_cv,9,0.037736,0.163636,0.644597
4,object_matrix_2way,object_matrix,object_median,absorbance_snv_sg_d1,alternative_chi2_emp_cv,3,0.056604,0.218182,0.607890
5,object_matrix_2way,object_matrix,object_median,snv_sg_d2,simple_emp_cv,7,0.075472,0.709091,0.524871
6,object_matrix_2way,object_matrix,object_median,snv_sg_d2,alternative_chi2_emp_cv,2,0.094340,0.545455,0.576329
7,object_matrix_2way,object_matrix,object_median,snv_sg_d2,data_driven_emp_cv,7,0.094340,0.672727,0.551458
8,object_matrix_2way,object_matrix,object_median,snv_sg_d2,alternative_empHQ_fixed2,5,0.132075,0.709091,0.551115
9,object_matrix_2way,object_matrix,object_mean,snv_sg_d2,alternative_chi2_emp_cv,2,0.150943,0.109091,0.520926
10,object_matrix_2way,object_matrix,object_median,absorbance_snv_sg_d1,simple_emp_cv,5,0.150943,0.672727,0.540995
11,object_matrix_2way,object_matrix,object_median,absorbance_snv_sg_d1,data_driven_emp_cv,6,0.188679,0.672727,0.540995
12,object_matrix_2way,object_matrix,object_mean,snv_sg_d2,simple_emp_cv,2,0.207547,0.000000,0.596226
13,object_matrix_2way,object_matrix,object_median,absorbance_snv_sg_d2,data_driven_emp_cv,3,0.207547,0.454545,0.612350
14,object_matrix_2way,object_matrix,object_median,absorbance_snv_sg_d1,alternative_empHQ_fixed2,5,0.226415,0.472727,0.546655
15,object_matrix_2way,object_matrix,object_mean,absorbance_snv_sg_d2,data_driven_emp_cv,1,0.226415,0.690909,0.541338
16,object_matrix_2way,object_matrix,object_median,absorbance_sg_d2,alternative_chi2_emp_cv,7,0.245283,0.054545,0.638250
17,object_matrix_2way,object_matrix,object_mean,absorbance_sg_d2,data_driven_emp_cv,4,0.245283,0.109091,0.650086
18,object_matrix_2way,object_matrix,object_median,absorbance_snv_sg_d1,alternative_empHQ_emp_cv,2,0.245283,0.600000,0.540995
19,object_matrix_2way,object_matrix,object_median,absorbance_snv_sg_d2,alternative_empHQ_fixed2,3,0.264151,0.254545,0.636878

                                   file  suffixes   size_mb
0           optuna_pixel_matrix.sqlite3  .sqlite3  1.890625
1          optuna_object_matrix.sqlite3  .sqlite3  1.257812
2      optuna_candidate_metrics.parquet  .parquet  0.070337
3   optuna_new_model_candidates.parquet  .parquet  0.067903
4       optuna_model_candidates.parquet  .parquet  0.067903
5       optuna_completed_trials.parquet  .parquet  0.038926
6                 optuna_trials.parquet  .parquet  0.038926
7        optuna_search_protocol.parquet  .parquet  0.025057
8     optuna_search_diagnostics.parquet  .parquet  0.007904
9             wavelength_config.parquet  .parquet  0.003999
10          preprocessing_scope.parquet  .parquet  0.002533